// relationshipDepthQuestions.tsx
import { Question } from "../../types/types";
import {
  Heart,
  Home,
  Users,
  Brain,
  Star,
  Sun,
  Moon,
  Target,
  MessageCircle,
  HandHeart,
  Lightbulb,
  Globe,
  Gift,
  Map,
  Book,
  Compass,
  Calendar,
  Coffee,
  Baby,
  Church,
} from "lucide-react";

export const relationshipDepthQuestions: Question[] = [
  {
    worldId: "RELATIONSHIP",

    id: "perfect_relationship_day",
    category: "relationship",
    subcategory: "depth",
    question:
      "תאר/י את היום המושלם בעיניך עם בן/בת הזוג. מהבוקר ועד הלילה - אילו רגעים ופעילויות יהפכו אותו למיוחד ולמה דווקא אלו?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 1000,
    placeholder:
      "שתף/י את החזון שלך ליום משותף מושלם, כולל הפעילויות, האווירה והרגשות שהיית רוצה לחוות...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "relationship_growth",
    category: "relationship",
    subcategory: "depth",
    question:
      "ספר/י על רגע משמעותי במערכת יחסים קודמת שלימד אותך משהו חשוב על עצמך ועל מה שאת/ה מחפש/ת בזוגיות. מה למדת מהחוויה הזו?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder:
      "שתף/י את החוויה והתובנות שעלו ממנה לגבי עצמך ומה שחשוב לך בקשר...",
  },
  {
    worldId: "RELATIONSHIP",
id: "family_values",
    category: "relationship",
    subcategory: "depth",
    question:
      "מהם שלושת הערכים המרכזיים שהיית רוצה שינחו את המשפחה העתידית שלך? איך היית רוצה שהם יבואו לידי ביטוי בחיי היומיום?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder:
      "תאר/י את הערכים החשובים לך ואיך הם משתלבים בחזון המשפחתי שלך...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "partnership_vision",
    category: "relationship",
    subcategory: "depth",
    question:
      "איך את/ה רואה שותפות אידיאלית בזוגיות? ספר/י על החלוקה הרצויה של אחריות, קבלת החלטות ותמיכה הדדית",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י את תפיסתך לגבי שותפות זוגית ואיך היא באה לידי ביטוי...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "conflict_handling",
    category: "relationship",
    subcategory: "depth",
    question:
      "תאר/י מצב של קונפליקט שהתמודדת איתו בעבר. מה למדת ממנו על הדרך שבה היית רוצה להתמודד עם מחלוקות בזוגיות?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י את האתגר, דרך ההתמודדות והתובנות שלמדת ממנו...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "childhood_influence",
    category: "relationship",
    subcategory: "depth",
    question:
      "איך הבית שבו גדלת השפיע על תפיסת הזוגיות שלך? מה היית רוצה לאמץ ומה היית רוצה לעשות אחרת?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 1000,
    placeholder:
      "שתף/י על ההשפעות מהבית, התובנות והשינויים שהיית רוצה ליצור...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "emotional_needs",
    category: "relationship",
    subcategory: "depth",
    question:
      "מהם הצרכים הרגשיים החשובים ביותר שלך בזוגיות? איך היית רוצה שבן/בת הזוג יבינו ויענו על צרכים אלו?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder:
      "תאר/י את הצרכים הרגשיים שלך ואיך היית רוצה שיבואו לידי ביטוי...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "life_challenges",
    category: "relationship",
    subcategory: "depth",
    question:
      "איך היית רוצה שהזוגיות שלך תתמודד עם אתגרי החיים הגדולים (כמו משברים, שינויים או קשיים)? מה חשוב לך בהתמודדות משותפת?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י את תפיסתך לגבי התמודדות זוגית עם אתגרים...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "family_dynamics",
    category: "relationship",
    subcategory: "depth",
    question:
      "איך היית רוצה לבנות את הדינמיקה המשפחתית בבית שלך? ספר/י על האווירה, התקשורת והיחסים שהיית רוצה ליצור",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר/י את החזון שלך לדינמיקה המשפחתית הרצויה...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "personal_growth",
    category: "relationship",
    subcategory: "depth",
    question:
      "איך את/ה רואה את הקשר בין צמיחה אישית לזוגיות? איך היית רוצה שהקשר יתמוך בהתפתחות האישית של כל אחד?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י את תפיסתך לגבי האיזון בין צמיחה אישית וזוגית...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "life_dreams",
    category: "relationship",
    subcategory: "depth",
    question:
      "מהם החלומות הגדולים שהיית רוצה להגשים יחד עם בן/בת הזוג? איך את/ה רואה את החיים המשותפים תורמים להגשמת חלומות אלו?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 1000,
    placeholder: "תאר/י את החלומות המשותפים והדרך להגשמתם...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "intimacy_perspective",
    category: "relationship",
    subcategory: "depth",
    question:
      "מה משמעותה של אינטימיות עבורך בקשר זוגי? איך היית רוצה שהיא תבוא לידי ביטוי ברמה הרגשית והפיזית?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י את תפיסתך לגבי אינטימיות בזוגיות...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "support_system",
    category: "relationship",
    subcategory: "depth",
    question:
      "איך את/ה רואה את מערכת התמיכה הזוגית? ספר/י על הדרכים בהן היית רוצה לתמוך ולהיתמך בקשר",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר/י את תפיסתך לגבי תמיכה הדדית בזוגיות...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "cultural_traditions",
    category: "relationship",
    subcategory: "depth",
    question:
      "אילו מסורות תרבותיות או משפחתיות חשוב לך לשמר ולבנות בבית המשותף? מה המשמעות של מסורות אלו עבורך?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י על המסורות החשובות לך והמשמעות שלהן...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "relationship_fears",
    category: "relationship",
    subcategory: "depth",
    question:
      "מהם הפחדים או החששות שלך בהקשר של זוגיות? איך היית רוצה להתמודד איתם יחד עם בן/בת הזוג?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י את החששות שלך ואיך היית רוצה להתמודד איתם...",
  },
  {
    worldId: "RELATIONSHIP",
id: "future_vision",
    category: "relationship",
    subcategory: "depth",
    question:
      "איך את/ה מדמיין/ת את חייכם המשותפים בעוד 20 שנה? מה היית רוצה שיישאר דומה ומה היית רוצה שישתנה ויתפתח?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 1000,
    placeholder: "תאר/י את החזון שלך לעתיד המשותף...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "relationship_lessons",
    category: "relationship",
    subcategory: "depth",
    question:
      "מה הדבר המשמעותי ביותר שלמדת על עצמך ממערכות יחסים קודמות? איך זה משפיע על מה שאת/ה מחפש/ת היום?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י את התובנות והלקחים שלמדת...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "change_handling",
    category: "relationship",
    subcategory: "depth",
    question:
      "איך את/ה רואה את היכולת של זוגיות להתמודד עם שינויים משמעותיים בחיים? מה חשוב לך בהתמודדות כזו?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר/י את תפיסתך לגבי התמודדות עם שינויים בזוגיות...",
  },
  {
    worldId: "RELATIONSHIP",
    id: "relationship_growth",
    category: "relationship",
    subcategory: "depth",
    question:
      "איך היית רוצה לראות את הזוגיות שלך מתפתחת וצומחת לאורך השנים? מה יעזור לה להישאר מרעננת ומתחדשת?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י את חזונך לצמיחה והתפתחות בזוגיות...",
  },
  {
    worldId: "RELATIONSHIP",
id: "success_definition",
    category: "relationship",
    subcategory: "depth",
    question:
      "מה מבחינתך מגדיר זוגיות מוצלחת? אילו איכויות או מאפיינים הכי חשובים לך בקשר ארוך טווח?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר/י את תפיסתך לגבי זוגיות מוצלחת...",
  },
];

export default relationshipDepthQuestions;
