// src/components/questionnaire/questions/relationship/relationshipQuestions.tsx
import { Question } from '../../types/types';
import {
  Briefcase,
  BookOpen,
  Target,
  Heart,
  Users,
  Home,
  MessageCircle,
  Scale,
  Brain,
  Moon,
  Sparkles,
  HandHeart,
  ShieldCheck,
  Link,
  Map,
  Clock,
  Award,
  Baby,
  Coffee,
  Bed,
  Smile,
  Gift,
  Info,
  HelpCircle,
} from 'lucide-react';

export const relationshipQuestions: Question[] = [
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_core_meaning_revised',
    category: 'relationship',
    subcategory: 'core_expectations',
    type: 'multiSelect',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'deep_emotional_connection', icon: <Heart /> },
      { value: 'friendship_support', icon: <Users /> },
      { value: 'commitment_security', icon: <Link /> },
      { value: 'shared_growth', icon: <Sparkles /> },
      { value: 'building_home_family', icon: <Home /> },
    ],
    minSelections: 1,
    maxSelections: 2,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_key_feelings_from_partner_revised',
    category: 'relationship',
    subcategory: 'core_expectations',
    type: 'multiSelectWithOther',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'support_understanding', icon: <HandHeart /> },
      { value: 'appreciation_respect', icon: <Award /> },
      { value: 'security_trust', icon: <ShieldCheck /> },
      { value: 'desire_attraction', icon: <Sparkles /> },
      { value: 'lightness_fun', icon: <Smile /> },
      { value: 'intellectual_partnership', icon: <Brain /> },
    ],
    minSelections: 1,
    maxSelections: 3,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_love_languages',
    category: 'relationship',
    subcategory: 'core_expectations',
    type: 'multiSelect',
    depth: 'BASIC',
    isRequired: false,
    minSelections: 1,
    maxSelections: 2,
    options: [
      { value: 'words_of_affirmation' },
      { value: 'quality_time' },
      { value: 'physical_touch' },
      { value: 'acts_of_service' },
      { value: 'receiving_gifts' },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_communication_ideal_revised',
    category: 'relationship',
    subcategory: 'communication_intimacy',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'openness_directness', icon: <MessageCircle /> },
      { value: 'sensitivity_empathy', icon: <Heart /> },
      { value: 'solution_focused', icon: <Brain /> },
      { value: 'balance', icon: <Scale /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_handling_partner_disappointment_revised',
    category: 'relationship',
    subcategory: 'communication_intimacy',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'withdraw_process', icon: <Moon /> },
      { value: 'immediate_talk', icon: <MessageCircle /> },
      { value: 'suppression', icon: <ShieldCheck /> },
      { value: 'logical_analysis', icon: <Brain /> },
      { value: 'not_sure', icon: <HelpCircle /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_repair_mechanism',
    category: 'relationship',
    subcategory: 'communication_intimacy',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'processing_talk', icon: <MessageCircle /> },
      { value: 'hug_move_on', icon: <HandHeart /> },
      { value: 'time_out', icon: <Clock /> },
      { value: 'change_of_scenery', icon: <Sparkles /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_meaningful_apology',
    category: 'relationship',
    subcategory: 'communication_intimacy',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'express_remorse', icon: <Heart /> },
      { value: 'take_responsibility', icon: <ShieldCheck /> },
      { value: 'offer_to_fix', icon: <Target /> },
      { value: 'saying_sorry', icon: <MessageCircle /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_silent_treatment_view',
    category: 'relationship',
    subcategory: 'communication_intimacy',
    type: 'scale',
    depth: 'ADVANCED',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_expressing_needs',
    category: 'relationship',
    subcategory: 'communication_intimacy',
    type: 'singleChoice',
    depth: 'EXPERT',
    isRequired: false,
    options: [
        { value: 'keep_inside' },
        { value: 'wait_for_right_moment' },
        { value: 'direct_conversation' },
        { value: 'hint_repeatedly' },
    ],
    metadata: { estimatedTime: 1 },
},

{
    worldId: 'RELATIONSHIP',
    id: 'relationship_physical_intimacy_importance',
    category: 'relationship',
    subcategory: 'communication_intimacy',
    type: 'scale',
    depth: 'EXPERT',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
},
{
    worldId: 'RELATIONSHIP',
    id: 'relationship_screen_time_approach',
    category: 'relationship',
    subcategory: 'daily_life_partnership',
    type: 'singleChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
        { value: 'very_limited' },
        { value: 'balanced_usage' },
        { value: 'flexible_usage' },
    ],
    metadata: { estimatedTime: 1 },
},
{
    worldId: 'RELATIONSHIP',
    id: 'relationship_argument_style',
    category: 'relationship',
    subcategory: 'communication_intimacy',
    type: 'singleChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
        { value: 'expressive_emotive' },
        { value: 'need_time_to_process' },
        { value: 'immediate_resolution' },
        { value: 'conflict_avoidant' },
    ],
    metadata: { estimatedTime: 1 },
},


  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_partner_bad_day',
    category: 'relationship',
    subcategory: 'daily_life_partnership',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'listen_contain', icon: <Heart /> },
      { value: 'analyze_solve', icon: <Brain /> },
      { value: 'give_space', icon: <Home /> },
      { value: 'distract', icon: <Sparkles /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_receiving_support',
    category: 'relationship',
    subcategory: 'daily_life_partnership',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'need_to_vent', icon: <MessageCircle /> },
      { value: 'need_solutions', icon: <Brain /> },
      { value: 'need_distraction', icon: <Sparkles /> },
      { value: 'need_space', icon: <Home /> },
    ],
    metadata: { estimatedTime: 1 },
},

  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_household_philosophy',
    category: 'relationship',
    subcategory: 'daily_life_partnership',
    type: 'openText',
    depth: 'BASIC',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_daily_togetherness_vs_autonomy_revised',
    category: 'relationship',
    subcategory: 'daily_life_partnership',
    type: 'scale',
    depth: 'BASIC',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_role_in_growth',
    category: 'relationship',
    subcategory: 'growth_challenges',
    type: 'scale',
    depth: 'EXPERT',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_celebrating_success',
    category: 'relationship',
    subcategory: 'daily_life_partnership',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 30,
    maxLength: 300,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_family_vision_children_revised',
    category: 'relationship',
    subcategory: 'family_future_vision',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'central_part', icon: <Baby /> },
      { value: 'see_myself_as_parent', icon: <Home /> },
      { value: 'open_but_not_essential', icon: <Scale /> },
      { value: 'less_relevant', icon: <Heart /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_deal_breaker_summary_final_revised',
    category: 'relationship',
    subcategory: 'growth_challenges',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 50,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_dating_journey_reflection',
    category: 'relationship',
    subcategory: 'growth_challenges',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'new_to_process', icon: <Sparkles /> },
      { value: 'some_experience', icon: <Map /> },
      { value: 'long_journey', icon: <Clock /> },
      { value: 'taking_a_break', icon: <Moon /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELATIONSHIP',
    id: 'relationship_dating_journey_lesson',
    category: 'relationship',
    subcategory: 'growth_challenges',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 50,
    maxLength: 500,
    metadata: { estimatedTime: 3 },
  },
];
