// src/components/questionnaire/questions/partner/partnerQuestions.tsx
import { Question } from '../../types/types';
import {
  Heart,
  Brain,
  Smile,
  ShieldCheck,
  Star,
  Users,
  Moon,
  Home,
  Target,
  Scale,
  BookOpen,
  Scroll,
  Activity,
  Coffee,
  Eye,
  Car,
  Flag,
  Globe,
  HandHeart,
  Lightbulb,
  Briefcase,
  PiggyBank,
  Info,
  Sparkles,
  Palette,
  Headphones,
  MessageCircle,
  TrendingUp,
  Building2,
  Mountain,
  TreePine,
  MapPin,
  DollarSign,
  HelpCircle,
} from 'lucide-react';

export const partnerQuestions: Question[] = [
  {
    worldId: 'PARTNER',
    id: 'partner_initial_impression_priorities_revised',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'multiSelect',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'appearance_style', icon: <Eye /> },
      { value: 'smile_energy', icon: <Smile /> },
      { value: 'conversation_chemistry', icon: <MessageCircle /> },
      { value: 'wit_depth', icon: <Brain /> },
      { value: 'sense_of_security', icon: <ShieldCheck /> },
    ],
    minSelections: 1,
    maxSelections: 3,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_appearance_importance_scale_revised',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'scale',
    depth: 'BASIC',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_intelligence_types',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'budgetAllocation',
    depth: 'ADVANCED',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'emotional', icon: <Heart /> },
      { value: 'analytical', icon: <Brain /> },
      { value: 'life_smarts', icon: <Sparkles /> },
      { value: 'creative', icon: <Lightbulb /> },
      { value: 'spiritual_torah', icon: <BookOpen /> },
    ],
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_core_character_traits_essential_revised',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'budgetAllocation',
    depth: 'BASIC',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'integrity', icon: <ShieldCheck /> },
      { value: 'warmth', icon: <Heart /> },
      { value: 'optimism', icon: <Smile /> },
      { value: 'maturity', icon: <Target /> },
      { value: 'ambition', icon: <Star /> },
      { value: 'communication', icon: <HandHeart /> },
    ],
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_completion_trait',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 20,
    maxLength: 300,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_emotional_expression_preference',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'singleChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
        { value: 'open_verbal' },
        { value: 'action_oriented' },
        { value: 'balanced' },
        { value: 'not_critical' },
    ],
    metadata: { estimatedTime: 1 },
},

  {
    worldId: 'PARTNER',
    id: 'partner_dating_persona',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'budgetAllocation',
    depth: 'ADVANCED',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'observer_listener', icon: <Headphones /> },
      { value: 'storyteller_initiator', icon: <MessageCircle /> },
      { value: 'humorous_light', icon: <Smile /> },
      { value: 'deep_serious', icon: <Brain /> },
      { value: 'shy_reserved', icon: <Moon /> },
    ],
    metadata: { estimatedTime: 3 },
  },

  {
    worldId: 'PARTNER',
    id: 'partner_lifestyle_pace_preference_revised',
    category: 'partner',
    subcategory: 'lifestyle_social',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'dynamic_active', icon: <Activity /> },
      { value: 'calm_serene', icon: <Home /> },
      { value: 'balanced', icon: <Scale /> },
      { value: 'adventurous_spontaneous', icon: <Sparkles /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_financial_habits_scale',
    category: 'partner',
    subcategory: 'career_finance_education',
    type: 'scale',
    depth: 'BASIC',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_career_ambition_preference_revised',
    category: 'partner',
    subcategory: 'career_finance_education',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'ambition_focus', icon: <Star /> },
      { value: 'work_life_balance', icon: <Scale /> },
      { value: 'personal_satisfaction', icon: <Heart /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_deal_breakers_open_text_revised',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 30,
    maxLength: 300,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_common_disqualifiers',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_personality_clash',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_red_flag_vs_quirk',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 50,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_in_laws_conflict',
    category: 'partner',
    subcategory: 'family_background',
    type: 'iconChoice',
    depth: 'EXPERT',
    isRequired: false,
    options: [
      { value: 'loyalty_to_couple', icon: <ShieldCheck /> },
      { value: 'mediation_compromise', icon: <Scale /> },
      { value: 'diplomacy', icon: <Users /> },
      { value: 'loyalty_to_family_of_origin', icon: <Home /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_family_connection_importance',
    category: 'partner',
    subcategory: 'family_background',
    type: 'scale',
    depth: 'ADVANCED',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
},

  {
    worldId: 'PARTNER',
    id: 'partner_must_have_quality_final_revised',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 10,
    maxLength: 150,
    metadata: { estimatedTime: 1 },
  },
];
