// src/components/questionnaire/questions/partner/partnerQuestions.tsx
import { Question } from '../../types/types';
import {
  Heart,
  Brain,
  Smile,
  ShieldCheck,
  Star,
  Users,
  Moon,
  Home,
  Target,
  Scale,
  BookOpen,
  Scroll,
  Activity,
  Coffee,
  Eye,
  Car,
  Flag,
  Globe,
  HandHeart,
  Lightbulb,
  Briefcase,
  PiggyBank,
  Info,
  Sparkles,
  Palette,
  Headphones,
  MessageCircle,
  TrendingUp,
  Building2,
  Mountain,
  TreePine,
  MapPin,
  DollarSign,
  HelpCircle,
  Wind,
} from 'lucide-react';

export const partnerQuestions: Question[] = [
  {
    worldId: 'PARTNER',
    id: 'partner_initial_impression_priorities_revised',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'multiSelect',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'appearance_style', icon: <Eye /> },
      { value: 'smile_energy', icon: <Smile /> },
      { value: 'conversation_chemistry', icon: <MessageCircle /> },
      { value: 'wit_depth', icon: <Brain /> },
      { value: 'sense_of_security', icon: <ShieldCheck /> },
    ],
    minSelections: 1,
    maxSelections: 3,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_appearance_importance_scale_revised',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'scale',
    depth: 'BASIC',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_intelligence_types',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'budgetAllocation',
    depth: 'ADVANCED',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'emotional', icon: <Heart /> },
      { value: 'analytical', icon: <Brain /> },
      { value: 'life_smarts', icon: <Sparkles /> },
      { value: 'creative', icon: <Lightbulb /> },
      { value: 'spiritual_torah', icon: <BookOpen /> },
    ],
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_core_character_traits_essential_revised',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'budgetAllocation',
    depth: 'BASIC',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'integrity', icon: <ShieldCheck /> },
      { value: 'warmth', icon: <Heart /> },
      { value: 'optimism', icon: <Smile /> },
      { value: 'maturity', icon: <Target /> },
      { value: 'ambition', icon: <Star /> },
      { value: 'communication', icon: <HandHeart /> },
    ],
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_completion_trait',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 20,
    maxLength: 300,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_emotional_expression_preference',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'singleChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
        { value: 'open_verbal' },
        { value: 'action_oriented' },
        { value: 'balanced' },
        { value: 'not_critical' },
    ],
    metadata: { estimatedTime: 1 },
},

  {
    worldId: 'PARTNER',
    id: 'partner_dating_persona',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'budgetAllocation',
    depth: 'ADVANCED',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'observer_listener', icon: <Headphones /> },
      { value: 'storyteller_initiator', icon: <MessageCircle /> },
      { value: 'humorous_light', icon: <Smile /> },
      { value: 'deep_serious', icon: <Brain /> },
      { value: 'shy_reserved', icon: <Moon /> },
    ],
    metadata: { estimatedTime: 3 },
  },

  {
    worldId: 'PARTNER',
    id: 'partner_lifestyle_pace_preference_revised',
    category: 'partner',
    subcategory: 'lifestyle_social',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'dynamic_active', icon: <Activity /> },
      { value: 'calm_serene', icon: <Home /> },
      { value: 'balanced', icon: <Scale /> },
      { value: 'adventurous_spontaneous', icon: <Sparkles /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_financial_habits_scale',
    category: 'partner',
    subcategory: 'career_finance_education',
    type: 'scale',
    depth: 'BASIC',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_career_ambition_preference_revised',
    category: 'partner',
    subcategory: 'career_finance_education',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'ambition_focus', icon: <Star /> },
      { value: 'work_life_balance', icon: <Scale /> },
      { value: 'personal_satisfaction', icon: <Heart /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_deal_breakers_open_text_revised',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 30,
    maxLength: 300,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_common_disqualifiers',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_personality_clash',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_red_flag_vs_quirk',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 50,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_in_laws_conflict',
    category: 'partner',
    subcategory: 'family_background',
    type: 'iconChoice',
    depth: 'EXPERT',
    isRequired: false,
    options: [
      { value: 'loyalty_to_couple', icon: <ShieldCheck /> },
      { value: 'mediation_compromise', icon: <Scale /> },
      { value: 'diplomacy', icon: <Users /> },
      { value: 'loyalty_to_family_of_origin', icon: <Home /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_family_connection_importance',
    category: 'partner',
    subcategory: 'family_background',
    type: 'scale',
    depth: 'ADVANCED',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
},

  {
    worldId: 'PARTNER',
    id: 'partner_must_have_quality_final_revised',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 10,
    maxLength: 150,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_smoking_preference',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'singleChoice',
    depth: 'BASIC',
    isRequired: true,
    options: [
      { value: 'no_preference', icon: <Wind /> },
      { value: 'slightly_bothers' },
      { value: 'no_smokers' },
      { value: 'deal_breaker' },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_romantic_past_comfort',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'singleChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
        { value: 'no_past' },
        { value: 'short_term_ok' },
        { value: 'long_term_ok' },
        { value: 'past_is_past' },
    ],
    conditions: { maritalStatus: ['SINGLE'] },
    metadata: { estimatedTime: 1 },
},
{
    worldId: 'PARTNER',
    id: 'partner_what_you_bring',
    category: 'partner',
    subcategory: 'self_perception',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 50,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
},

  // ─── שאלות מותנות: פרק ב' ────────────────────────────────────────────────
  {
    worldId: 'PARTNER',
    id: 'partner_second_marriage_preference',
    category: 'partner',
    subcategory: 'non_negotiables',
    type: 'singleChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'prefer_same_background' },
      { value: 'open_to_first_marriage' },
      { value: 'doesnt_matter' },
    ],
    conditions: { maritalStatus: ['DIVORCED', 'WIDOWED'] },
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PARTNER',
    id: 'partner_accepting_stepchildren',
    category: 'partner',
    subcategory: 'family_background',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'fully_open', icon: <Heart /> },
      { value: 'open_with_boundaries', icon: <ShieldCheck /> },
      { value: 'depends_on_ages', icon: <Scale /> },
      { value: 'prefer_no_children', icon: <HelpCircle /> },
    ],
    conditions: { maritalStatus: ['DIVORCED', 'WIDOWED'] },
    metadata: { estimatedTime: 1 },
  },

  // ─── שאלות מותנות: גיל 55+ ───────────────────────────────────────────────
  {
    worldId: 'PARTNER',
    id: 'partner_priorities_senior',
    category: 'partner',
    subcategory: 'first_impression_basics',
    type: 'budgetAllocation',
    depth: 'BASIC',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'health_vitality', icon: <Activity /> },
      { value: 'financial_stability', icon: <PiggyBank /> },
      { value: 'emotional_availability', icon: <Heart /> },
      { value: 'family_integration', icon: <Home /> },
      { value: 'shared_interests', icon: <Coffee /> },
      { value: 'spiritual_alignment', icon: <Globe /> },
    ],
    conditions: { ageRange: [55, 120] },
    metadata: { estimatedTime: 3 },
  },

  // ─── שאלות מותנות: חרדים ────────────────────────────────────────────────
  {
    worldId: 'PARTNER',
    id: 'partner_torah_learning_expectation_charedi',
    category: 'partner',
    subcategory: 'career_finance_education',
    type: 'singleChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'kollel_full_time' },
      { value: 'kollel_partial' },
      { value: 'working_and_learning' },
      { value: 'flexible' },
    ],
    conditions: { religiousLevel: ['charedi', 'charedi_lite'] },
    metadata: { estimatedTime: 1 },
  },

  // ─── שאלות מותנות: נשים דתיות/חרדיות בלבד ───────────────────────────────
  {
    worldId: 'PARTNER',
    id: 'partner_head_covering_women',
    category: 'partner',
    subcategory: 'lifestyle_social',
    type: 'singleChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'full_covering' },
      { value: 'partial_covering' },
      { value: 'not_yet_decided' },
      { value: 'not_planning_to_cover' },
    ],
    conditions: { gender: ['FEMALE'], religiousLevel: ['dati', 'dati_lite', 'charedi', 'charedi_lite'] },
    metadata: { estimatedTime: 1 },
  },
];
