// partnerBasicQuestions.tsx
import { Question } from "../../types/types";
import {
  Heart,
  Home,
  Users,
  Brain,
  Star,
  Sun,
  Target,
  MessageCircle,
  Smile,
  HandHeart,
  Globe,
  Music,
  Book,
  Clock,
  Map,
  Church,
  Brush,
  Coffee,
  Laugh,
} from "lucide-react";

export const partnerBasicQuestions: Question[] = [
  {
    worldId: "PARTNER",
    id: "initial_attraction",
    category: "partner",
    subcategory: "basics",
    question: "מה הכי חשוב לך במבט ראשון אצל בת זוג?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Smile />,
        text: "חום ונעימות",
        value: "warmth",
        description: "אישיות מקבלת ומאירת פנים",
      },
      {
        icon: <Brain />,
        text: "אינטליגנציה",
        value: "intelligence",
        description: "חוכמה וסקרנות אינטלקטואלית",
      },
      {
        icon: <Heart />,
        text: "רגישות",
        value: "sensitivity",
        description: "עדינות ואכפתיות",
      },
      {
        icon: <Laugh />,
        text: "חוש הומור",
        value: "humor",
        description: "קלילות ויכולת לצחוק",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_communication_style",
    category: "partner",
    subcategory: "basics",
    question: "איזה סגנון תקשורת היית רוצה שיהיה לבת הזוג שלך?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <MessageCircle />,
        text: "עמוקה ורגשית",
        value: "deep",
        description: "שיחות משמעותיות על רגשות וחיים",
      },
      {
        icon: <Coffee />,
        text: "קלילה ומשעשעת",
        value: "light",
        description: "תקשורת קלה וזורמת",
      },
      {
        icon: <Target />,
        text: "ישירה ועניינית",
        value: "direct",
        description: "תקשורת ברורה וממוקדת",
      },
      {
        icon: <HandHeart />,
        text: "תומכת ומכילה",
        value: "supportive",
        description: "הקשבה והכלה רגשית",
      },
    ],
  },
  {
    worldId: "PARTNER",
id: "partner_leisure",
    category: "partner",
    subcategory: "basics",
    question: "איך היית רוצה שבת הזוג תבלה את זמנה הפנוי?",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Book />,
        text: "העשרה ולמידה",
        value: "learning",
      },
      {
        icon: <Users />,
        text: "פעילות חברתית",
        value: "social",
      },
      {
        icon: <Brush />,
        text: "יצירה ואומנות",
        value: "creative",
      },
      {
        icon: <Globe />,
        text: "טיולים וחוויות",
        value: "adventures",
      },
    ],
    minSelections: 1,
    maxSelections: 2,
  },
  {
    worldId: "PARTNER",
    id:  "partner_family_approach",
    category: "partner",
    subcategory: "basics",
    question: "איזו גישה למשפחה היית רוצה שתהיה לבת הזוג?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Heart />,
        text: "משפחתית מאוד",
        value: "very_family_oriented",
        description: "מעורבות גבוהה בחיי המשפחה",
      },
      {
        icon: <Home />,
        text: "מאוזנת",
        value: "balanced",
        description: "שילוב בין משפחה לעצמאות",
      },
      {
        icon: <Users />,
        text: "חברתית",
        value: "social",
        description: "דגש על קשרים חברתיים",
      },
      {
        icon: <Target />,
        text: "עצמאית",
        value: "independent",
        description: "שומרת על עצמאות אישית",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_life_goals",
    category: "partner",
    subcategory: "basics",
    question: "אילו שאיפות היית רוצה שיהיו לבת הזוג?",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Star />,
        text: "הגשמה מקצועית",
        value: "career",
      },
      {
        icon: <Home />,
        text: "בניית משפחה",
        value: "family",
      },
      {
        icon: <Book />,
        text: "התפתחות אישית",
        value: "growth",
      },
      {
        icon: <Globe />,
        text: "השפעה חברתית",
        value: "impact",
      },
    ],
    minSelections: 1,
    maxSelections: 2,
  },
  {
    worldId: "PARTNER",
    id: "partner_emotional_expression",
    category: "partner",
    subcategory: "basics",
    question: "איך היית רוצה שבת הזוג תביע רגשות?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Heart />,
        text: "רגשית ופתוחה",
        value: "expressive",
        description: "ביטוי חופשי של רגשות",
      },
      {
        icon: <HandHeart />,
        text: "מאוזנת ויציבה",
        value: "balanced",
        description: "ביטוי רגשי מאוזן",
      },
      {
        icon: <Brain />,
        text: "מחושבת ושקולה",
        value: "thoughtful",
        description: "גישה רציונלית לרגשות",
      },
      {
        icon: <Sun />,
        text: "אופטימית ומעודדת",
        value: "positive",
        description: "דגש על חיוביות",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_lifestyle",
    category: "partner",
    subcategory: "basics",
    question: "איזה סגנון חיים היית רוצה שיהיה לבת הזוג?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Globe />,
        text: "הרפתקני ודינמי",
        value: "adventurous",
        description: "חיים מלאי אקשן והרפתקאות",
      },
      {
        icon: <Home />,
        text: "יציב ומסודר",
        value: "stable",
        description: "חיים מאורגנים ויציבים",
      },
      {
        icon: <Music />,
        text: "יצירתי ואמנותי",
        value: "creative",
        description: "חיים של יצירה והבעה",
      },
      {
        icon: <Book />,
        text: "אינטלקטואלי",
        value: "intellectual",
        description: "חיים של למידה והעשרה",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_social_style",
    category: "partner",
    subcategory: "basics",
    question: "איזה סגנון חברתי היית רוצה שיהיה לבת הזוג?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Users />,
        text: "חברותית מאוד",
        value: "very_social",
        description: "אוהבת להיות מוקפת באנשים",
      },
      {
        icon: <Home />,
        text: "מאוזנת חברתית",
        value: "balanced",
        description: "משלבת זמן חברתי ואישי",
      },
      {
        icon: <Heart />,
        text: "סלקטיבית",
        value: "selective",
        description: "מעדיפה חברויות קרובות ועמוקות",
      },
      {
        icon: <Book />,
        text: "שקטה ועצמאית",
        value: "independent",
        description: "מעדיפה זמן אישי",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_values",
    category: "partner",
    subcategory: "basics",
    question: "אילו ערכים הכי חשוב לך שיהיו לבת הזוג?",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Heart />,
        text: "אמפתיה וחמלה",
        value: "empathy",
      },
      {
        icon: <Target />,
        text: "יושרה ואמינות",
        value: "integrity",
      },
      {
        icon: <Star />,
        text: "שאפתנות",
        value: "ambition",
      },
      {
        icon: <HandHeart />,
        text: "נתינה ועזרה",
        value: "giving",
      },
    ],
    minSelections: 1,
    maxSelections: 2,
  },
  {
    worldId: "PARTNER",
    id: "partner_career_attitude",
    category: "partner",
    subcategory: "basics",
    question: "איזו גישה לקריירה היית רוצה שתהיה לבת הזוג?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Star />,
        text: "שאפתנית מאוד",
        value: "ambitious",
        description: "מוכוונת הצלחה והישגים",
      },
      {
        icon: <Target />,
        text: "מאוזנת",
        value: "balanced",
        description: "משלבת קריירה וחיים אישיים",
      },
      {
        icon: <Heart />,
        text: "מוכוונת משמעות",
        value: "meaningful",
        description: "מחפשת סיפוק והשפעה",
      },
      {
        icon: <Home />,
        text: "גמישה",
        value: "flexible",
        description: "מתאימה את העבודה לחיים",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_decision_making",
    category: "partner",
    subcategory: "basics",
    question: "איך היית רוצה שבת הזוג תקבל החלטות?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Brain />,
        text: "רציונלית",
        value: "rational",
        description: "מבוססת על ניתוח והיגיון",
      },
      {
        icon: <Heart />,
        text: "אינטואיטיבית",
        value: "intuitive",
        description: "מקשיבה לתחושות הבטן",
      },
      {
        icon: <Users />,
        text: "משתפת",
        value: "collaborative",
        description: "מתייעצת עם אחרים",
      },
      {
        icon: <Target />,
        text: "מאוזנת",
        value: "balanced",
        description: "משלבת רגש והיגיון",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_conflict_resolution",
    category: "partner",
    subcategory: "basics",
    question: "איך היית רוצה שבת הזוג תתמודד עם קונפליקטים?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <MessageCircle />,
        text: "דיון פתוח",
        value: "open_discussion",
        description: "מעדיפה לדבר על הכל",
      },
      {
        icon: <HandHeart />,
        text: "פשרה והבנה",
        value: "compromise",
        description: "מחפשת פתרון מאוזן",
      },
      {
        icon: <Clock />,
        text: "זמן לעיבוד",
        value: "processing",
        description: "לוקחת זמן לחשיבה",
      },
      {
        icon: <Target />,
        text: "פתרון מעשי",
        value: "practical",
        description: "מחפשת פתרונות מעשיים",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_religious_approach",
    category: "partner",
    subcategory: "basics",
    question: "איזו גישה לדת ומסורת היית רוצה שתהיה לבת הזוג?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Church />,
        text: "מסורתית מאוד",
        value: "very_religious",
        description: "שומרת על מסורת וערכי דת",
      },
      {
        icon: <Star />,
        text: "מסורתית גמישה",
        value: "flexible_traditional",
        description: "משלבת מסורת עם מודרניות",
      },
      {
        icon: <Heart />,
        text: "חיבור רוחני",
        value: "spiritual",
        description: "מחוברת לערכים רוחניים",
      },
      {
        icon: <Sun />,
        text: "חילונית",
        value: "secular",
        description: "מנהלת אורח חיים חילוני",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_personal_growth",
    category: "partner",
    subcategory: "basics",
    question: "איזו גישה להתפתחות אישית היית רוצה שתהיה לבת הזוג?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Book />,
        text: "לומדת תמיד",
        value: "constant_learner",
        description: "משקיעה בלמידה והתפתחות",
      },
      {
        icon: <Target />,
        text: "מכוונת מטרות",
        value: "goal_oriented",
        description: "מציבה ומשיגה יעדים",
      },
      {
        icon: <Heart />,
        text: "צמיחה רגשית",
        value: "emotional_growth",
        description: "מתפתחת מבחינה רגשית",
      },
      {
        icon: <Globe />,
        text: "פתוחה לחוויות",
        value: "open_minded",
        description: "פתוחה להתנסויות חדשות",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_support_style",
    category: "partner",
    subcategory: "basics",
    question: "איך היית רוצה שבת הזוג תתמוך בך?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <HandHeart />,
        text: "תמיכה רגשית",
        value: "emotional_support",
        description: "מקשיבה ומכילה רגשית",
      },
      {
        icon: <Target />,
        text: "תמיכה מעשית",
        value: "practical_support",
        description: "עוזרת במציאת פתרונות",
      },
      {
        icon: <Star />,
        text: "מעודדת צמיחה",
        value: "growth_support",
        description: "דוחפת להתפתח ולהתקדם",
      },
      {
        icon: <Sun />,
        text: "נוכחות תומכת",
        value: "presence",
        description: "פשוט נמצאת שם בשבילי",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_intimacy_approach",
    category: "partner",
    subcategory: "basics",
    question: "איזו גישה לקרבה ואינטימיות היית רוצה שתהיה לבת הזוג?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Heart />,
        text: "רומנטית",
        value: "romantic",
        description: "מחפשת רומנטיקה ואינטימיות",
      },
      {
        icon: <MessageCircle />,
        text: "רגשית",
        value: "emotional",
        description: "מעדיפה חיבור רגשי עמוק",
      },
      {
        icon: <HandHeart />,
        text: "פיזית",
        value: "physical",
        description: "מעריכה מגע וקרבה פיזית",
      },
      {
        icon: <Target />,
        text: "מאוזנת",
        value: "balanced",
        description: "משלבת בין כל סוגי הקרבה",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_future_vision",
    category: "partner",
    subcategory: "basics",
    question: "איך היית רוצה שבת הזוג תראה את העתיד המשותף?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Map />,
        text: "מתכננת",
        value: "planner",
        description: "אוהבת לתכנן את העתיד",
      },
      {
        icon: <Globe />,
        text: "הרפתקנית",
        value: "adventurous",
        description: "פתוחה להזדמנויות חדשות",
      },
      {
        icon: <Home />,
        text: "יציבה",
        value: "stable",
        description: "מחפשת יציבות וביטחון",
      },
      {
        icon: <Star />,
        text: "שאפתנית",
        value: "ambitious",
        description: "מציבה יעדים גבוהים",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_interests",
    category: "partner",
    subcategory: "basics",
    question: "אילו תחומי עניין היית רוצה שיהיו לבת הזוג?",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Book />,
        text: "אינטלקטואליים",
        value: "intellectual",
      },
      {
        icon: <Music />,
        text: "אומנות ותרבות",
        value: "arts",
      },
      {
        icon: <Globe />,
        text: "טיולים וטבע",
        value: "nature",
      },
      {
        icon: <Users />,
        text: "חברה וקהילה",
        value: "community",
      },
    ],
    minSelections: 1,
    maxSelections: 2,
  },
  {
    worldId: "PARTNER",
    id: "partner_independence",
    category: "partner",
    subcategory: "basics",
    question: "איזו רמת עצמאות היית רוצה שתהיה לבת הזוג?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Star />,
        text: "עצמאית מאוד",
        value: "very_independent",
        description: "אוהבת לעשות דברים לבד",
      },
      {
        icon: <Users />,
        text: "משלבת",
        value: "balanced",
        description: "משלבת עצמאות ושותפות",
      },
      {
        icon: <Heart />,
        text: "מחוברת",
        value: "connected",
        description: "מעדיפה לעשות דברים יחד",
      },
      {
        icon: <Target />,
        text: "גמישה",
        value: "flexible",
        description: "מתאימה את עצמה למצב",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_emotions_handling",
    category: "partner",
    subcategory: "basics",
    question: "איך היית רוצה שבת הזוג תתמודד עם רגשות?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <MessageCircle />,
        text: "משתפת",
        value: "expressive",
        description: "מדברת על רגשות בפתיחות",
      },
      {
        icon: <Brain />,
        text: "מעבדת",
        value: "processing",
        description: "מעבדת רגשות בפנים",
      },
      {
        icon: <HandHeart />,
        text: "מאוזנת",
        value: "balanced",
        description: "משלבת שיתוף ועיבוד",
      },
      {
        icon: <Target />,
        text: "פרקטית",
        value: "practical",
        description: "מתמקדת בפתרונות",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_home_management",
    category: "partner",
    subcategory: "basics",
    question: "איזו גישה לניהול הבית היית רוצה שתהיה לבת הזוג?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Home />,
        text: "מאורגנת",
        value: "organized",
        description: "אוהבת סדר וארגון",
      },
      {
        icon: <Heart />,
        text: "יוצרת אווירה",
        value: "atmosphere",
        description: "מתמקדת באווירה נעימה",
      },
      {
        icon: <Users />,
        text: "משתפת פעולה",
        value: "collaborative",
        description: "עובדת בשיתוף פעולה",
      },
      {
        icon: <Sun />,
        text: "גמישה",
        value: "flexible",
        description: "מסתגלת למצבים משתנים",
      },
    ],
  },
  {
    worldId: "PARTNER",
    id: "partner_stress_handling",
    category: "partner",
    subcategory: "basics",
    question: "איך היית רוצה שבת הזוג תתמודד עם מצבי לחץ?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Target />,
        text: "פותרת בעיות",
        value: "problem_solver",
        description: "מתמקדת במציאת פתרונות",
      },
      {
        icon: <Heart />,
        text: "מבקשת תמיכה",
        value: "support_seeker",
        description: "משתפת ומבקשת עזרה",
      },
      {
        icon: <Sun />,
        text: "אופטימית",
        value: "optimistic",
        description: "שומרת על גישה חיובית",
      },
      {
        icon: <Brain />,
        text: "מתכננת",
        value: "planner",
        description: "מתכננת ומתארגנת מראש",
      },
    ],
  },
];

export default partnerBasicQuestions;
