// partnerDepthQuestions.tsx
import { Question } from "../../types/types";

export const partnerDepthQuestions: Question[] = [
  {
    worldId: "PARTNER",
    id: "emotional_support_style",
    category: "partner",
    subcategory: "depth",
    question:
      "איך היית רוצה שבת הזוג תתמוך בך ברגעים מאתגרים? תאר סיטואציה ספציפית ואיך היית רוצה שהיא תגיב",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף על סוג התמיכה שאתה מחפש ואיך היית רוצה לחוות אותה...",
  },
  {
    worldId: "PARTNER",
    id: "values_expression",
    category: "partner",
    subcategory: "depth",
    question:
      "אילו ערכים חשובים לך שבת הזוג תייצג בחייה? תן דוגמאות ספציפיות לאיך היית רוצה לראות ערכים אלו באים לידי ביטוי ביומיום",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder:
      "תאר את הערכים החשובים לך ואיך היית רוצה לראות אותם מתבטאים...",
  },
  {
    worldId: "PARTNER",
    id: "intellectual_connection",
    category: "partner",
    subcategory: "depth",
    question:
      "איזה סוג של חיבור אינטלקטואלי היית רוצה שיהיה ביניכם? על מה היית רוצה שתוכלו לדבר ולחשוב יחד?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף על החיבור האינטלקטואלי שאתה מחפש...",
  },
  {
    worldId: "PARTNER",
    id: "future_challenges",
    category: "partner",
    subcategory: "depth",
    question:
      "איך היית רוצה שתתמודדו יחד עם אתגרים עתידיים? איזה סוג של שותפות היית רוצה ליצור בהתמודדות עם קשיים?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר את סוג השותפות שהיית רוצה באתגרים...",
  },
  {
    worldId: "PARTNER",
    id: "emotional_growth",
    category: "partner",
    subcategory: "depth",
    question:
      "איך היית רוצה לראות את בת הזוג מתפתחת מבחינה רגשית? איך הייתם יכולים לצמוח רגשית יחד?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף על הצמיחה הרגשית שהיית רוצה לראות...",
  },
  {
    worldId: "PARTNER",
    id: "life_goals_support",
    category: "partner",
    subcategory: "depth",
    question:
      "איך היית רוצה שבת הזוג תתמוך במטרות החיים שלך? איזה תפקיד היית רוצה שהיא תיקח בהגשמת החלומות שלך?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר את התמיכה שהיית רוצה במטרות החיים שלך...",
  },
  {
    worldId: "PARTNER",
    id: "shared_spirituality",
    category: "partner",
    subcategory: "depth",
    question:
      "איזה חיבור רוחני היית רוצה שיהיה ביניכם? איך היית רוצה לחוות יחד את הצד הרוחני של החיים?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף על החיבור הרוחני שהיית רוצה בזוגיות...",
  },
  {
    worldId: "PARTNER",
    id: "conflict_resolution",
    category: "partner",
    subcategory: "depth",
    question:
      "כשיש חילוקי דעות, איך היית רוצה שבת הזוג תנהל את השיחה? תאר את הדרך האידיאלית בעיניך לפתרון קונפליקטים",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר את הדרך הרצויה בעיניך לפתרון מחלוקות...",
  },
  {
    worldId: "PARTNER",
    id: "quality_time",
    category: "partner",
    subcategory: "depth",
    question:
      "איך נראה בעיניך זמן איכות משמעותי עם בת זוג? אילו חוויות משותפות היית רוצה ליצור יחד?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר את סוג הזמן המשותף שהיית רוצה...",
  },
  {
    worldId: "PARTNER",
    id: "personal_growth_support",
    category: "partner",
    subcategory: "depth",
    question:
      "איך היית רוצה שבת הזוג תתמוך בצמיחה האישית שלך? איזה מרחב היית רוצה לקבל להתפתחות עצמית בתוך הזוגיות?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף על התמיכה שהיית רוצה בצמיחה האישית שלך...",
  },
  {
    worldId: "PARTNER",
    id: "shared_dreams",
    category: "partner",
    subcategory: "depth",
    question:
      "אילו חלומות משותפים היית רוצה להגשים יחד? איך היית רוצה שתעבדו יחד להגשמת החלומות האלה?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר את החלומות המשותפים שהיית רוצה להגשים...",
  },
  {
    worldId: "PARTNER",
    id: "emotional_intimacy",
    category: "partner",
    subcategory: "depth",
    question:
      "מה יוצר אצלך תחושה של קרבה רגשית אמיתית? איך היית רוצה לבנות ולטפח אינטימיות רגשית עם בת הזוג?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף על הקרבה הרגשית שאתה מחפש...",
  },
  {
    worldId: "PARTNER",
    id: "daily_partnership",
    category: "partner",
    subcategory: "depth",
    question:
      "איך היית רוצה שהשותפות היומיומית ביניכם תיראה? אילו ערכים היית רוצה שינחו את החיים המשותפים שלכם?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר את השותפות היומיומית שהיית רוצה...",
  },
  {
    worldId: "PARTNER",
    id: "trust_building",
    category: "partner",
    subcategory: "depth",
    question:
      "מה בונה אצלך אמון בקשר? אילו התנהגויות או מאפיינים של בת הזוג יגרמו לך להרגיש שאתה יכול לתת בה אמון מלא?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף על מה שבונה אצלך אמון בקשר...",
  },
  {
    worldId: "PARTNER",
    id: "family_relationships",
    category: "partner",
    subcategory: "depth",
    question:
      "איך היית רוצה שבת הזוג תתייחס למשפחה שלך? איזה סוג של קשר היית רוצה שייבנה בינה לבין המשפחה המורחבת?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר את היחסים המשפחתיים שהיית רוצה לראות...",
  },
  {
    worldId: "PARTNER",
    id: "life_balance",
    category: "partner",
    subcategory: "depth",
    question:
      "איזה איזון היית רוצה למצוא בין הזוגיות לשאר תחומי החיים? איך היית רוצה שבת הזוג תתמוך באיזון הזה?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף על האיזון שאתה מחפש בין תחומי החיים...",
  },
  {
    worldId: "PARTNER",
    id: "mutual_growth",
    category: "partner",
    subcategory: "depth",
    question:
      "איך היית רוצה לראות את עצמכם צומחים וצומחים יחד לאורך השנים? איזה סוג של התפתחות משותפת היית רוצה ליצור?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר את הצמיחה המשותפת שהיית רוצה לחוות...",
  },
  {
    worldId: "PARTNER",
    id: "partner_independence",
    category: "partner",
    subcategory: "depth",
    question:
      "איזה מרחב אישי היית רוצה שיהיה לכל אחד מכם בתוך הזוגיות? איך לדעתך צריך לאזן בין עצמאות לקרבה?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף על האיזון שאתה מחפש בין עצמאות וקרבה...",
  },
  {
    worldId: "PARTNER",
    id: "relationship_success",
    category: "partner",
    subcategory: "depth",
    question:
      "מה נחשב בעיניך לזוגיות מוצלחת? אילו מרכיבים הכרחיים בעיניך לקשר ארוך טווח ומספק?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר את תפיסתך לגבי זוגיות מוצלחת...",
  },
  {
    worldId: "PARTNER",
    id: "life_philosophy",
    category: "partner",
    subcategory: "depth",
    question:
      "איזו השקפת עולם היית רוצה לחלוק עם בת הזוג? אילו ערכים ואמונות בסיסיות חשוב לך שיהיו משותפים?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף על השקפת העולם המשותפת שאתה מחפש...",
  },
];

export default partnerDepthQuestions;
