// src/components/questionnaire/questions/religion/faithQuestions.tsx - (גרסה מתוקנת)
import { Question } from '../../types/types';

export const faithQuestions: Question[] = [
  // Spiritual and Religious Values
  {
    worldId: 'RELIGION',
    id: 'spiritualMoment',
    category: 'values',
    subcategory: 'spiritual',
    question: 'מהו הרגע הכי רוחני שחווית בחייך?',
    type: 'openText',
    depth: 'BASIC',
    isRequired: false,
    placeholder: 'ספר/י על חוויה משמעותית...',
    minLength: 20,
    maxLength: 500,
  },
  {
    worldId: 'RELIGION',
    id: 'favoriteHoliday',
    category: 'values',
    subcategory: 'spiritual',
    question: 'איזה חג יהודי הכי משמעותי עבורך?',
    type: 'singleChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'ראש השנה', text: 'ראש השנה' },
      { value: 'יום כיפור', text: 'יום כיפור' },
      { value: 'פסח', text: 'פסח' },
      { value: 'שבועות', text: 'שבועות' },
    ],
  },

  // Personal Values
  {
    worldId: 'RELIGION',
    id: 'coreValues',
    category: 'values',
    subcategory: 'personal',
    question: 'מהם שלושת הערכים החשובים ביותר בחייך?',
    type: 'multiSelect',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'יושר ואמת', text: 'יושר ואמת' },
      { value: 'משפחה', text: 'משפחה' },
      { value: 'לימוד והתפתחות', text: 'לימוד והתפתחות' },
      { value: 'חסד', text: 'חסד' },
      { value: 'מסורת', text: 'מסורת' },
      { value: 'הצלחה', text: 'הצלחה' },
    ],
    minSelections: 1,
    maxSelections: 3,
  },
  {
    worldId: 'RELIGION',
    id: 'lifeGoals',
    category: 'values',
    subcategory: 'personal',
    question: 'מהי המטרה העיקרית שלך בחיים?',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    placeholder: 'שתף/י במטרות החיים שלך...',
    minLength: 30,
    maxLength: 500,
  },

  // Community Values
  {
    worldId: 'RELIGION',
    id: 'communityRole',
    category: 'values',
    subcategory: 'community',
    question: 'איזה תפקיד אתה רואה לעצמך בקהילה?',
    type: 'multiSelect',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'מנהיג/מוביל', text: 'מנהיג/מוביל' },
      { value: 'תומך ומסייע', text: 'תומך ומסייע' },
      { value: 'מחנך/מלמד', text: 'מחנך/מלמד' },
      { value: 'משתתף פעיל', text: 'משתתף פעיל' },
    ],
    minSelections: 1,
    maxSelections: 2,
  },
  {
    worldId: 'RELIGION',
    id: 'givingPhilosophy',
    category: 'values',
    subcategory: 'community',
    question: 'מהי תפיסת עולמך בנושא נתינה וצדקה?',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    placeholder: 'תאר/י את גישתך לנתינה...',
    minLength: 30,
    maxLength: 500,
  },

  // Future Values
  {
    worldId: 'RELIGION',
    id: 'nextGeneration',
    category: 'values',
    subcategory: 'future',
    question: 'מה הערכים החשובים ביותר שתרצה להעביר לדור הבא?',
    type: 'multiSelect',
    depth: 'EXPERT',
    isRequired: false,
    options: [
      { value: 'תורה ומסורת', text: 'תורה ומסורת' },
      { value: 'מוסר וערכים', text: 'מוסר וערכים' },
      { value: 'חינוך והשכלה', text: 'חינוך והשכלה' },
      { value: 'עצמאות', text: 'עצמאות' },
      { value: 'קהילתיות', text: 'קהילתיות' },
    ],
    minSelections: 1,
    maxSelections: 3,
  },
  {
    worldId: 'RELIGION',
    id: 'israelVision',
    category: 'values',
    subcategory: 'future',
    question: 'מהו החזון שלך למדינת ישראל?',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    placeholder: 'שתף/י את חזונך...',
    minLength: 50,
    maxLength: 1000,
  },
];
