// src/components/questionnaire/questions/religion/practicalReligionQuestions.tsx - (גרסה מתוקנת)
import { Question } from "../../types/types";

export const practicalQuestions: Question[] = [
  // Basic Principles
  {worldId: "RELIGION",
    id: "religiousWorldview",
    category: "religiousLifestyle",
    subcategory: "basicPrinciples",
    question: "מהי השקפת עולמך הדתית?",
    type: "openText",
    depth: "BASIC",
    isRequired: false,
    placeholder: "תאר/י את תפיסת עולמך הדתית...",
    minLength: 20,
    maxLength: 500,
  },
  {worldId: "RELIGION",
    id: "religiousIdentity",
    category: "religiousLifestyle",
    subcategory: "basicPrinciples",
    question: "איך אתה מגדיר את זהותך הדתית?",
    type: "singleChoice",
    depth: "BASIC",
    isRequired: false,
    options: [
      { value: "חרדי", text: "חרדי" },
      { value: "דתי לאומי", text: "דתי לאומי" },
      { value: "מסורתי", text: "מסורתי" },
      { value: "אחר", text: "אחר" },
    ],
  },
  {worldId: "RELIGION",
    id: "halachaImportance",
    category: "religiousLifestyle",
    subcategory: "basicPrinciples",
    question: "מה מקומה של ההלכה בחיי היומיום שלך?",
    type: "openText",
    depth: "BASIC",
    isRequired: false,
    placeholder: "תאר/י את מקום ההלכה בחייך...",
    minLength: 20,
    maxLength: 500,
  },

  // Prayer and Learning
  {worldId: "RELIGION",
    id: "minyanImportance",
    category: "religiousLifestyle",
    subcategory: "prayerAndLearning",
    question: "מהי חשיבות התפילה במניין בחייך?",
    type: "singleChoice",
    depth: "BASIC",
    isRequired: false,
    options: [
      { value: "חשוב מאוד - משתדל להתפלל כל תפילה במניין", text: "חשוב מאוד - משתדל להתפלל כל תפילה במניין" },
      { value: "חשוב - משתדל לפחות פעם ביום", text: "חשוב - משתדל לפחות פעם ביום" },
      { value: "לעיתים - בעיקר בשבתות וחגים", text: "לעיתים - בעיקר בשבתות וחגים" },
      { value: "פחות חשוב לי", text: "פחות חשוב לי" },
    ],
  },
  {worldId: "RELIGION",
    id: "dailyLearning",
    category: "religiousLifestyle",
    subcategory: "prayerAndLearning",
    question: "איך נראה סדר הלימוד היומי שלך?",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: false,
    options: [
      { value: "דף יומי", text: "דף יומי" },
      { value: "הלכה יומית", text: "הלכה יומית" },
      { value: "פרשת שבוע", text: "פרשת שבוע" },
      { value: "חסידות", text: "חסידות" },
      { value: "מוסר", text: "מוסר" },
      { value: "אחר", text: "אחר" },
    ],
    minSelections: 1,
    maxSelections: 4,
  },
  
  // Shabbat and Holidays
  {worldId: "RELIGION",
    id: "idealShabbat",
    category: "religiousLifestyle",
    subcategory: "shabbatAndHolidays",
    question: "איך נראית השבת האידיאלית בעיניך?",
    type: "openText",
    depth: "BASIC",
    isRequired: false,
    placeholder: "תאר/י את השבת המושלמת עבורך...",
    minLength: 20,
    maxLength: 500,
  },
  {worldId: "RELIGION",
    id: "shabbatRestrictions",
    category: "religiousLifestyle",
    subcategory: "shabbatAndHolidays",
    question: "מה יחסך לחומרות בהלכות שבת?",
    type: "multiSelect",
    depth: "ADVANCED",
    isRequired: false,
    options: [
      { value: "מחמיר בהלכות שבת", text: "מחמיר בהלכות שבת" },
      { value: "שומר על ההלכות הבסיסיות", text: "שומר על ההלכות הבסיסיות" },
      { value: "גמיש יותר בפרשנות", text: "גמיש יותר בפרשנות" },
      { value: "תלוי במצב ובנסיבות", text: "תלוי במצב ובנסיבות" },
    ],
    minSelections: 1,
    maxSelections: 2,
  },

  // Kashrut and Halacha
  {worldId: "RELIGION",
    id: "kashrutLevel",
    category: "religiousLifestyle",
    subcategory: "kashrutAndHalacha",
    question: "מה רמת ההקפדה שלך בכשרות?",
    type: "singleChoice",
    depth: "BASIC",
    isRequired: false,
    options: [
      { value: "מהדרין בלבד", text: "מהדרין בלבד" },
      { value: "כשרות רגילה", text: "כשרות רגילה" },
      { value: "כשרות בסיסית", text: "כשרות בסיסית" },
      { value: "גמיש יותר", text: "גמיש יותר" },
    ],
  },
  {worldId: "RELIGION",
    id: "eatingOut",
    category: "religiousLifestyle",
    subcategory: "kashrutAndHalacha",
    question: "איך אתה מתייחס לאכילה מחוץ לבית?",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: false,
    options: [
      { value: "רק במסעדות כשרות", text: "רק במסעדות כשרות" },
      { value: "אוכל בבתים של משפחה", text: "אוכל בבתים של משפחה" },
      { value: "אוכל אצל חברים", text: "אוכל אצל חברים" },
      { value: "גמיש בהתאם לנסיבות", text: "גמיש בהתאם לנסיבות" },
    ],
    minSelections: 1,
    maxSelections: 3,
  },

  // Modesty and Public Space
  {worldId: "RELIGION",
    id: "modestyView",
    category: "religiousLifestyle",
    subcategory: "modestyAndPublic",
    question: "מהי השקפתך בענייני צניעות?",
    type: "openText",
    depth: "BASIC",
    isRequired: false,
    placeholder: "תאר/י את תפיסתך בנושא צניעות...",
    minLength: 20,
    maxLength: 500,
  },
  {worldId: "RELIGION",
    id: "genderSeparation",
    category: "religiousLifestyle",
    subcategory: "modestyAndPublic",
    question: "איך אתה מתייחס להפרדה בין גברים לנשים?",
    type: "singleChoice",
    depth: "ADVANCED",
    isRequired: false,
    options: [
      { value: "תומך בהפרדה מלאה", text: "תומך בהפרדה מלאה" },
      { value: "תלוי בנסיבות ובמקום", text: "תלוי בנסיבות ובמקום" },
      { value: "גמיש יותר בנושא", text: "גמיש יותר בנושא" },
      { value: "מתנגד להפרדה", text: "מתנגד להפרדה" },
    ],
  },
];