// src/components/questionnaire/questions/religion/religionQuestions.tsx
import { Question } from '../../types/types';
import {
  Scroll,
  BookOpen,
  Users,
  Home,
  Target,
  Scale,
  Heart,
  Sparkles,
  ShieldCheck,
  Flag,
  X,
  HandHeart,
  Lightbulb,
  Info,
  PocketKnife,
  Bed,
  Smile,
  Brain,
} from 'lucide-react';

export const religionQuestions: Question[] = [
  {
    worldId: 'RELIGION',
    id: 'religion_core_feeling_of_faith',
    category: 'religion',
    subcategory: 'identity_belief',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'security_stability', icon: <ShieldCheck /> },
      { value: 'meaning_belonging', icon: <Target /> },
      { value: 'joy_gratitude', icon: <Sparkles /> },
      { value: 'challenge_growth', icon: <Brain /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_my_personal_prayer',
    category: 'religion',
    subcategory: 'personal_reflection',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 30,
    maxLength: 300,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_rabbinic_guidance_role_revised',
    category: 'religion',
    subcategory: 'identity_belief',
    type: 'scale',
    depth: 'BASIC',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_shabbat_experience',
    category: 'religion',
    subcategory: 'practical_observance',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'family_time', icon: <Home /> },
      { value: 'spiritual_ascension', icon: <BookOpen /> },
      { value: 'rest_recharge', icon: <Bed /> },
      { value: 'community_social', icon: <Users /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_daily_spiritual_connection',
    category: 'religion',
    subcategory: 'practical_observance',
    type: 'multiSelect',
    depth: 'ADVANCED',
    isRequired: false,
    minSelections: 1,
    maxSelections: 3,
    options: [
      { value: 'torah_study' },
      { value: 'personal_prayer' },
      { value: 'nature_gratitude' },
      { value: 'acts_of_kindness' },
      { value: 'song_music' },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_kashrut_observance_details_revised',
    category: 'religion',
    subcategory: 'practical_observance',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_modesty_personal_approach_revised',
    category: 'religion',
    subcategory: 'practical_observance',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_secular_culture_scenario',
    category: 'religion',
    subcategory: 'community_influence',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'avoid', icon: <X /> },
      { value: 'filter_check', icon: <Info /> },
      { value: 'social_inclusion', icon: <Users /> },
      { value: 'suggest_alternative', icon: <Smile /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_general_culture_consumption',
    category: 'religion',
    subcategory: 'community_influence',
    type: 'scale',
    depth: 'ADVANCED',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_community_role',
    category: 'religion',
    subcategory: 'community_influence',
    type: 'singleChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'central' },
      { value: 'important' },
      { value: 'secondary' },
      { value: 'not_seeking' },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_partner_torah_learning_expectation',
    category: 'religion',
    subcategory: 'relationship_family',
    type: 'singleChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'dedicated_daily' },
      { value: 'regularly_flexible' },
      { value: 'when_possible' },
      { value: 'not_a_focus' },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_army_service_attitude',
    category: 'religion',
    subcategory: 'community_influence',
    type: 'singleChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'essential_for_men' },
      { value: 'meaningful_service' },
      { value: 'torah_is_protection' },
      { value: 'flexible_personal_choice' },
    ],
    conditions: { religiousLevel: ['dati', 'dati_lite', 'masorti', 'hiloni'] },
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_zionism_importance',
    category: 'religion',
    subcategory: 'community_influence',
    type: 'scale',
    depth: 'ADVANCED',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_intergroup_friendships',
    category: 'religion',
    subcategory: 'community_influence',
    type: 'singleChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'large_part' },
      { value: 'some_friends' },
      { value: 'mostly_homogeneous' },
    ],
    metadata: { estimatedTime: 1 },
  },

  {
    worldId: 'RELIGION',
    id: 'religion_doubts_and_struggles',
    category: 'religion',
    subcategory: 'identity_belief',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_partner_ideal_religious_profile_revised',
    category: 'religion',
    subcategory: 'relationship_family',
    type: 'openText',
    depth: 'BASIC',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_flexibility_religious_differences_partner_revised',
    category: 'religion',
    subcategory: 'relationship_family',
    type: 'scale',
    depth: 'ADVANCED',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_gender_roles_philosophy',
    category: 'religion',
    subcategory: 'relationship_family',
    type: 'budgetAllocation',
    depth: 'EXPERT',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'traditional', icon: <Scroll /> },
      { value: 'egalitarian', icon: <Scale /> },
      { value: 'flexible', icon: <Sparkles /> },
    ],
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_children_education_religious_vision_revised',
    category: 'religion',
    subcategory: 'relationship_family',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 50,
    maxLength: 500,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'RELIGION',
    id: 'religion_other_denominations_attitude',
    category: 'religion',
    subcategory: 'community_influence',
    type: 'singleChoice',
    depth: 'EXPERT',
    isRequired: false,
    options: [
      { value: 'decline' },
      { value: 'conditional_participation' },
      { value: 'accept_openly' },
      { value: 'depends_on_context' },
    ],
    metadata: { estimatedTime: 1 },
  },

  // ─── שאלות מותנות: חרדים ────────────────────────────────────────────────
  {
    worldId: 'RELIGION',
    id: 'religion_kollel_financial_model',
    category: 'religion',
    subcategory: 'relationship_family',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'wife_supports_full_kollel', icon: <BookOpen /> },
      { value: 'partial_support_partial_work', icon: <Scale /> },
      { value: 'work_and_learn', icon: <Brain /> },
      { value: 'flexible_by_stage', icon: <Sparkles /> },
    ],
    conditions: { religiousLevel: ['charedi', 'charedi_lite'] },
    metadata: { estimatedTime: 1 },
  },

  // ─── שאלות מותנות: דתיים / חרדים ─────────────────────────────────────────
  {
    worldId: 'RELIGION',
    id: 'religion_shomer_negiah_approach',
    category: 'religion',
    subcategory: 'practical_observance',
    type: 'singleChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'strictly_shomer' },
      { value: 'personal_decision' },
      { value: 'not_my_practice' },
      { value: 'prefer_not_to_answer' },
    ],
    conditions: { religiousLevel: ['dati', 'dati_lite', 'charedi', 'charedi_lite'] },
    metadata: { estimatedTime: 1 },
  },

  // ─── שאלות מותנות: חילונים / מסורתיים ────────────────────────────────────
  {
    worldId: 'RELIGION',
    id: 'religion_jewish_identity_secular',
    category: 'religion',
    subcategory: 'identity_belief',
    type: 'budgetAllocation',
    depth: 'BASIC',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'cultural_heritage', icon: <Flag /> },
      { value: 'ethical_values', icon: <Scale /> },
      { value: 'holiday_tradition', icon: <Home /> },
      { value: 'community_belonging', icon: <Users /> },
      { value: 'personal_spiritual', icon: <Sparkles /> },
      { value: 'minimal_connection', icon: <Smile /> },
    ],
    conditions: { religiousLevel: ['hiloni', 'masorti'] },
    metadata: { estimatedTime: 3 },
  },

  // ─── שאלות מותנות: פרק ב' ────────────────────────────────────────────────
  {
    worldId: 'RELIGION',
    id: 'religion_faith_after_hardship',
    category: 'religion',
    subcategory: 'identity_belief',
    type: 'singleChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'strengthened_faith' },
      { value: 'unchanged' },
      { value: 'created_questions' },
      { value: 'weakened_connection' },
    ],
    conditions: { maritalStatus: ['DIVORCED', 'WIDOWED'] },
    metadata: { estimatedTime: 1 },
  },
];
