"use client";
import React from "react";
import type { ReactNode } from "react";
import {
  BookOpen,
  Scroll,
  Star,
  Heart,
  Book,
  Hand,
  HandHeart,
  Gem,
  Users,
  Home,
  Globe,
  Target,
  Brain,
  HeartHandshake,
  Flower,
  Mountain,
  Flame,
  User,
  Trees,
  Building2,
  Scale,
  Infinity,
} from "lucide-react";
import type { Question } from "../types/types";

const valueQuestions: Question[] = [
  {
    id: "spiritualMoment",
    category: "values",
    subcategory: "opening",
    question: "מהו הרגע הכי רוחני שחווית בחייך?",
    type: "openText",
    depth: "BASIC",
    isRequired: true,
    placeholder: "ספר/י על חוויה משמעותית...",
    minLength: 50,
    maxLength: 500,
  },
  {
    id: "favoriteHoliday",
    category: "values",
    subcategory: "opening",
    question: "איזה חג יהודי הכי משמעותי עבורך?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Flame size={24} />,
        text: "חנוכה",
        value: "hanukkah",
        description: "חג האור והניסים",
      },
      {
        icon: <Scroll size={24} />,
        text: "פסח",
        value: "pesach",
        description: "חג החירות",
      },
      {
        icon: <Star size={24} />,
        text: "ראש השנה",
        value: "roshHashana",
        description: "יום הדין והתחדשות",
      },
      {
        icon: <Mountain size={24} />,
        text: "שבועות",
        value: "shavuot",
        description: "זמן מתן תורתנו",
      },
    ],
  },
  {
    id: "spiritualActivity",
    category: "values",
    subcategory: "opening",
    question: "איזו פעילות רוחנית מדברת אליך?",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Hand size={24} />,
        text: "תפילה",
        value: "prayer",
        description: "חיבור אישי לבורא עולם",
      },
      {
        icon: <BookOpen size={24} />,
        text: "לימוד תורה",
        value: "torah",
        description: "העמקה בכתבי הקודש",
      },
      {
        icon: <Flower size={24} />,
        text: "מדיטציה",
        value: "meditation",
        description: "התבוננות פנימית ומודעות",
      },
      {
        icon: <HandHeart size={24} />,
        text: "התנדבות",
        value: "volunteering",
        description: "עזרה לזולת וחסד",
      },
    ],
    minSelections: 1,
    maxSelections: 3,
  },
  {
    id: "valuesPriorities",
    category: "values",
    subcategory: "priorities",
    question: "איך היית מחלק/ת את סדרי העדיפויות בחיים?",
    type: "budgetAllocation",
    depth: "ADVANCED",
    isRequired: true,
    totalPoints: 100,
    categories: [
      {
        label: "משפחה",
        icon: <Users />,
        min: 0,
        max: 100,
        description: "זמן ואנרגיה המוקדשים למשפחה",
      },
      {
        label: "רוחניות",
        icon: <Heart />,
        min: 0,
        max: 100,
        description: "התפתחות רוחנית ואמונה",
      },
      {
        label: "קריירה",
        icon: <Target />,
        min: 0,
        max: 100,
        description: "התפתחות מקצועית והגשמה",
      },
      {
        label: "חברה וקהילה",
        icon: <Globe />,
        min: 0,
        max: 100,
        description: "מעורבות חברתית וקהילתית",
      },
    ],
  },
  {
    id: "lifePhilosophy",
    category: "values",
    subcategory: "beliefs",
    question: "מהי תפיסת העולם שמנחה אותך בחיים?",
    type: "openText",
    depth: "EXPERT",
    isRequired: false,
    placeholder: "שתף/י את האמונות והערכים שמנחים אותך...",
    minLength: 100,
    maxLength: 1000,
    metadata: {
      helpText: "זו שאלה מעמיקה שמטרתה להבין את השקפת העולם הייחודית שלך",
      estimatedTime: 5,
    },
  },
];

export default valueQuestions;
