// src/components/questionnaire/questions/personality/personalityQuestions.tsx
import { Question } from '../../types/types';
import {
  Sun,
  Moon,
  Users,
  Brain,
  Heart,
  Target,
  Compass,
  Cloud,
  Leaf,
  Home,
  Watch,
  Scale,
  Coffee,
  MessageCircle,
  HandHeart,
  Lightbulb,
  Sparkles,
  Star,
  Smile,
  ShieldCheck,
  BookOpen,
  Palette,
  Headphones,
  Mountain,
  Bed,
  Utensils,
  Activity,
  Edit,
  HelpCircle,
  Anchor,
  Feather,
} from 'lucide-react';

export const personalityQuestions: Question[] = [
  {
    worldId: 'PERSONALITY',
    id: 'personality_self_portrayal_revised',
    category: 'personality',
    subcategory: 'self_perception',
    type: 'openText',
    depth: 'BASIC',
    isRequired: true,
    minLength: 70,
    maxLength: 500,
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_core_trait_selection_revised',
    category: 'personality',
    subcategory: 'self_perception',
    type: 'budgetAllocation',
    depth: 'BASIC',
    isRequired: true,
    totalPoints: 100,
    categories: [
      { value: 'empathetic_sensitive', icon: <Heart /> },
      { value: 'honest_reliable', icon: <ShieldCheck /> },
      { value: 'optimistic_cheerful', icon: <Sun /> },
      { value: 'humorous', icon: <Smile /> },
      { value: 'intelligent_curious', icon: <Brain /> },
      { value: 'ambitious_motivated', icon: <Star /> },
      { value: 'easygoing_flexible', icon: <Feather /> },
      { value: 'responsible_organized', icon: <Target /> },
      { value: 'creative_original', icon: <Lightbulb /> },
      { value: 'stable_grounded', icon: <Anchor /> },
      { value: 'decisive_confident', icon: <Compass /> },
      { value: 'generous_caring', icon: <HandHeart /> },
    ],
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_social_battery_recharge',
    category: 'personality',
    subcategory: 'lifestyle',
    type: 'scenario',
    depth: 'BASIC',
    isRequired: true,
    options: [
      { value: 'quiet_evening_home', icon: <Moon /> },
      { value: 'intimate_gathering', icon: <Coffee /> },
      { value: 'energetic_social_outing', icon: <Users /> },
      { value: 'flexible_combination', icon: <Scale /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_biological_clock',
    category: 'personality',
    subcategory: 'lifestyle',
    type: 'scale',
    depth: 'BASIC',
    isRequired: true,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_daily_structure_revised',
    category: 'personality',
    subcategory: 'lifestyle',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: true,
    options: [
      { value: 'order_planning', icon: <Watch /> },
      { value: 'flexibility_flow', icon: <Cloud /> },
      { value: 'task_oriented', icon: <Target /> },
      { value: 'balance', icon: <Scale /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_social_situation_revised',
    category: 'personality',
    subcategory: 'social_communication',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: true,
    options: [
      { value: 'initiator', icon: <Users /> },
      { value: 'joiner', icon: <Coffee /> },
      { value: 'deep_diver', icon: <MessageCircle /> },
      { value: 'observer', icon: <Compass /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_unproductive_day_feeling',
    category: 'personality',
    subcategory: 'emotional_coping',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'self_compassion', icon: <Heart /> },
      { value: 'criticism_action', icon: <Target /> },
      { value: 'analysis_learning', icon: <Brain /> },
      { value: 'immediate_fix', icon: <Activity /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_plan_change_reaction',
    category: 'personality',
    subcategory: 'emotional_coping',
    type: 'scale',
    depth: 'BASIC',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_stress_management_revised',
    category: 'personality',
    subcategory: 'emotional_coping',
    type: 'multiSelectWithOther',
    depth: 'BASIC',
    isRequired: true,
    options: [
      { value: 'movement_sport', icon: <Activity /> },
      { value: 'talk_vent', icon: <Users /> },
      { value: 'alone_time_rest', icon: <Bed /> },
      { value: 'nature', icon: <Leaf /> },
      { value: 'creative_hobby', icon: <Palette /> },
      { value: 'order_organization', icon: <Brain /> },
      { value: 'media_disconnect', icon: <Headphones /> },
    ],
    minSelections: 1,
    maxSelections: 3,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_friendship_in_action',
    category: 'personality',
    subcategory: 'social_communication',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 50,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_friend_in_crisis',
    category: 'personality',
    subcategory: 'social_communication',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'emotional_support', icon: <Heart /> },
      { value: 'problem_solving', icon: <Brain /> },
      { value: 'clarification_analysis', icon: <MessageCircle /> },
      { value: 'distraction', icon: <Sparkles /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_handling_criticism_revised',
    category: 'personality',
    subcategory: 'emotional_coping',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 50,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_communication_style_revised',
    category: 'personality',
    subcategory: 'social_communication',
    type: 'budgetAllocation',
    depth: 'ADVANCED',
    isRequired: true,
    totalPoints: 100,
    categories: [
      { value: 'direct_clear', icon: <Target /> },
      { value: 'empathetic_listening', icon: <HandHeart /> },
      { value: 'logic_facts', icon: <Brain /> },
      { value: 'humor_lightness', icon: <Smile /> },
      { value: 'openness_emotional_sharing', icon: <Heart /> },
    ],
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_humor_type',
    category: 'personality',
    subcategory: 'social_communication',
    type: 'multiSelect',
    depth: 'ADVANCED',
    isRequired: false,
    minSelections: 1,
    maxSelections: 2,
    options: [
      { value: 'cynical_witty' },
      { value: 'puns_wordplay' },
      { value: 'situational_sitcom' },
      { value: 'self_deprecating' },
      { value: 'silly_light' },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_learning_process',
    category: 'personality',
    subcategory: 'growth_aspirations',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 50,
    maxLength: 500,
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_failure_lesson',
    category: 'personality',
    subcategory: 'emotional_coping',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 50,
    maxLength: 500,
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_good_vs_perfect_day',
    category: 'personality',
    subcategory: 'lifestyle',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_vacation_compass',
    category: 'personality',
    subcategory: 'lifestyle',
    type: 'budgetAllocation',
    depth: 'ADVANCED',
    isRequired: true,
    totalPoints: 100,
    categories: [
      { value: 'relaxation', icon: <Bed /> },
      { value: 'adventure', icon: <Mountain /> },
      { value: 'city_life', icon: <Sparkles /> },
      { value: 'social_time', icon: <Users /> },
      { value: 'romance', icon: <Heart /> },
      { value: 'enrichment', icon: <BookOpen /> },
    ],
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_primary_motivation_revised',
    category: 'personality',
    subcategory: 'growth_aspirations',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: true,
    options: [
      { value: 'achieving_goals', icon: <Star /> },
      { value: 'building_connections', icon: <Heart /> },
      { value: 'giving_impact', icon: <HandHeart /> },
      { value: 'learning_curiosity', icon: <BookOpen /> },
      { value: 'creativity_expression', icon: <Sparkles /> },
      { value: 'security_stability', icon: <ShieldCheck /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'PERSONALITY',
    id: 'personality_strengths_and_weaknesses_revised',
    category: 'personality',
    subcategory: 'growth_aspirations',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: true,
    minLength: 70,
    maxLength: 600,
    metadata: { estimatedTime: 3 },
  },
];
