// personalityQuestionsPartOne.tsx
import { Question } from "../../types/types";
import {
  Sun,
  Moon,
  Cloud,
  Compass,
  Flower,
  Users,
  Book,
  Leaf,
  Coffee,
  Target,
  MessageCircle,
  HandHeart,
  Lightbulb,
  Brain,
  Map,
  Star,
  Heart,
  Music,
  Home,
  Edit,
  PenTool,
  Bike,
  Pizza,
  Camera,
  Globe,
  Gift,
  Watch,
  Phone,
} from "lucide-react";

export const personalityQuestionsPartOne: Question[] = [
  {
    worldId: "PERSONALITY",
    id: "personality_description",
    category: "personality",
    subcategory: "depth",
    question: "ספר על עצמך ב10 משפטים",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "נשמח לשמוע עליך בכתיבה חופשית, כנה וזורמת",
  },
  {
    worldId: "PERSONALITY",
    id: "personality_type",
    category: "personality",
    subcategory: "basics",
    question: "איך היית מגדיר/ה את האישיות שלך בצורה הכי מדוייקת?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Sun />,
        text: "אנרגטי/ת ופתוח/ה",
        value: "energetic",
        description: "אוהב/ת להיות במרכז העניינים ולהכיר אנשים חדשים",
      },
      {
        icon: <Moon />,
        text: "שקט/ה ומופנם/ת",
        value: "quiet",
        description: "מעדיף/ה מפגשים אינטימיים ושקט",
      },
      {
        icon: <Cloud />,
        text: "זורם/ת ומסתגל/ת",
        value: "adaptable",
        description: "גמיש/ה ומסתגל/ת בקלות למצבים חדשים",
      },
      {
        icon: <Compass />,
        text: "מוכוון/ת מטרה",
        value: "focused",
        description: "ממוקד/ת במטרות וביעדים",
      },
    ],
  },
  {
    worldId: "PERSONALITY",

    id: "life_mission",
    category: "personality",
    subcategory: "depth",
    question: "מהי השליחות או המטרה שאת/ה מרגיש/ה שיש לך בחיים?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: false,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י את החזון והשאיפות העמוקות שלך...",
  },
  {
    worldId: "PERSONALITY",

    id: "social_settings",
    category: "personality",
    subcategory: "basics",
    question: "באיזו סביבה חברתית את/ה מרגיש/ה הכי בנוח?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Users />,
        text: "מסיבות גדולות",
        value: "parties",
        description: "אירועים חברתיים גדולים ותוססים",
      },
      {
        icon: <Coffee />,
        text: "מפגשים קטנים",
        value: "small_gatherings",
        description: "מפגשים אינטימיים עם חברים קרובים",
      },
      {
        icon: <Home />,
        text: "בילוי ביתי",
        value: "home",
        description: "ערבים שקטים בבית עם משפחה",
      },
      {
        icon: <Book />,
        text: "לבד או בזוג",
        value: "alone",
        description: "זמן איכות לבד או עם אדם קרוב",
      },
    ],
  },
  {
    worldId: "PERSONALITY",
    id: "life_values",
    category: "personality",
    subcategory: "depth",
    question:
      "מהם שלושת הערכים החשובים ביותר בחייך ואיך הם באים לידי ביטוי ביומיום?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר/י את הערכים שמנחים אותך והדוגמאות מחייך...",
  },
  {
    worldId: "PERSONALITY",
    id: "free_time_activities",
    category: "personality",
    subcategory: "basics",
    question: "מה את/ה הכי אוהב/ת לעשות בזמן הפנוי?",
    type: "multiSelectWithOther",
    depth: "BASIC",
    isRequired: false,
    options: [
      {
        icon: <Book />,
        text: "קריאה ולמידה",
        value: "reading",
      },
      {
        icon: <Bike />,
        text: "ספורט ופעילות גופנית",
        value: "sports",
      },
      {
        icon: <PenTool />,
        text: "יצירה ואומנות",
        value: "art",
      },
      {
        icon: <Music />,
        text: "מוזיקה ובידור",
        value: "music",
      },
      {
        icon: <Flower />,
        text: "טבע וגינון",
        value: "nature",
      },
      {
        icon: <Globe />,
        text: "טיולים ונסיעות",
        value: "travel",
      },
      {
        icon: <Edit />,
        text: "אחר",
        value: "other",
        allowFreeText: true,
        placeholder: "ספר/י לנו מה את/ה אוהב/ת לעשות...",
      },
    ],
    minSelections: 1,
    maxSelections: 3,
  },
  {
    worldId: "PERSONALITY",

    id: "relationship_lessons",
    category: "personality",
    subcategory: "depth",
    question:
      "מה למדת על עצמך ממערכות היחסים המשמעותיות בחייך?(לאו דווקא זוגיות)",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 100,
    maxLength: 800,
    placeholder: "שתף/י תובנות ולקחים ממערכות יחסים...",
  },
  {
    worldId: "PERSONALITY",

    id: "communication_style",
    category: "personality",
    subcategory: "basics",
    question: " איזה סוג של שיח מועדף עליך ביום יום?",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <MessageCircle />,
        text: "קליל וכיפי",
        value: "fun",
        description: "שיח קליל שמעורב בצחוקים ואווירה כיפית",
      },
      {
        icon: <HandHeart />,
        text: "עמוק ומשמעותי",
        value: "sensitive",
        description: "שיח פורה ומשמעותי סביב ערכים",
      },
      {
        icon: <Lightbulb />,
        text: "רציני וענייני",
        value: "creative",
        description: "מדבר לעניין בלי יותר מדי חפירות",
      },
      {
        icon: <Brain />,
        text: "לא מרבה לדבר",
        value: "quiet",
        description: "שקט זה הדבר המועדף עליי",
      },
    ],
    minSelections: 1,
    maxSelections: 2,
  },
  {
    worldId: "PERSONALITY",
    id: "perfect_morning_detail",
    category: "personality",
    subcategory: "depth",
    question:
      "תאר/י את הבוקר המושלם שלך - משעת הקימה ועד הצהריים. מה כולל בוקר כזה ולמה דווקא הפעילויות האלו משמחות אותך?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: false,
    minLength: 50,
    maxLength: 500,
    placeholder: "תאר/י את סדר היום, הפעילויות והתחושות שעולות בך...",
  },
  {
    worldId: "PERSONALITY",
    id: "daily_routine",
    category: "personality",
    subcategory: "basics",
    question: "איך את/ה מעדיף/ה לנהל את היום-יום?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Watch />,
        text: "שגרה מתוכננת",
        value: "structured",
        description: "לוח זמנים קבוע ומאורגן",
      },
      {
        icon: <Cloud />,
        text: "זרימה גמישה",
        value: "flexible",
        description: "התאמה לפי הצורך והמצב",
      },
      {
        icon: <Target />,
        text: "מוכוון משימות",
        value: "task_oriented",
        description: "התקדמות לפי יעדים",
      },
      {
        icon: <Sun />,
        text: "ספונטני ומשתנה",
        value: "spontaneous",
        description: "כל יום שונה ומפתיע",
      },
    ],
  },
  {
    worldId: "PERSONALITY",
    id: "future_self",
    category: "personality",
    subcategory: "depth",
    question: "איך את/ה רואה את עצמך בעוד עשר שנים? מה השתנה ומה נשאר דומה?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: false,
    minLength: 100,
    maxLength: 800,
    placeholder: "תאר/י את החזון העתידי שלך...",
  },
];

export default personalityQuestionsPartOne;
