// src/components/HomePage/components/demo-data.ts
import type {
  ExtendedMatchSuggestion,
  PartyInfo,
} from '@/app/components/suggestions/types';
import type {
  QuestionnaireResponse as QuestionnaireResponseType,
  UserProfile,
  UserImage,
} from '@/types/next-auth';
import {
  ReligiousJourney,
  ServiceType,
  Gender,
  AvailabilityStatus,
  KippahType,
  HeadCoveringType,
} from '@prisma/client';

// --- תשובות שאלון לדמו #1: נועה (הבחורה) ---
const noaQuestionnaireResponse: QuestionnaireResponseType = {
  id: 'qr-demo-noa',
  userId: 'demo-profile-noa',
  // התשובות נשמרות כאובייקט JSON, כאשר כל מפתח הוא ID השאלה
  valuesAnswers: {
    values_core_elaboration:
      'הערך הכי חשוב לי הוא משפחה, וזה מתבטא בכך שאני משקיעה זמן רב בקשר עם ההורים והאחים שלי, ורואה את הבית העתידי שלי כמקום חם ומכיל שמהווה מרכז לעולם שלנו.',
    values_attitude_towards_money: 'איזון בין נוחות חומרית לערכים אחרים',
  },
  personalityAnswers: null,
  relationshipAnswers: {
    relationship_core_meaning: [
      'חיבור רגשי עמוק, אינטימיות והבנה הדדית',
      'שותפות איתנה, חברות אמת ותמיכה הדדית',
    ],
    relationship_intimacy_meaning:
      'אינטימיות עבורי היא היכולת להיות חשופה לחלוטין בפני מישהו, לשתף בחלומות ובפחדים, ולדעת שיש מישהו בעולם שמכיר אותי באמת ומקבל אותי כמו שאני.',
  },
  partnerAnswers: {
    partner_must_have_quality_final:
      'התכונה החשובה ביותר היא טוב לב. אדם עם לב טוב הוא אדם שיודע לתת, לקבל, לסלוח ולהיות שותף אמיתי. כל השאר נבנה על היסוד הזה.',
  },
  religionAnswers: null,
  valuesCompleted: true,
  personalityCompleted: false,
  relationshipCompleted: true,
  partnerCompleted: true,
  religionCompleted: false,
  worldsCompleted: ['VALUES', 'RELATIONSHIP', 'PARTNER'],
  completed: false,
  startedAt: new Date(),
  completedAt: null,
  lastSaved: new Date(),
  createdAt: new Date(),
  updatedAt: new Date(),
  formattedAnswers: null,
};

// --- פרופיל מלא לדמו #1: נועה (הבחורה) ---
const noaProfile: PartyInfo = {
  id: 'demo-profile-noa',
  email: 'noa.demo@example.com',
  firstName: 'נועה',
  lastName: 'ישראלי',
  isProfileComplete: true,
  images: [
    {
      id: 'img1',
      url: 'https://res.cloudinary.com/dmfxoi6g0/image/upload/v1753700882/dina4_gr0ako.jpg',
      isMain: true,
      userId: 'demo-profile-noa',
      createdAt: new Date(),
      updatedAt: new Date(),
      cloudinaryPublicId: 'dina4_gr0ako',
    },
    {
      id: 'img2',
      url: 'https://res.cloudinary.com/dmfxoi6g0/image/upload/v1753700882/dina4_gr0ako.jpg',
      isMain: false,
      userId: 'demo-profile-noa',
      createdAt: new Date(),
      updatedAt: new Date(),
      cloudinaryPublicId: 'dina4_gr0ako',
    },
    {
      id: 'img3',
      url: 'https://res.cloudinary.com/dmfxoi6g0/image/upload/v1753700882/dina4_gr0ako.jpg',
      isMain: false,
      userId: 'demo-profile-noa',
      createdAt: new Date(),
      updatedAt: new Date(),
      cloudinaryPublicId: 'dina4_gr0ako',
    },
    {
      id: 'img4',
      url: 'https://res.cloudinary.com/dmfxoi6g0/image/upload/v1753700882/dina4_gr0ako.jpg',
      isMain: false,
      userId: 'demo-profile-noa',
      createdAt: new Date(),
      updatedAt: new Date(),
      cloudinaryPublicId: 'dina4_gr0ako',
    },
  ],
  profile: {
    id: 'profile-noa-demo',
    userId: 'demo-profile-noa',
    gender: Gender.FEMALE,
    birthDate: new Date('1996-05-15T00:00:00.000Z'),
    birthDateIsApproximate: false,
    height: 168,
    city: 'תל אביב',
    occupation: 'מעצבת UX/UI בכירה',
    education: 'תואר ראשון בתקשורת חזותית, בצלאל',
    educationLevel: 'academic_ba',
    religiousLevel: 'דתי לאומי תורני',
    shomerNegiah: false,
    about:
      'אופטימית וחובבת שיחות עומק על כוס קפה. מוצאת יופי בדברים הקטנים של החיים, בין אם זה טיול בטבע או פלייליסט טוב. מחפשת שותף לדרך, לבנות יחד בית שמלא בצחוק, כבוד הדדי וצמיחה משותפת.',
    maritalStatus: 'רווקה',
    profileCharacterTraits: ['אופטימית', 'יצירתית', 'אמפתית'],
    profileHobbies: ['טיולים', 'קריאה', 'אומנות ויצירה'],
    preferredAgeMin: 28,
    preferredAgeMax: 35,
    preferredReligiousLevels: [
      'דתי/ה לאומי/ת ליברלי/ת',
      'מסורתי/ת (קרוב/ה לדת)',
    ],
    isProfileVisible: true,
    availabilityStatus: AvailabilityStatus.AVAILABLE,
    createdAt: new Date(),
    updatedAt: new Date(),
    hasViewedProfilePreview: false,
    nativeLanguage: 'עברית',
    additionalLanguages: ['אנגלית'],
    origin: 'מעורב',
    serviceType: ServiceType.NATIONAL_SERVICE_TWO_YEARS,
    parentStatus: 'נשואים',
    preferredLocations: ['מרכז'],
    preferredEducation: ['אקדמית'],
    preferredOccupations: ['הייטק', 'יצירתי'],
    preferredMaritalStatuses: ['רווק/ה'],
    preferredOrigins: ['ללא העדפה מיוחדת'],
    preferredServiceTypes: [],
    preferredHeadCoverings: [],
    preferredKippahTypes: [],
    preferredCharacterTraits: ['בעל חוש הומור', 'שאפתן', 'כן וישר'],
    preferredHobbies: ['טיולים', 'מוזיקה/נגינה'],
    hasChildrenFromPrevious: false,
    matchingNotes:
      'מחפשת מישהו עם ראש פתוח, שאוהב ללמוד ולהתפתח. חשוב לי מאוד חוש הומור טוב ויכולת לנהל שיחות עמוקות. פחות מתחברת לציניות וחשוב לי שיהיה אופטימי וחיובי.',
    contactPreference: 'both',
    religiousJourney: ReligiousJourney.BORN_INTO_CURRENT_LIFESTYLE,
    manualEntryText: null,
    preferredReligiousJourneys: [ReligiousJourney.BORN_INTO_CURRENT_LIFESTYLE],
    serviceDetails: null,
    headCovering: null,
    kippahType: null,
    aliyaCountry: null,
    aliyaYear: null,
    siblings: 4,
    position: 2,
    preferredHeightMin: 175,
    preferredHeightMax: 190,
    preferredShomerNegiah: 'גמישה',
    preferredPartnerHasChildren: 'מעדיפה שלא',
    preferredAliyaStatus: 'ללא העדפה',
    preferredHasChildrenFromPrevious: false,
    preferredMatchmakerGender: null,
    verifiedBy: null,
    availabilityNote: null,
    availabilityUpdatedAt: null,
    lastActive: null,
  },
};

// --- הצעה מלאה לדמו #1: נועה ---
export const demoSuggestionDataFemale: ExtendedMatchSuggestion = {
  id: 'demo-suggestion-homepage-female',
  matchmakerId: 'matchmaker-demo',
  firstPartyId: 'visitor-user-id',
  secondPartyId: 'demo-profile-noa',
  status: 'PENDING_FIRST_PARTY',
  priority: 'HIGH',
  createdAt: new Date(),
  updatedAt: new Date(),
  lastActivity: new Date(),
  category: 'ACTIVE',
  matchingReason:
    'זיהיתי חיבור מיוחד בין האופטימיות והאהבה שלכם לשיחות עומק. שניכם מחפשים קשר המבוסס על כבוד, צמיחה משותפת ובית מלא בצחוק. אני מאמין שהערכים הדתיים הליברליים שלכם והשאיפות המקצועיות יכולים להשתלב בצורה הרמונית וליצור בסיס איתן לקשר משמעותי.',
  firstPartyNotes:
    'זו הצעה שאני מתרגשת במיוחד להציג לך. נועה היא בחורה איכותית, עם עומק ורגישות שנדיר למצוא. אני חושבת שהיא בדיוק מה שחיפשת.',
  secondPartyNotes: null,
  internalNotes: null,
  followUpNotes: null,
  responseDeadline: null,
  decisionDeadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
  lastStatusChange: new Date(),
  previousStatus: 'DRAFT',
  firstPartySent: new Date(),
  firstPartyResponded: null,
  secondPartySent: null,
  secondPartyResponded: null,
  firstMeetingScheduled: null,
  closedAt: null,
  matchmaker: { firstName: 'דינה', lastName: 'אנגלרד' },
  firstParty: {
    id: 'visitor-user-id',
    email: 'visitor@example.com',
    firstName: 'המשתמש',
    lastName: 'שלנו',
    isProfileComplete: true,
    profile: null,
    images: [],
  },
  secondParty: noaProfile,
  statusHistory: [
    {
      id: 'h1f',
      suggestionId: 'demo-suggestion-homepage-female',
      status: 'DRAFT',
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
      notes: 'השדכנית יצרה טיוטת הצעה',
    },
    {
      id: 'h2f',
      suggestionId: 'demo-suggestion-homepage-female',
      status: 'PENDING_FIRST_PARTY',
      createdAt: new Date(),
      notes: 'ההצעה נשלחה אליך לבדיקה ראשונית.',
    },
  ],
};

// --- תשובות שאלון לדמו #2: דניאל (הבחור) ---
const danielQuestionnaireResponse: QuestionnaireResponseType = {
  id: 'qr-demo-daniel',
  userId: 'demo-profile-daniel',
  valuesAnswers: {
    values_life_priorities_allocation: {
      'זוגיות וחיפוש זוגיות': 30,
      משפחה: 20,
      'קריירה ופרנסה': 25,
      'רוחניות, דת ולימוד תורה': 15,
      'חברים, קהילה והתנדבות': 5,
      'פנאי ותחביבים': 5,
    },
  },
  personalityAnswers: {
    personality_self_portrayal:
      'אני אדם של עשייה, אוהב אתגרים ומטרות. חשובה לי מאוד האמינות, ואני תמיד משתדל לעמוד במילה שלי. יש לי צד אנליטי חזק, אבל גם מאוד אוהב לנגן ולבלות בטבע כדי להתאזן.',
    personality_introversion_extroversion: 7,
  },
  relationshipAnswers: null,
  partnerAnswers: {
    partner_core_character_traits_essential: {
      'יושרה, אמינות וכנות': 30,
      'חום, אמפתיה וטוב לב': 20,
      'אינטליגנציה וסקרנות': 20,
      'אופטימיות ושמחת חיים': 15,
      'תקשורת טובה והקשבה': 15,
    },
    partner_must_have_quality_final:
      'התכונה הכי חשובה לי היא שותפות. הידיעה שיש לי מישהי לצידי, שאנחנו צוות מול כל מה שהחיים מביאים, ושאנחנו תמיד דואגים אחד לשנייה.',
  },
  religionAnswers: null,
  valuesCompleted: true,
  personalityCompleted: true,
  relationshipCompleted: false,
  partnerCompleted: true,
  religionCompleted: false,
  worldsCompleted: ['VALUES', 'PERSONALITY', 'PARTNER'],
  completed: false,
  startedAt: new Date(),
  completedAt: null,
  lastSaved: new Date(),
  createdAt: new Date(),
  updatedAt: new Date(),
  formattedAnswers: null,
};

// --- פרופיל מלא לדמו #2: דניאל (הבחור) ---
const danielProfile: PartyInfo = {
  id: 'demo-profile-daniel',
  email: 'daniel.demo@example.com',
  firstName: 'דניאל',
  lastName: 'כהן',
  isProfileComplete: true,
  images: [
    {
      id: 'img1m',
      url: 'https://res.cloudinary.com/dmfxoi6g0/image/upload/v1753700884/eitan_h9ylkc.jpg',
      isMain: true,
      userId: 'demo-profile-daniel',
      createdAt: new Date(),
      updatedAt: new Date(),
      cloudinaryPublicId: 'eitan_h9ylkc',
    },
    {
      id: 'img2m',
      url: 'https://res.cloudinary.com/dmfxoi6g0/image/upload/v1753700884/eitan_h9ylkc.jpg',
      isMain: false,
      userId: 'demo-profile-daniel',
      createdAt: new Date(),
      updatedAt: new Date(),
      cloudinaryPublicId: 'eitan_h9ylkc',
    },
    {
      id: 'img3m',
      url: 'https://res.cloudinary.com/dmfxoi6g0/image/upload/v1753700884/eitan_h9ylkc.jpg',
      isMain: false,
      userId: 'demo-profile-daniel',
      createdAt: new Date(),
      updatedAt: new Date(),
      cloudinaryPublicId: 'eitan_h9ylkc',
    },
    {
      id: 'img4m',
      url: 'https://res.cloudinary.com/dmfxoi6g0/image/upload/v1753700884/eitan_h9ylkc.jpg',
      isMain: false,
      userId: 'demo-profile-daniel',
      createdAt: new Date(),
      updatedAt: new Date(),
      cloudinaryPublicId: 'eitan_h9ylkc',
    },
  ],
  profile: {
    id: 'profile-daniel-demo',
    userId: 'demo-profile-daniel',
    gender: Gender.MALE,
    birthDate: new Date('1994-08-20T00:00:00.000Z'),
    birthDateIsApproximate: false,
    height: 182,
    city: 'ירושלים',
    occupation: 'מהנדס תוכנה וסטודנט לתואר שני',
    education: 'תואר ראשון בהנדסת תוכנה, הטכניון',
    educationLevel: 'academic_student',
    religiousLevel: 'דתי לאומי-ליברלי',
    shomerNegiah: true,
    about:
      'בחור של אנשים ושל עשייה. אוהב את השילוב בין עולם ההייטק הדינמי לבין קביעת עיתים לתורה. מאמין שצריך לחיות חיים מלאים עם משמעות, גם בעבודה וגם מחוצה לה. בשעות הפנאי אוהב לטייל בארץ, לנגן בגיטרה ולבלות זמן איכות עם חברים. מחפש שותפה לחיים, לבנות ביחד בית עם יראת שמיים, פתיחות מחשבתית והרבה שמחה.',
    maritalStatus: 'רווק',
    profileCharacterTraits: ['שאפתן', 'ישר ואמין', 'משפחתי'],
    profileHobbies: ['טיולים', 'מוזיקה/נגינה', 'למידה/קורסים'],
    preferredAgeMin: 26,
    preferredAgeMax: 32,
    preferredReligiousLevels: [
      'דתי/ה לאומי/ת תורני/ת',
      'דתי/ה לאומי/ת (סטנדרטי)',
    ],
    isProfileVisible: true,
    availabilityStatus: AvailabilityStatus.AVAILABLE,
    createdAt: new Date(),
    updatedAt: new Date(),
    hasViewedProfilePreview: false,
    nativeLanguage: 'עברית',
    additionalLanguages: ['אנגלית'],
    origin: 'ספרדי',
    serviceType: ServiceType.MILITARY_INTELLIGENCE_CYBER_TECH,
    parentStatus: 'נשואים',
    preferredLocations: ['ירושלים', 'מרכז'],
    preferredEducation: ['אקדמית'],
    preferredOccupations: [],
    preferredMaritalStatuses: ['רווק/ה'],
    preferredOrigins: ['ללא העדפה מיוחדת'],
    preferredServiceTypes: [],
    preferredHeadCoverings: [
      HeadCoveringType.FULL_COVERAGE,
      HeadCoveringType.PARTIAL_COVERAGE,
    ],
    preferredKippahTypes: [],
    preferredCharacterTraits: ['אמפתית', 'אופטימית', 'בעלת חוש הומור'],
    preferredHobbies: ['טיולים', 'קריאה', 'בישול/אפיה'],
    hasChildrenFromPrevious: false,
    matchingNotes:
      'מחפש בחורה עם עומק, שמחה ורצון לבנות בית של תורה וערכים. מישהי שהיא גם חברה טובה, שאפשר לנהל איתה שיחות נפש וגם לצחוק איתה על הכל. חשוב לי שתהיה לה שאיפה להתפתח, גם אישית וגם רוחנית, ושנצעד יחד בדרך משותפת.',
    contactPreference: 'matchmaker',
    religiousJourney: ReligiousJourney.BORN_INTO_CURRENT_LIFESTYLE,
    manualEntryText: null,
    preferredReligiousJourneys: [ReligiousJourney.BORN_INTO_CURRENT_LIFESTYLE],
    serviceDetails: 'שירות משמעותי ביחידה 8200',
    headCovering: null,
    kippahType: KippahType.KNITTED_SMALL,
    aliyaCountry: null,
    aliyaYear: null,
    siblings: 3,
    position: 1,
    preferredHeightMin: 160,
    preferredHeightMax: 175,
    preferredShomerNegiah: 'כן, חשוב לי',
    preferredPartnerHasChildren: 'מעדיף שלא',
    preferredAliyaStatus: 'ללא העדפה',
    preferredHasChildrenFromPrevious: false,
    preferredMatchmakerGender: null,
    verifiedBy: null,
    availabilityNote: null,
    availabilityUpdatedAt: null,
    lastActive: null,
  },
  questionnaireResponses: [danielQuestionnaireResponse],
};

// --- הצעה מלאה לדמו #2: דניאל ---
export const demoSuggestionDataMale: ExtendedMatchSuggestion = {
  id: 'demo-suggestion-homepage-male',
  matchmakerId: 'matchmaker-demo-2',
  firstPartyId: 'visitor-user-id',
  secondPartyId: 'demo-profile-daniel',
  status: 'PENDING_FIRST_PARTY',
  priority: 'HIGH',
  createdAt: new Date(),
  updatedAt: new Date(),
  lastActivity: new Date(),
  category: 'ACTIVE',
  matchingReason:
    'החיבור בין הרצון שלך ליציבות ובית חם לבין השאיפות והאמביציה של דניאל נראה לי מבטיח במיוחד. שניכם אנשים של עשייה, עם רגליים על הקרקע אבל ראש בעננים. אני מאמין שהרצון שלו להקים בית תורני מודרני והגישה שלך לחיים יכולים ליצור שלם הגדול מסך חלקיו.',
  firstPartyNotes:
    'דניאל הוא בחור רציני, ערכי ועם לב זהב. הוא משלב בצורה מרשימה בין עולם התורה לעולם המעשה, ומחפש שותפה אמיתית לחיים. אני חושב שיש לכם הרבה על מה לדבר.',
  secondPartyNotes: null,
  internalNotes: null,
  followUpNotes: null,
  responseDeadline: null,
  decisionDeadline: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
  lastStatusChange: new Date(),
  previousStatus: 'DRAFT',
  firstPartySent: new Date(),
  firstPartyResponded: null,
  secondPartySent: null,
  secondPartyResponded: null,
  firstMeetingScheduled: null,
  closedAt: null,
  matchmaker: { firstName: 'איתן', lastName: 'אנגלרד' },
  firstParty: {
    id: 'visitor-user-id',
    email: 'visitor@example.com',
    firstName: 'המשתמשת',
    lastName: 'שלנו',
    isProfileComplete: true,
    profile: null,
    images: [],
  },
  secondParty: danielProfile,
  statusHistory: [
    {
      id: 'h1m',
      suggestionId: 'demo-suggestion-homepage-male',
      status: 'DRAFT',
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      notes: 'השדכן יצר טיוטת הצעה',
    },
    {
      id: 'h2m',
      suggestionId: 'demo-suggestion-homepage-male',
      status: 'PENDING_FIRST_PARTY',
      createdAt: new Date(),
      notes: 'ההצעה נשלחה אליך לבדיקה ראשונית.',
    },
  ],
};
