// src/components/questionnaire/questions/values/valuesQuestions.tsx
import { Question } from '../../types/types';
import {
  Heart,
  Scale,
  Brain,
  BookOpen,
  Users,
  Home,
  Briefcase,
  Target,
  PiggyBank,
  HandHeart,
  TrendingUp,
  Leaf,
  Sparkles,
  ShieldCheck,
  Flag,
  HelpCircle,
  Info,
  Scroll,
  DollarSign,
  Activity,
  MessageCircle,
} from 'lucide-react';

export const valuesQuestions: Question[] = [
  {
    worldId: 'VALUES',
    id: 'values_core_identification_revised',
    category: 'values',
    subcategory: 'core_values',
    type: 'budgetAllocation',
    depth: 'BASIC',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'family_connections', icon: <Heart /> },
      { value: 'integrity_honesty', icon: <ShieldCheck /> },
      { value: 'spirituality_faith', icon: <BookOpen /> },
      { value: 'personal_growth', icon: <TrendingUp /> },
      { value: 'giving_contribution', icon: <HandHeart /> },
      { value: 'career_fulfillment', icon: <Briefcase /> },
      { value: 'financial_security', icon: <PiggyBank /> },
      { value: 'creativity_expression', icon: <Sparkles /> },
    ],
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'VALUES',
    id: 'values_core_elaboration_revised',
    category: 'values',
    subcategory: 'core_values',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 70,
    maxLength: 600,
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'VALUES',
    id: 'values_childhood_home_atmosphere',
    category: 'values',
    subcategory: 'core_values',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 10,
    maxLength: 150,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'VALUES',
    id: 'values_quiet_heroes',
    category: 'values',
    subcategory: 'core_values',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'VALUES',
    id: 'values_childhood_shaping_experience',
    category: 'values',
    subcategory: 'core_values',
    type: 'multiSelect',
    depth: 'ADVANCED',
    isRequired: false,
    minSelections: 1,
    maxSelections: 3,
    options: [
      { value: 'financial_struggle_or_abundance', icon: <DollarSign /> },
      { value: 'parental_relationship_dynamics', icon: <Home /> },
      { value: 'social_challenges_school', icon: <Users /> },
      { value: 'health_or_loss_experiences', icon: <Heart /> },
      { value: 'academic_pressure_or_freedom', icon: <BookOpen /> },
      { value: 'religious_environment_strict_or_open', icon: <Scroll /> },
    ],
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'VALUES',
    id: 'values_strength_from_challenge',
    category: 'values',
    subcategory: 'core_values',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 50,
    maxLength: 500,
    metadata: { estimatedTime: 3 },
  },

  {
    worldId: 'VALUES',
    id: 'values_two_job_offers',
    category: 'values',
    subcategory: 'life_priorities',
    type: 'scenario',
    depth: 'EXPERT',
    isRequired: false,
    options: [{ value: 'offer_a' }, { value: 'offer_b' }],
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'VALUES',
    id: 'values_life_priorities_allocation_revised',
    category: 'values',
    subcategory: 'life_priorities',
    type: 'budgetAllocation',
    depth: 'ADVANCED',
    isRequired: false,
    totalPoints: 100,
    categories: [
      { value: 'relationship', icon: <Heart /> },
      { value: 'family', icon: <Home /> },
      { value: 'career', icon: <Briefcase /> },
      { value: 'spirituality', icon: <BookOpen /> },
      { value: 'community', icon: <Users /> },
      { value: 'leisure', icon: <Sparkles /> },
    ],
    metadata: { estimatedTime: 4 },
  },
  {
    worldId: 'VALUES',
    id: 'values_health_lifestyle_importance',
    category: 'values',
    subcategory: 'life_priorities',
    type: 'scale',
    depth: 'BASIC',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'VALUES',
    id: 'values_risk_attitude',
    category: 'values',
    subcategory: 'life_priorities',
    type: 'iconChoice', // שינוי מסוג scale ל-iconChoice
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'stability_anchor', icon: <ShieldCheck /> }, // עוגן ויציבות
      { value: 'calculated_balance', icon: <Scale /> }, // איזון מחושב
      { value: 'growth_opportunity', icon: <TrendingUp /> }, // צמיחה והזדמנות
    ],
    metadata: { estimatedTime: 1 },
  },

  {
    worldId: 'VALUES',
    id: 'values_feeling_of_home',
    category: 'values',
    subcategory: 'community_social',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 30,
    maxLength: 300,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'VALUES',
    id: 'values_definition_of_rich_life',
    category: 'values',
    subcategory: 'material_intellectual',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'VALUES',
    id: 'values_attitude_towards_money_revised',
    category: 'values',
    subcategory: 'material_intellectual',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'security_tool', icon: <PiggyBank /> },
      { value: 'means_for_experiences', icon: <Sparkles /> },
      { value: 'balance_responsibility', icon: <Scale /> },
      { value: 'simplicity', icon: <Leaf /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'VALUES',
    id: 'values_definition_of_success',
    category: 'values',
    subcategory: 'material_intellectual',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 40,
    maxLength: 400,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'VALUES',
    id: 'values_extended_family_involvement',
    category: 'values',
    subcategory: 'community_social',
    type: 'singleChoice',
    depth: 'EXPERT',
    isRequired: false,
    options: [
      { value: 'high_involvement' },
      { value: 'healthy_boundaries' },
      { value: 'minimal_involvement' },
      { value: 'depends_on_dynamics' },
    ],
    metadata: { estimatedTime: 1 },
  },

  {
    worldId: 'VALUES',
    id: 'values_lost_wallet',
    category: 'values',
    subcategory: 'core_values',
    type: 'openText',
    depth: 'BASIC',
    isRequired: false,
    minLength: 30,
    maxLength: 300,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: 'VALUES',
    id: 'values_moral_dilemma',
    category: 'values',
    subcategory: 'core_values',
    type: 'scenario',
    depth: 'EXPERT',
    isRequired: false,
    options: [
      { value: 'express_discomfort' },
      { value: 'listen_without_judgment' },
      { value: 'challenge_and_advise' },
      { value: 'do_not_intervene' },
    ],
    metadata: { estimatedTime: 2 },
  },

  {
    worldId: 'VALUES',
    id: 'values_giving_tzedaka_importance_revised',
    category: 'values',
    subcategory: 'material_intellectual',
    type: 'scale',
    depth: 'BASIC',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'VALUES',
    id: 'values_education_pursuit_revised',
    category: 'values',
    subcategory: 'material_intellectual',
    type: 'iconChoice',
    depth: 'BASIC',
    isRequired: false,
    options: [
      { value: 'lifelong_learning', icon: <BookOpen /> },
      { value: 'goal_oriented_learning', icon: <Target /> },
      { value: 'experiential_learning', icon: <Sparkles /> },
      { value: 'appreciative_but_passive', icon: <Scale /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'VALUES',
    id: 'values_parents_tradition_conflict',
    category: 'values',
    subcategory: 'challenges_conflicts',
    type: 'openText',
    depth: 'EXPERT',
    isRequired: false,
    minLength: 50,
    maxLength: 500,
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: 'VALUES',
    id: 'values_social_political_stance_importance_partner_revised',
    category: 'values',
    subcategory: 'community_social',
    type: 'scale',
    depth: 'ADVANCED',
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'VALUES',
    id: 'values_dealing_with_disagreement_partner_revised',
    category: 'values',
    subcategory: 'challenges_conflicts',
    type: 'iconChoice',
    depth: 'ADVANCED',
    isRequired: false,
    options: [
      { value: 'discussion_understanding', icon: <MessageCircle /> },
      { value: 'finding_common_ground', icon: <Brain /> },
      { value: 'seeking_compromise', icon: <Scale /> },
      { value: 'agree_to_disagree', icon: <Heart /> },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: 'VALUES',
    id: 'values_non_negotiable_for_partner_revised',
    category: 'values',
    subcategory: 'summary_future',
    type: 'openText',
    depth: 'ADVANCED',
    isRequired: false,
    minLength: 30,
    maxLength: 300,
    metadata: { estimatedTime: 2 },
  },
];
