import { Question } from "../../types/types";
import {
  Scale,
  Users,
  Globe,
  Target,
  Map,
  Leaf,
  ScrollText,
  Construction,
  Brain,
  Laptop,
  HandHeart,
  Flag,
  Star,
  TreePine,
  Church,
} from "lucide-react";

export const valuesQuestionsPartTwo: Question[] = [
  {
    worldId: "VALUES",
    id: "state_religion",
    category: "values",
    subcategory: "depth",
    question: "מהי תפיסתך לגבי היחס בין דת ומדינה?",
    type: "iconChoice",
    depth: "ADVANCED",
    isRequired: true,
    options: [
      {
        icon: <Flag />,
        text: "הפרדה מלאה",
        value: "separation",
        description: "תומך בהפרדה בין דת ומדינה",
      },
      {
        icon: <Scale />,
        text: "איזון עדין",
        value: "balance",
        description: "מחפש איזון בין מסורת למודרנה",
      },
      {
        icon: <Church />,
        text: "זהות יהודית",
        value: "jewish_identity",
        description: "מעדיף שמירה על צביון יהודי מסורתי",
      },
      {
        icon: <Star />,
        text: "חופש בחירה",
        value: "freedom",
        description: "תומך בחופש בחירה אישי",
      },
    ],
  },
  {
    worldId: "VALUES",
    id: "environmental_view",
    category: "values",
    subcategory: "basics",
    question: "מהי גישתך לאיכות הסביבה?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: false,
    options: [
      {
        icon: <TreePine />,
        text: "אקטיביסט סביבתי",
        value: "activist",
        description: "פעיל בנושאי סביבה וקיימות",
      },
      {
        icon: <Leaf />,
        text: "מודעות בסיסית",
        value: "aware",
        description: "משתדל לשמור על הסביבה",
      },
      {
        icon: <Scale />,
        text: "איזון מעשי",
        value: "practical",
        description: "מאזן בין צרכים לסביבה",
      },
      {
        icon: <Target />,
        text: "מיקוד בהתפתחות",
        value: "development",
        description: "מעדיף פיתוח וקדמה",
      },
    ],
  },
  {
    worldId: "VALUES",
    id: "social_responsibility",
    category: "values",
    subcategory: "depth",
    question: "מהי תפיסתך לגבי אחריות חברתית?",
    type: "multiSelect",
    depth: "ADVANCED",
    isRequired: false,
    options: [
      {
        icon: <HandHeart />,
        text: "עזרה לזולת",
        value: "helping",
        description: "מאמין בעזרה הדדית וצדקה",
      },
      {
        icon: <Users />,
        text: "מעורבות קהילתית",
        value: "community",
        description: "פעיל בקהילה ובחברה",
      },
      {
        icon: <Globe />,
        text: "אחריות גלובלית",
        value: "global",
        description: "רואה אחריות כלפי העולם כולו",
      },
      {
        icon: <Construction />,
        text: "פיתוח חברתי",
        value: "development",
        description: "מאמין בפיתוח וקידום החברה",
      },
    ],
    minSelections: 1,
    maxSelections: 2,
  },
  {
    worldId: "VALUES",
    id: "shabbat_public",
    category: "values",
    subcategory: "depth",
    question: "איך צריך להיראות המרחב הציבורי בשבת?",
    type: "iconChoice",
    depth: "ADVANCED",
    isRequired: true,
    options: [
      {
        icon: <ScrollText />,
        text: "שמירה מסורתית",
        value: "traditional",
        description: "תומך בשמירת צביון השבת המסורתי",
      },
      {
        icon: <Scale />,
        text: "איזון מקומי",
        value: "local_balance",
        description: "תומך בהסדרה לפי אופי האזור",
      },
      {
        icon: <Star />,
        text: "חופש בחירה",
        value: "freedom",
        description: "תומך בחופש בחירה מלא",
      },
      {
        icon: <Map />,
        text: "הפרדה אזורית",
        value: "separation",
        description: "תומך בהפרדה בין אזורים שונים",
      },
    ],
  },
  {
    worldId: "VALUES",
    id: "technology_integration",
    category: "values",
    subcategory: "basics",
    question: "מהי גישתך לשילוב טכנולוגיה בחיים?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: false,
    options: [
      {
        icon: <Laptop />,
        text: "אימוץ מלא",
        value: "full_adoption",
        description: "מאמץ חידושים טכנולוגיים",
      },
      {
        icon: <Scale />,
        text: "שילוב מבוקר",
        value: "controlled",
        description: "משלב טכנולוגיה באופן מאוזן",
      },
      {
        icon: <Brain />,
        text: "גישה ביקורתית",
        value: "critical",
        description: "בוחן כל חידוש בקפידה",
      },
      {
        icon: <Target />,
        text: "שימוש מינימלי",
        value: "minimal",
        description: "מעדיף להגביל שימוש בטכנולוגיה",
      },
    ],
  },
];

export default valuesQuestionsPartTwo;
