// src/components/questionnaire/questions/values/valuesQuestions.tsx
import { Question } from "../../types/types";
import {
  Scale,
  Briefcase,
  Book,
  Target,
  Leaf,
  Building,
  Sword,
  Brain,
  Laptop,
  HandHeart,
  LibraryBig,
  Users,
  Globe,
  Map,
  ScrollText,
  Flag,
  Star,
  TreePine,
  Church,
  Heart,
  Coffee,
  Home,
  ShieldCheck,
  Award,
  PiggyBank,
  Palette,
  Music,
  TrendingUp, // אייקון לצמיחה אישית
  DollarSign, // אייקון לנתינה/כסף
  HelpCircle, // אייקון לשאלת המשך
} from "lucide-react";

export const valuesQuestions: Question[] = [
  // --- ערכים אישיים ---
  {
    worldId: "VALUES",
    id: "core_values_open",
    category: "values",
    subcategory: "personal",
    question:
      "מהם 3-5 הערכים החשובים ביותר שמנחים אותך בחיי היומיום? הסבר/י בקצרה מדוע כל אחד מהם חשוב ואיך הוא בא לידי ביטוי בחייך.",
    type: "openText",
    depth: "ADVANCED",
    isRequired: true,
    minLength: 150,
    maxLength: 1000,
    placeholder:
      "לדוגמה: משפחתיות - הקשר עם המשפחה הוא עוגן מרכזי עבורי, ואני משקיע/ה זמן בקשרים אלו. יושרה - חשוב לי להיות אדם שאפשר לסמוך עליו, לכן אעמוד במילה שלי גם אם זה לא נוח. צמיחה אישית - אני מאמינ/ה בלמידה מתמדת, ולכן אני קורא/ת ספרים בתחום המקצועי שלי...",
    metadata: { estimatedTime: 5 },
  },
  {
    worldId: "VALUES",
    id: "life_priorities_today",
    category: "values",
    subcategory: "personal",
    question:
      "סדר עדיפויות נוכחי: חלק/י 100 נקודות אנרגיה/חשיבות בין תחומי החיים הבאים, כפי שהם באים לידי ביטוי בחייך *היום*.",
    type: "budgetAllocation",
    depth: "ADVANCED",
    isRequired: true,
    totalPoints: 100,
    categories: [
      { label: "משפחה וקשרים קרובים", icon: <Home />, min: 0, max: 100, description: "זמן, אנרגיה ומחשבה המוקדשים למשפחה הגרעינית, משפחת המוצא וחברים קרובים." },
      { label: "קריירה ועבודה", icon: <Briefcase />, min: 0, max: 100, description: "השקעה בפיתוח מקצועי, קידום בעבודה, שעות עבודה והתמודדות עם אתגרים." },
      { label: "רוחניות ולימוד תורה", icon: <Book />, min: 0, max: 100, description: "זמן המוקדש לתפילה, לימוד, חשבון נפש ופעילויות רוחניות אחרות." },
      { label: "קהילה, חברים והתנדבות", icon: <Users />, min: 0, max: 100, description: "מעורבות קהילתית, קשרים חברתיים רחבים יותר, פעילויות התנדבות ותרומה לחברה." },
      { label: "פנאי, תחביבים וצמיחה אישית", icon: <Star />, min: 0, max: 100, description: "זמן המוקדש לתחביבים, ספורט, תרבות, מנוחה, למידה שאינה רוחנית/מקצועית ופיתוח עצמי." },
    ],
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: "VALUES",
    id: "life_priorities_future",
    category: "values",
    subcategory: "personal",
    question:
      "סדר עדיפויות רצוי בזוגיות: איך היית רוצה לחלק 100 נקודות אנרגיה/חשיבות בין תחומי החיים בזוגיות *עתידית*?",
    type: "budgetAllocation",
    depth: "ADVANCED",
    isRequired: true,
    totalPoints: 100,
    categories: [
      { label: "זוגיות ומשפחה", icon: <Home />, min: 0, max: 100, description: "זמן, אנרגיה ותשומת לב המוקדשים לבן/בת הזוג ולילדים (אם וכאשר יהיו)." },
      { label: "קריירה ועבודה (של שניכם)", icon: <Briefcase />, min: 0, max: 100, description: "השקעה בקריירה של כל אחד מבני הזוג והתמיכה ההדדית בה." },
      { label: "רוחניות ולימוד תורה", icon: <Book />, min: 0, max: 100, description: "זמן משותף ואישי המוקדש ללימוד, תפילה וחיבור רוחני." },
      { label: "קהילה, חברים והתנדבות", icon: <Users />, min: 0, max: 100, description: "מעורבות משותפת ונפרדת בחיי הקהילה, קשרים חברתיים ותרומה." },
      { label: "פנאי, תחביבים וצמיחה אישית", icon: <Star />, min: 0, max: 100, description: "זמן משותף ואישי המוקדש לתחביבים, בילויים, מנוחה והתפתחות עצמית." },
    ],
    metadata: {
      estimatedTime: 3,
      helpText: "חשוב/י על האיזון האידיאלי עבורך ועבור הזוגיות שת/ירצה לבנות.",
    },
  },
  {
    worldId: "VALUES",
    id: "economic_approach",
    category: "values",
    subcategory: "personal",
    question:
      "על סולם של 1 (פשטות והסתפקות במועט) עד 10 (שאיפה להצלחה ורווחה כלכלית), היכן היית ממקם/ת את גישתך הכלכלית?",
    type: "scale",
    depth: "BASIC",
    isRequired: true,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "economic_approach_elaboration",
    category: "values",
    subcategory: "personal",
    question: "(אופציונלי) הסבר/י בקצרה את המשמעות של הדירוג שבחרת בשאלה הקודמת לגבי גישתך הכלכלית.",
    type: "openText",
    depth: "ADVANCED",
    isRequired: false,
    minLength: 0,
    maxLength: 300,
    placeholder: "מה עומד מאחורי הדירוג? מהם השיקולים שלך בנושא כלכלי?",
    metadata: { estimatedTime: 2 },
    icon: <HelpCircle/>, // <<--- Icon at the top level
  },
  {
    worldId: "VALUES",
    id: "money_role",
    category: "values",
    subcategory: "personal",
    question: "מהו בעיניך תפקידו של כסף בחיים ובזוגיות?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: false,
    minLength: 50,
    maxLength: 400,
    placeholder: "האם הוא אמצעי להשגת מטרות, מקור לביטחון, גורם לחץ, מאפשר חוויות, כלי לנתינה?...",
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: "VALUES",
    id: "giving_importance",
    category: "values",
    subcategory: "personal",
    question: "על סולם של 1 (פחות חשוב) עד 10 (חשוב מאוד), עד כמה נתינה, צדקה וחסד מהווים חלק משמעותי בחייך?",
    type: "scale",
    depth: "BASIC",
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
    icon: <DollarSign/>, // <<--- Icon at the top level
  },
  {
    worldId: "VALUES",
    id: "personal_growth_importance",
    category: "values",
    subcategory: "personal",
    question: "על סולם של 1 (פחות חשוב) עד 10 (חשוב מאוד), עד כמה חשובה לך צמיחה והתפתחות אישית מתמדת (בתחומים שונים)?",
    type: "scale",
    depth: "BASIC",
    isRequired: true,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
    icon: <TrendingUp/>, // <<--- Icon at the top level
  },
  {
    worldId: "VALUES",
    id: "education_level_preference",
    category: "values",
    subcategory: "personal",
    question:
      "מהי רמת ההשכלה הכללית (לימודי חול) הרצויה בעיניך עבורך ועבור בן/בת זוגך?",
    type: "singleChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      { value: "not_important", text: "רמת ההשכלה הפורמלית פחות חשובה לי" },
      { value: "high_school", text: "השכלה תיכונית / מקצועית" },
      { value: "academic", text: "השכלה אקדמית (תואר ראשון ומעלה)" },
      { value: "depends", text: "תלוי באדם ובתחומי העניין שלו" },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "education_importance",
    category: "values",
    subcategory: "personal",
    question:
      "עד כמה חשובה לך השכלה פורמלית (כללית או תורנית) בהתפתחות אישית ובחיי המשפחה?",
    type: "scale",
    depth: "BASIC",
    isRequired: true,
    min: 1, // לא חשוב כלל
    max: 10, // חשוב מאוד
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "torah_learning_importance",
    category: "values",
    subcategory: "personal",
    question:
      "על סולם של 1 (פחות מרכזי) עד 10 (מרכזי מאוד), איזה מקום תופס לימוד תורה (אישי או משותף) בחייך ואיזה מקום היית רוצה שיתפוס בעתיד?",
    type: "scale",
    depth: "ADVANCED",
    isRequired: true,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "torah_learning_expression",
    category: "values",
    subcategory: "personal",
    question:
      "כיצד לימוד תורה בא לידי ביטוי בחייך כיום, או איך היית רוצה שיבוא לידי ביטוי?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: false,
    minLength: 50,
    maxLength: 400,
    placeholder:
      "לדוגמה: שיעור קבוע, דף יומי, חברותא, לימוד עצמי מספרים, דיונים על פרשת שבוע, שיעורים באינטרנט...",
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: "VALUES",
    id: "career_priorities",
    category: "values",
    subcategory: "personal",
    question: "מהם הדברים החשובים לך ביותר בקריירה או בעבודה? (בחר/י עד 3)",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: true,
    options: [
      { icon: <HandHeart />, text: "תרומה ומשמעות", value: "contribution" },
      { icon: <PiggyBank />, text: "ביטחון כלכלי ותגמול", value: "stability_reward" },
      { icon: <Award />, text: "התפתחות מקצועית והישגים", value: "achievement_growth" },
      { icon: <Scale />, text: "איזון בית-עבודה", value: "balance" },
      { icon: <Star />, text: "עניין, אתגר וגיוון", value: "interest_challenge" },
      { icon: <Users />, text: "סביבה חברתית נעימה", value: "social_environment" },
    ],
    minSelections: 1,
    maxSelections: 3,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "leisure_importance",
    category: "values",
    subcategory: "personal",
    question: "עד כמה חשוב לך לפנות זמן לפנאי, תחביבים ופעילויות תרבות?",
    type: "scale",
    depth: "BASIC",
    isRequired: false,
    min: 1, // לא חשוב
    max: 10, // חשוב מאוד
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "leisure_preferences",
    category: "values",
    subcategory: "personal",
    question: "אילו סוגי בילוי ופנאי חשוב לך שיהיו משותפים עם בן/בת הזוג? (בחר/י עד 4)",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: false,
    options: [
      { icon: <Coffee />, text: "בילויים שקטים ורגועים", value: "quiet" },
      { icon: <Globe />, text: "טיולים בטבע והרפתקאות", value: "nature_adventure" },
      { icon: <Palette />, text: "תרבות ואמנות", value: "culture_art" },
      { icon: <Music />, text: "מוזיקה והופעות", value: "music_shows" },
      { icon: <Book />, text: "למידה והעשרה משותפת", value: "learning" },
      { icon: <Users />, text: "מפגשים חברתיים ואירוח", value: "social_hosting" },
      { icon: <HandHeart />, text: "התנדבות ופעילות קהילתית", value: "volunteering" },
      { icon: <Heart />, text: "פעילויות רוחניות משותפות", value: "spiritual" },
    ],
    minSelections: 1,
    maxSelections: 4,
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: "VALUES",
    id: "modesty_meaning",
    category: "values",
    subcategory: "personal",
    question:
      "מהי המשמעות של 'צניעות' עבורך? כיצד היא באה לידי ביטוי בתחומים שונים (לבוש, דיבור, התנהלות כלכלית, התנהגות חברתית)?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: false,
    minLength: 100,
    maxLength: 600,
    placeholder: "שתף/י את תפיסתך והבנתך את המושג. למשל: בלבוש - הקפדה על כיסוי מסוים. בדיבור - הימנעות מרכילות או דיבור בוטה. בהתנהלות כלכלית - הימנעות מראוותנות. בהתנהגות חברתית - שמירה על איפוק או גבולות מסוימים...",
    metadata: { estimatedTime: 3 },
  },
  {
    worldId: "VALUES",
    id: "modesty_partner_importance",
    category: "values",
    subcategory: "personal",
    question: "עד כמה חשוב לך שבן/בת הזוג יחזיקו בתפיסת צניעות דומה לשלך?",
    type: "scale",
    depth: "ADVANCED",
    isRequired: false,
    min: 1, // לא חשוב
    max: 10, // חשוב מאוד
    metadata: { estimatedTime: 1 },
  },

  // --- ערכים קהילתיים וחברתיים ---
  {
    worldId: "VALUES",
    id: "community_importance",
    category: "values",
    subcategory: "community",
    question:
      "על סולם של 1 (לא חשוב) עד 10 (חשוב מאוד), עד כמה חשוב לך להיות חלק מקהילה תומכת ומעורבת?",
    type: "scale",
    depth: "BASIC",
    isRequired: false,
    min: 1,
    max: 10,
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "social_responsibility_partner",
    category: "values",
    subcategory: "community",
    question:
      "עד כמה חשוב לך שבן/בת הזוג יהיו שותפים לפעילויות התנדבותיות, קהילתיות או סביבתיות?",
    type: "scale",
    depth: "ADVANCED",
    isRequired: false,
    min: 1, // לא חשוב
    max: 10, // חשוב מאוד
    metadata: { estimatedTime: 1 },
  },

  // --- השקפת עולם ומדינה ---
  {
    worldId: "VALUES",
    id: "military_service_view",
    category: "values",
    subcategory: "worldview",
    question:
      "מהי גישתך האישית לשירות צבאי/לאומי או ללימוד תורה כמסלול חיים מרכזי?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      { icon: <Sword />, text: "שירות משמעותי (צבאי/לאומי)", value: "meaningful_service" },
      { icon: <Book />, text: "שילוב תורה ושירות (הסדר/שילובים)", value: "hesder_integration" },
      { icon: <LibraryBig />, text: "לימוד תורה כמרכז החיים", value: "torah_centric" },
      { icon: <Target />, text: "תרומה בדרכים אחרות", value: "other_contribution" },
      { icon: <HelpCircle />, text: "פטור / לא רלוונטי עבורי", value: "exempt_not_relevant" },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "military_service_partner_expectation",
    category: "values",
    subcategory: "worldview",
    question:
      "עד כמה חשוב לך שבן/בת הזוג יגיעו ממסלול (שירות צבאי/לאומי/לימוד תורה) דומה או תואם לשלך?",
    type: "scale",
    depth: "BASIC",
    isRequired: true,
    min: 1, // לא חשוב
    max: 10, // חשוב מאוד
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "state_religion_view",
    category: "values",
    subcategory: "worldview",
    question: "מהי גישתך האידיאלית ליחס בין דת ומדינה בישראל?",
    type: "iconChoice",
    depth: "ADVANCED",
    isRequired: true,
    options: [
      { icon: <Flag />, text: "הפרדה מלאה בין דת למדינה", value: "separation" },
      { icon: <Scale />, text: "סטטוס קוו (שמירה על האיזון הקיים)", value: "status_quo" },
      { icon: <Church />, text: "מדינה יהודית-דמוקרטית (עם צביון יהודי בולט)", value: "jewish_democratic" },
      { icon: <ScrollText />, text: "מדינת הלכה (החלת ההלכה במרחב הציבורי)", value: "halacha_state" },
      { icon: <HelpCircle />, text: "גישה אחרת / מורכבת", value: "other_complex" },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "state_religion_partner_importance",
    category: "values",
    subcategory: "worldview",
    question:
      "עד כמה חשוב לך שבן/בת הזוג יחזיקו בהשקפה דומה לשלך בנושא דת ומדינה?",
    type: "scale",
    depth: "ADVANCED",
    isRequired: false,
    min: 1, // לא חשוב
    max: 10, // חשוב מאוד
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "shabbat_public_space_view",
    category: "values",
    subcategory: "worldview",
    question:
      "איך לדעתך צריך להיראות המרחב הציבורי (תחבורה, מסחר, בילוי) בשבת?",
    type: "iconChoice",
    depth: "ADVANCED",
    isRequired: true,
    options: [
      { icon: <ScrollText />, text: "שמירה מלאה על קדושת השבת (ללא חילול שבת פומבי)", value: "full_observance" },
      { icon: <Scale />, text: "שמירה חלקית עם התחשבות הדדית ומתן אפשרויות מסוימות", value: "partial_observance" },
      { icon: <Map />, text: "הסדרה מקומית לפי אופי האזור/העיר", value: "local_decision" },
      { icon: <Star />, text: "חופש פעילות מלא לכל אדם", value: "full_freedom" },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "shabbat_home_vision",
    category: "values",
    subcategory: "worldview",
    question: "איך היית רוצה שהשבת תיראה בביתכם המשותף?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: false,
    minLength: 50,
    maxLength: 500,
    placeholder: "תאר/י את האווירה (רוגע, חברה), הפעילויות (תפילה, לימוד, טיול, משחקים), ורמת ההקפדה ההלכתית הרצויה...",
    metadata: { estimatedTime: 2 },
  },

  // --- גישות נוספות ---
  {
    worldId: "VALUES",
    id: "technology_integration_view",
    category: "values",
    subcategory: "approach",
    question:
      "מהי גישתך לשילוב טכנולוגיה (סמארטפונים, אינטרנט, רשתות חברתיות) בחיי היומיום ובחינוך הילדים?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: false,
    options: [
      { icon: <Laptop />, text: "אימוץ פתוח ושימוש חופשי", value: "open_adoption" },
      { icon: <Scale />, text: "שימוש מבוקר ומאוזן עם גבולות", value: "controlled_use" },
      { icon: <ShieldCheck />, text: "סינון והגנה קפדניים", value: "filtered_protected" },
      { icon: <Target />, text: "צמצום השימוש למינימום ההכרחי", value: "minimal_necessary" },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "technology_role_home",
    category: "values",
    subcategory: "approach",
    question:
      "איזה תפקיד היית רוצה שלטכנולוגיה יהיה בבית המשותף ובגידול הילדים?",
    type: "openText",
    depth: "ADVANCED",
    isRequired: false,
    minLength: 50,
    maxLength: 400,
    placeholder: "האם היא כלי עזר ללמידה ותקשורת, מקור בידור, גורם שיש להגביל את השימוש בו, מקור למתח פוטנציאלי?...",
    metadata: { estimatedTime: 2 },
  },
  {
    worldId: "VALUES",
    id: "medical_approach",
    category: "values",
    subcategory: "approach",
    question: "מהי גישתך לרפואה ובריאות?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: false,
    options: [
      { icon: <Building />, text: "רפואה קונבנציונלית מערבית", value: "conventional" },
      { icon: <Leaf />, text: "פתיחות לרפואה משלימה / אלטרנטיבית", value: "alternative" },
      { icon: <Scale />, text: "גישה משולבת (אינטגרטיבית)", value: "integrated" },
      { icon: <Brain />, text: "מחקר אישי ולקיחת אחריות", value: "research_personal" },
    ],
    metadata: { estimatedTime: 1 },
  },
  {
    worldId: "VALUES",
    id: "environmental_approach",
    category: "values",
    subcategory: "approach",
    question: "מהי גישתך לשמירה על איכות הסביבה וקיימות?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: false,
    options: [
      { icon: <TreePine />, text: "חשוב מאוד, אורח חיים אקולוגי", value: "very_important_active" },
      { icon: <Leaf />, text: "חשוב, מודעות ושמירה בסיסית", value: "important_aware" },
      { icon: <Scale />, text: "מאזן/ת בין נוחות לסביבה", value: "balanced_practical" },
      { icon: <Target />, text: "פחות בראש סדר העדיפויות", value: "lower_priority" },
    ],
    metadata: { estimatedTime: 1 },
  },
];

export default valuesQuestions;