import { Question } from "../../types/types";
import {
  Scale,
  Heart,
  Users,
  Briefcase,
  Book,
  Globe,
  Target,
  Map,
  Leaf,
  Building,
  Gem,
  ScrollText,
  Sparkles,
  Construction,
  ShieldCheck,
  GraduationCap,
  Sword,
  Brain,
  Laptop,
  HandHeart,
  School,
  LibraryBig,
} from "lucide-react";

export const valuesQuestionsPartOne: Question[] = [
  {
    worldId: "VALUES",
    id: "military_service",
    category: "values",
    subcategory: "basics",
    question: "מהי הגישה שלך לשירות צבאי?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Sword />,
        text: "שירות קרבי מלא",
        value: "combat",
        description: "מאמין בתרומה משמעותית דרך שירות קרבי",
      },
      {
        icon: <Book />,
        text: " שילוב תורה עם צבא - הסדר",
        value: "hesder",
        description: "משלב בין לימוד תורה לשירות צבאי",
      },
      {
        icon: <LibraryBig />,
        text: "לימוד תורה",
        value: "torah",
        description: "מתמקד בלימוד תורה כדרך חיים",
      },
      {
        icon: <Laptop />,
        text: "תרומה משמעותית בכל דרך שהיא ",
        value: "tech",
        description: "תורם גם דרך יכולות טכנולוגיות ומקצועיות",
      },
    ],
  },
  {
    worldId: "VALUES",
    id: "economic_worldview",
    category: "values",
    subcategory: "basics",
    question: "מהי תפיסת העולם הכלכלית שלך?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <Gem />,
        text: "שאיפה להצלחה",
        value: "success",
        description: "מאמין בחשיבות ההצלחה הכלכלית",
      },
      {
        icon: <Scale />,
        text: "איזון והסתפקות",
        value: "balance",
        description: "מחפש איזון בין רווחה לערכים",
      },
      {
        icon: <Leaf />,
        text: "פשטות",
        value: "simplicity",
        description: "מעדיף חיים פשוטים וצנועים",
      },
      {
        icon: <Target />,
        text: "יעדים מדודים",
        value: "goals",
        description: " לפי צורך המשפחה - מציב ומשיג יעדים כלכליים מתוכננים",
      },
    ],
  },
  {
    worldId: "VALUES",
    id: "education_approach",
    category: "values",
    subcategory: "basics",
    question: "מהי גישתך ללימודי חול?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <School />,
        text: "לימודי ליבה מלאים",
        value: "full_core",
        description: "תומך בשילוב מלא של לימודי ליבה",
      },
      {
        icon: <Scale />,
        text: "שילוב מאוזן",
        value: "balanced",
        description: "משלב לימודי קודש וחול באופן מאוזן",
      },
      {
        icon: <Book />,
        text: "התמקדות בקודש",
        value: "torah_focus",
        description: "מעדיף להתמקד בלימודי קודש",
      },
      {
        icon: <Brain />,
        text: "למידה לפי צורך",
        value: "as_needed",
        description: "רוכש השכלה בהתאם לצרכים המעשיים",
      },
    ],
  },
  {
    worldId: "VALUES",
    id: "medical_approach",
    category: "values",
    subcategory: "basics",
    question: "מהי גישתך לרפואה ובריאות?",
    type: "iconChoice",
    depth: "BASIC",
    isRequired: false,
    options: [
      {
        icon: <Building />,
        text: "רפואה קונבנציונלית",
        value: "conventional",
        description: "מאמין ברפואה המערבית המסורתית",
      },
      {
        icon: <Leaf />,
        text: "רפואה משלימה",
        value: "alternative",
        description: "פתוח לשיטות ריפוי טבעיות",
      },
      {
        icon: <Scale />,
        text: "גישה משולבת",
        value: "integrated",
        description: "משלב בין שיטות טיפול שונות",
      },
      {
        icon: <Brain />,
        text: "מחקר עצמאי",
        value: "research",
        description: "חוקר ולומד לפני קבלת החלטות",
      },
    ],
  },
  {
    worldId: "VALUES",
    id: "career_priorities",
    category: "values",
    subcategory: "basics",
    question: "מה חשוב לך בקריירה?",
    type: "multiSelect",
    depth: "BASIC",
    isRequired: true,
    options: [
      {
        icon: <HandHeart />,
        text: "תרומה לחברה",
        value: "contribution",
        description: "עבודה שמשפיעה על החברה",
      },
      {
        icon: <Briefcase />,
        text: "יציבות כלכלית",
        value: "stability",
        description: "ביטחון תעסוקתי והכנסה יציבה",
      },
      {
        icon: <Target />,
        text: "הישגיות",
        value: "achievement",
        description: "התפתחות מקצועית והצלחה",
      },
      {
        icon: <Scale />,
        text: "איזון",
        value: "balance",
        description: "איזון בין קריירה לחיים אישיים",
      },
    ],
    minSelections: 1,
    maxSelections: 2,
  },
];

export default valuesQuestionsPartOne;
