import type { SFSection, SFQuestion } from './types';

// ========== ANCHOR QUESTIONS ==========
export const ANCHOR_QUESTIONS: SFQuestion[] = [
  {
    id: 'anchor_sector',
    type: 'singleChoice',
    textKey: 'questions.anchor_sector.text',
    subtitleKey: 'questions.anchor_sector.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    required: true,
    options: [
      { value: 'charedi_litvish', labelKey: 'options.anchor_sector.charedi_litvish', subtitleKey: 'options.anchor_sector.charedi_litvish_sub', icon: '🕍' },
      { value: 'charedi_hasidic', labelKey: 'options.anchor_sector.charedi_hasidic', subtitleKey: 'options.anchor_sector.charedi_hasidic_sub', icon: '🕍' },
      { value: 'charedi_sephardi', labelKey: 'options.anchor_sector.charedi_sephardi', subtitleKey: 'options.anchor_sector.charedi_sephardi_sub', icon: '🕍' },
      { value: 'charedi_modern', labelKey: 'options.anchor_sector.charedi_modern', subtitleKey: 'options.anchor_sector.charedi_modern_sub', icon: '🕍' },
      { value: 'hardal', labelKey: 'options.anchor_sector.hardal', subtitleKey: 'options.anchor_sector.hardal_sub', icon: '🏔️' },
      { value: 'dati_leumi_torani', labelKey: 'options.anchor_sector.dati_leumi_torani', subtitleKey: 'options.anchor_sector.dati_leumi_torani_sub', icon: '🏔️' },
      { value: 'dati_leumi_classic', labelKey: 'options.anchor_sector.dati_leumi_classic', subtitleKey: 'options.anchor_sector.dati_leumi_classic_sub', icon: '🏔️' },
      { value: 'dati_leumi_modern', labelKey: 'options.anchor_sector.dati_leumi_modern', subtitleKey: 'options.anchor_sector.dati_leumi_modern_sub', icon: '🏔️' },
      { value: 'dati_lite', labelKey: 'options.anchor_sector.dati_lite', subtitleKey: 'options.anchor_sector.dati_lite_sub', icon: '🕯️' },
      { value: 'datlash', labelKey: 'options.anchor_sector.datlash', subtitleKey: 'options.anchor_sector.datlash_sub', icon: '🕯️' },
      { value: 'chozer_bteshuva', labelKey: 'options.anchor_sector.chozer_bteshuva', subtitleKey: 'options.anchor_sector.chozer_bteshuva_sub', icon: '🔍' },
      { value: 'masorti_strong', labelKey: 'options.anchor_sector.masorti_strong', subtitleKey: 'options.anchor_sector.masorti_strong_sub', icon: '🕯️' },
      { value: 'masorti_medium', labelKey: 'options.anchor_sector.masorti_medium', subtitleKey: 'options.anchor_sector.masorti_medium_sub', icon: '🕯️' },
      { value: 'masorti_light', labelKey: 'options.anchor_sector.masorti_light', subtitleKey: 'options.anchor_sector.masorti_light_sub', icon: '🕯️' },
      { value: 'hiloni_jewish', labelKey: 'options.anchor_sector.hiloni_jewish', subtitleKey: 'options.anchor_sector.hiloni_jewish_sub', icon: '✡️' },
      { value: 'hiloni_cultural', labelKey: 'options.anchor_sector.hiloni_cultural', subtitleKey: 'options.anchor_sector.hiloni_cultural_sub', icon: '✡️' },
      { value: 'hiloni', labelKey: 'options.anchor_sector.hiloni', subtitleKey: 'options.anchor_sector.hiloni_sub', icon: '✡️' },
      { value: 'in_process', labelKey: 'options.anchor_sector.in_process', subtitleKey: 'options.anchor_sector.in_process_sub', icon: '🔍' },
      { value: 'diaspora', labelKey: 'options.anchor_sector.diaspora', subtitleKey: 'options.anchor_sector.diaspora_sub', icon: '🌍' },
      { value: 'other', labelKey: 'options.anchor_sector.other', icon: '➕', isCustomInput: true },
    ],
  },
  {
    id: 'anchor_sector_hasidic',
    type: 'singleChoice',
    textKey: 'questions.anchor_sector_hasidic.text',
    subtitleKey: 'questions.anchor_sector_hasidic.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectors: ['charedi_hasidic'] },
    options: [
      { value: 'ger', labelKey: 'options.anchor_sector_hasidic.ger' },
      { value: 'belz', labelKey: 'options.anchor_sector_hasidic.belz' },
      { value: 'vizhnitz', labelKey: 'options.anchor_sector_hasidic.vizhnitz' },
      { value: 'chabad', labelKey: 'options.anchor_sector_hasidic.chabad', subtitleKey: 'options.anchor_sector_hasidic.chabad_sub' },
      { value: 'breslov', labelKey: 'options.anchor_sector_hasidic.breslov', subtitleKey: 'options.anchor_sector_hasidic.breslov_sub' },
      { value: 'satmar', labelKey: 'options.anchor_sector_hasidic.satmar' },
      { value: 'skvere', labelKey: 'options.anchor_sector_hasidic.skvere' },
      { value: 'boyan', labelKey: 'options.anchor_sector_hasidic.boyan' },
      { value: 'karlin', labelKey: 'options.anchor_sector_hasidic.karlin' },
      { value: 'slonim', labelKey: 'options.anchor_sector_hasidic.slonim' },
      { value: 'toldos_aharon', labelKey: 'options.anchor_sector_hasidic.toldos_aharon' },
      { value: 'other_hasidic', labelKey: 'options.anchor_sector_hasidic.other_hasidic', isCustomInput: true },
    ],
  },
  {
    id: 'anchor_sector_diaspora',
    type: 'singleChoice',
    textKey: 'questions.anchor_sector_diaspora.text',
    subtitleKey: 'questions.anchor_sector_diaspora.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectors: ['diaspora'] },
    options: [
      { value: 'mo_yeshivish', labelKey: 'options.anchor_sector_diaspora.mo_yeshivish' },
      { value: 'yu_graduate', labelKey: 'options.anchor_sector_diaspora.yu_graduate' },
      { value: 'ivy_league_jewish', labelKey: 'options.anchor_sector_diaspora.ivy_league_jewish' },
      { value: 'conservative', labelKey: 'options.anchor_sector_diaspora.conservative' },
      { value: 'reform', labelKey: 'options.anchor_sector_diaspora.reform' },
      { value: 'chabad_diaspora', labelKey: 'options.anchor_sector_diaspora.chabad_diaspora' },
      { value: 'french_jewish', labelKey: 'options.anchor_sector_diaspora.french_jewish' },
      { value: 'sephardi_diaspora', labelKey: 'options.anchor_sector_diaspora.sephardi_diaspora' },
      { value: 'uk_jewish', labelKey: 'options.anchor_sector_diaspora.uk_jewish' },
      { value: 'aus_jewish', labelKey: 'options.anchor_sector_diaspora.aus_jewish' },
      { value: 'arg_jewish', labelKey: 'options.anchor_sector_diaspora.arg_jewish' },
      { value: 'russian_jewish', labelKey: 'options.anchor_sector_diaspora.russian_jewish' },
      { value: 'other_diaspora', labelKey: 'options.anchor_sector_diaspora.other_diaspora', isCustomInput: true },
    ],
  },
  {
    id: 'anchor_life_stage',
    type: 'singleChoice',
    textKey: 'questions.anchor_life_stage.text',
    subtitleKey: 'questions.anchor_life_stage.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    required: true,
    options: [
      { value: 'first_marriage', labelKey: 'options.anchor_life_stage.first_marriage', icon: '💍' },
      { value: 'divorced_no_children', labelKey: 'options.anchor_life_stage.divorced_no_children', icon: '🔄' },
      { value: 'divorced_with_children', labelKey: 'options.anchor_life_stage.divorced_with_children', icon: '👨‍👧' },
      { value: 'widowed', labelKey: 'options.anchor_life_stage.widowed', icon: '🕊️' },
      { value: 'returning', labelKey: 'options.anchor_life_stage.returning', icon: '🔄' },
    ],
  },
];

// ========== IDENTITY QUESTIONS (Section 1) ==========
export const IDENTITY_QUESTIONS: SFQuestion[] = [
  {
    id: 's1_charedi_study_work',
    type: 'singleChoice',
    textKey: 'questions.s1_charedi_study_work.text',
    subtitleKey: 'questions.s1_charedi_study_work.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectorGroups: ['charedi'], genders: ['MALE'] },
    options: [
      { value: 'full_kollel', labelKey: 'options.s1_charedi_study_work.full_kollel' },
      { value: 'kollel_part', labelKey: 'options.s1_charedi_study_work.kollel_part' },
      { value: 'works_learns', labelKey: 'options.s1_charedi_study_work.works_learns' },
      { value: 'works_only', labelKey: 'options.s1_charedi_study_work.works_only' },
      { value: 'studying_yeshiva', labelKey: 'options.s1_charedi_study_work.studying_yeshiva' },
    ],
  },
  {
    id: 's1_charedi_study_work_f',
    type: 'singleChoice',
    textKey: 'questions.s1_charedi_study_work_f.text',
    subtitleKey: 'questions.s1_charedi_study_work_f.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectorGroups: ['charedi'], genders: ['FEMALE'] },
    options: [
      { value: 'homemaker', labelKey: 'options.s1_charedi_study_work_f.homemaker' },
      { value: 'homemaker_part', labelKey: 'options.s1_charedi_study_work_f.homemaker_part' },
      { value: 'working_full', labelKey: 'options.s1_charedi_study_work_f.working_full' },
      { value: 'studying', labelKey: 'options.s1_charedi_study_work_f.studying' },
      { value: 'working_studying', labelKey: 'options.s1_charedi_study_work_f.working_studying' },
    ],
  },
  {
    id: 's1_charedi_military',
    type: 'singleChoice',
    textKey: 'questions.s1_charedi_military.text',
    subtitleKey: 'questions.s1_charedi_military.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    isOptional: true,
    conditions: { sectorGroups: ['charedi'], genders: ['MALE'] },
    options: [
      { value: 'nachal_charedi', labelKey: 'options.s1_charedi_military.nachal_charedi' },
      { value: 'other_unit', labelKey: 'options.s1_charedi_military.other_unit' },
      { value: 'did_not_serve', labelKey: 'options.s1_charedi_military.did_not_serve' },
      { value: 'exempt', labelKey: 'options.s1_charedi_military.exempt' },
    ],
  },
  {
    id: 's1_dl_army_type',
    type: 'singleChoice',
    textKey: 'questions.s1_dl_army_type.text',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectorGroups: ['dati_leumi'], genders: ['MALE'] },
    options: [
      { value: 'combat_full', labelKey: 'options.s1_dl_army_type.combat_full' },
      { value: 'non_combat', labelKey: 'options.s1_dl_army_type.non_combat' },
      { value: 'hesder', labelKey: 'options.s1_dl_army_type.hesder' },
      { value: 'yeshiva_only', labelKey: 'options.s1_dl_army_type.yeshiva_only' },
      { value: 'kav', labelKey: 'options.s1_dl_army_type.kav' },
      { value: 'exempt_medical', labelKey: 'options.s1_dl_army_type.exempt_medical' },
      { value: 'exempt_other', labelKey: 'options.s1_dl_army_type.exempt_other' },
      { value: 'currently_serving', labelKey: 'options.s1_dl_army_type.currently_serving' },
    ],
  },
  {
    id: 's1_dl_service_f',
    type: 'singleChoice',
    textKey: 'questions.s1_dl_service_f.text',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectorGroups: ['dati_leumi'], genders: ['FEMALE'] },
    options: [
      { value: 'national_service', labelKey: 'options.s1_dl_service_f.national_service' },
      { value: 'midrasha', labelKey: 'options.s1_dl_service_f.midrasha' },
      { value: 'seminary', labelKey: 'options.s1_dl_service_f.seminary' },
      { value: 'army', labelKey: 'options.s1_dl_service_f.army' },
      { value: 'directly_academic', labelKey: 'options.s1_dl_service_f.directly_academic' },
      { value: 'gap_year_abroad', labelKey: 'options.s1_dl_service_f.gap_year_abroad' },
      { value: 'other_service', labelKey: 'options.s1_dl_service_f.other_service' },
    ],
  },
  {
    id: 's1_dl_yeshiva_type',
    type: 'singleChoice',
    textKey: 'questions.s1_dl_yeshiva_type.text',
    subtitleKey: 'questions.s1_dl_yeshiva_type.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectorGroups: ['dati_leumi'], genders: ['MALE'] },
    options: [
      { value: 'hesder_yeshiva', labelKey: 'options.s1_dl_yeshiva_type.hesder_yeshiva', subtitleKey: 'options.s1_dl_yeshiva_type.hesder_sub' },
      { value: 'kav_yeshiva', labelKey: 'options.s1_dl_yeshiva_type.kav_yeshiva', subtitleKey: 'options.s1_dl_yeshiva_type.kav_sub' },
      { value: 'big_yeshiva', labelKey: 'options.s1_dl_yeshiva_type.big_yeshiva', subtitleKey: 'options.s1_dl_yeshiva_type.big_sub' },
      { value: 'yeshiva_high', labelKey: 'options.s1_dl_yeshiva_type.yeshiva_high' },
      { value: 'no_yeshiva', labelKey: 'options.s1_dl_yeshiva_type.no_yeshiva' },
    ],
  },
  {
    id: 's1_dl_yeshiva_specific',
    type: 'multiSelect',
    textKey: 'questions.s1_dl_yeshiva_specific.text',
    subtitleKey: 'questions.s1_dl_yeshiva_specific.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    isOptional: true,
    allowCustom: true,
    maxSelections: 2,
    conditions: {
      sectorGroups: ['dati_leumi'],
      genders: ['MALE'],
      requiredAnswers: [{ questionId: 's1_dl_yeshiva_type', values: ['hesder_yeshiva', 'kav_yeshiva', 'big_yeshiva'] }],
    },
    options: [
      { value: 'har_etzion', labelKey: 'options.s1_dl_yeshiva_specific.har_etzion' },
      { value: 'shaalvim', labelKey: 'options.s1_dl_yeshiva_specific.shaalvim' },
      { value: 'kerem_byavne', labelKey: 'options.s1_dl_yeshiva_specific.kerem_byavne' },
      { value: 'har_amiel', labelKey: 'options.s1_dl_yeshiva_specific.har_amiel' },
      { value: 'eli', labelKey: 'options.s1_dl_yeshiva_specific.eli' },
      { value: 'siach', labelKey: 'options.s1_dl_yeshiva_specific.siach' },
      { value: 'merkaz_harav', labelKey: 'options.s1_dl_yeshiva_specific.merkaz_harav' },
      { value: 'otniel', labelKey: 'options.s1_dl_yeshiva_specific.otniel' },
      { value: 'maale_gilboa', labelKey: 'options.s1_dl_yeshiva_specific.maale_gilboa' },
      { value: 'beit_el', labelKey: 'options.s1_dl_yeshiva_specific.beit_el' },
      { value: 'netivot_moshe', labelKey: 'options.s1_dl_yeshiva_specific.netivot_moshe' },
      { value: 'other_yeshiva', labelKey: 'options.s1_dl_yeshiva_specific.other_yeshiva', isCustomInput: true },
    ],
  },
  {
    id: 's1_dl_zionism',
    type: 'singleChoice',
    textKey: 'questions.s1_dl_zionism.text',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectorGroups: ['dati_leumi'] },
    options: [
      { value: 'strong_zionist', labelKey: 'options.s1_dl_zionism.strong_zionist' },
      { value: 'classic_zionist', labelKey: 'options.s1_dl_zionism.classic_zionist' },
      { value: 'pragmatic_zionist', labelKey: 'options.s1_dl_zionism.pragmatic_zionist' },
      { value: 'indifferent', labelKey: 'options.s1_dl_zionism.indifferent' },
      { value: 'post_zionist', labelKey: 'options.s1_dl_zionism.post_zionist' },
      { value: 'eretz_israel_focus', labelKey: 'options.s1_dl_zionism.eretz_israel_focus' },
    ],
  },
  {
    id: 's1_shomer_negiah',
    type: 'singleChoice',
    textKey: 'questions.s1_shomer_negiah.text',
    subtitleKey: 'questions.s1_shomer_negiah.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: true,
    conditions: { sectorGroups: ['charedi', 'dati_leumi', 'masorti', 'chozer_bteshuva'] },
    options: [
      { value: 'fully_shomer', labelKey: 'options.s1_shomer_negiah.fully_shomer' },
      { value: 'mostly_shomer', labelKey: 'options.s1_shomer_negiah.mostly_shomer' },
      { value: 'not_shomer_open', labelKey: 'options.s1_shomer_negiah.not_shomer_open' },
      { value: 'not_shomer_prefer', labelKey: 'options.s1_shomer_negiah.not_shomer_prefer' },
      { value: 'not_relevant', labelKey: 'options.s1_shomer_negiah.not_relevant' },
    ],
  },
  {
    id: 's1_masorti_practices',
    type: 'multiSelect',
    textKey: 'questions.s1_masorti_practices.text',
    subtitleKey: 'questions.s1_masorti_practices.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    maxSelections: 8,
    conditions: { sectorGroups: ['masorti'] },
    options: [
      { value: 'shabbat', labelKey: 'options.s1_masorti_practices.shabbat' },
      { value: 'kashrut', labelKey: 'options.s1_masorti_practices.kashrut' },
      { value: 'holidays', labelKey: 'options.s1_masorti_practices.holidays' },
      { value: 'yom_kippur', labelKey: 'options.s1_masorti_practices.yom_kippur' },
      { value: 'brit_bar', labelKey: 'options.s1_masorti_practices.brit_bar' },
      { value: 'prayer', labelKey: 'options.s1_masorti_practices.prayer' },
      { value: 'jewish_education', labelKey: 'options.s1_masorti_practices.jewish_education' },
      { value: 'nothing_formal', labelKey: 'options.s1_masorti_practices.nothing_formal' },
    ],
  },
  {
    id: 's1_hiloni_jewish_identity',
    type: 'multiSelect',
    textKey: 'questions.s1_hiloni_jewish_identity.text',
    subtitleKey: 'questions.s1_hiloni_jewish_identity.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    maxSelections: 3,
    conditions: { sectorGroups: ['hiloni'] },
    options: [
      { value: 'national_pride', labelKey: 'options.s1_hiloni_jewish_identity.national_pride' },
      { value: 'israeli', labelKey: 'options.s1_hiloni_jewish_identity.israeli' },
      { value: 'culture_literature', labelKey: 'options.s1_hiloni_jewish_identity.culture_literature' },
      { value: 'history_holocaust', labelKey: 'options.s1_hiloni_jewish_identity.history_holocaust' },
      { value: 'tikkun_olam', labelKey: 'options.s1_hiloni_jewish_identity.tikkun_olam' },
      { value: 'family_tradition', labelKey: 'options.s1_hiloni_jewish_identity.family_tradition' },
      { value: 'not_defined', labelKey: 'options.s1_hiloni_jewish_identity.not_defined' },
    ],
  },
  {
    id: 's1_bt_path',
    type: 'singleChoice',
    textKey: 'questions.s1_bt_path.text',
    subtitleKey: 'questions.s1_bt_path.subtitle',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectors: ['chozer_bteshuva'] },
    options: [
      { value: 'gradual', labelKey: 'options.s1_bt_path.gradual' },
      { value: 'encounter', labelKey: 'options.s1_bt_path.encounter' },
      { value: 'study', labelKey: 'options.s1_bt_path.study' },
      { value: 'life_event', labelKey: 'options.s1_bt_path.life_event' },
      { value: 'community', labelKey: 'options.s1_bt_path.community' },
      { value: 'army', labelKey: 'options.s1_bt_path.army' },
      { value: 'family', labelKey: 'options.s1_bt_path.family' },
      { value: 'other_path', labelKey: 'options.s1_bt_path.other_path' },
    ],
  },
  {
    id: 's1_bt_time',
    type: 'singleChoice',
    textKey: 'questions.s1_bt_time.text',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectors: ['chozer_bteshuva'] },
    options: [
      { value: 'less_1', labelKey: 'options.s1_bt_time.less_1' },
      { value: '1_3', labelKey: 'options.s1_bt_time.1_3' },
      { value: '3_7', labelKey: 'options.s1_bt_time.3_7' },
      { value: 'more_7', labelKey: 'options.s1_bt_time.more_7' },
    ],
  },
  {
    id: 's1_diaspora_community',
    type: 'singleChoice',
    textKey: 'questions.s1_diaspora_community.text',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectors: ['diaspora'] },
    options: [
      { value: 'orthodox_mo', labelKey: 'options.s1_diaspora_community.orthodox_mo' },
      { value: 'yu_graduate', labelKey: 'options.s1_diaspora_community.yu_graduate' },
      { value: 'ivy_league', labelKey: 'options.s1_diaspora_community.ivy_league' },
      { value: 'conservative_member', labelKey: 'options.s1_diaspora_community.conservative_member' },
      { value: 'reform_member', labelKey: 'options.s1_diaspora_community.reform_member' },
      { value: 'chabad_member', labelKey: 'options.s1_diaspora_community.chabad_member' },
      { value: 'french_community', labelKey: 'options.s1_diaspora_community.french_community' },
      { value: 'sephardi_diaspora_comm', labelKey: 'options.s1_diaspora_community.sephardi_diaspora_comm' },
      { value: 'other_community', labelKey: 'options.s1_diaspora_community.other_community', isCustomInput: true },
    ],
  },
  {
    id: 's1_diaspora_education',
    type: 'singleChoice',
    textKey: 'questions.s1_diaspora_education.text',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectors: ['diaspora'] },
    options: [
      { value: 'ivy_league_edu', labelKey: 'options.s1_diaspora_education.ivy_league_edu' },
      { value: 'top_university', labelKey: 'options.s1_diaspora_education.top_university' },
      { value: 'state_university', labelKey: 'options.s1_diaspora_education.state_university' },
      { value: 'jewish_university', labelKey: 'options.s1_diaspora_education.jewish_university' },
      { value: 'seminary_abroad', labelKey: 'options.s1_diaspora_education.seminary_abroad' },
      { value: 'vocational', labelKey: 'options.s1_diaspora_education.vocational' },
      { value: 'high_school_only', labelKey: 'options.s1_diaspora_education.high_school_only' },
      { value: 'other_education', labelKey: 'options.s1_diaspora_education.other_education' },
    ],
  },
  {
    id: 's1_diaspora_aliyah',
    type: 'singleChoice',
    textKey: 'questions.s1_diaspora_aliyah.text',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: { sectors: ['diaspora'] },
    options: [
      { value: 'planning_soon', labelKey: 'options.s1_diaspora_aliyah.planning_soon' },
      { value: 'considering', labelKey: 'options.s1_diaspora_aliyah.considering' },
      { value: 'open_if_right', labelKey: 'options.s1_diaspora_aliyah.open_if_right' },
      { value: 'not_planning', labelKey: 'options.s1_diaspora_aliyah.not_planning' },
      { value: 'already_made_aliyah', labelKey: 'options.s1_diaspora_aliyah.already_made_aliyah' },
    ],
  },
  {
    id: 's1_diaspora_aliyah_timeline',
    type: 'singleChoice',
    textKey: 'questions.s1_diaspora_aliyah_timeline.text',
    category: 'sector',
    forSelf: true,
    forPartner: false,
    conditions: {
      sectors: ['diaspora'],
      requiredAnswers: [{ questionId: 's1_diaspora_aliyah', values: ['planning_soon', 'considering'] }],
    },
    options: [
      { value: 'within_year', labelKey: 'options.s1_diaspora_aliyah_timeline.within_year' },
      { value: '1_3_years', labelKey: 'options.s1_diaspora_aliyah_timeline.1_3_years' },
      { value: '3_5_years', labelKey: 'options.s1_diaspora_aliyah_timeline.3_5_years' },
      { value: 'undecided', labelKey: 'options.s1_diaspora_aliyah_timeline.undecided' },
    ],
  },
];

// ========== IDENTITY PARTNER QUESTIONS ==========
export const IDENTITY_PARTNER_QUESTIONS: SFQuestion[] = [
  {
    id: 'p_sector_preference',
    type: 'multiSelect',
    textKey: 'questions.p_sector_preference.text',
    subtitleKey: 'questions.p_sector_preference.subtitle',
    category: 'sector',
    forSelf: false,
    forPartner: true,
    maxSelections: 5,
    options: [
      { value: 'charedi_litvish', labelKey: 'options.anchor_sector.charedi_litvish', icon: '🕍' },
      { value: 'charedi_hasidic', labelKey: 'options.anchor_sector.charedi_hasidic', icon: '🕍' },
      { value: 'charedi_sephardi', labelKey: 'options.anchor_sector.charedi_sephardi', icon: '🕍' },
      { value: 'charedi_modern', labelKey: 'options.anchor_sector.charedi_modern', icon: '🕍' },
      { value: 'hardal', labelKey: 'options.anchor_sector.hardal', icon: '🏔️' },
      { value: 'dati_leumi_torani', labelKey: 'options.anchor_sector.dati_leumi_torani', icon: '🏔️' },
      { value: 'dati_leumi_classic', labelKey: 'options.anchor_sector.dati_leumi_classic', icon: '🏔️' },
      { value: 'dati_leumi_modern', labelKey: 'options.anchor_sector.dati_leumi_modern', icon: '🏔️' },
      { value: 'dati_lite', labelKey: 'options.anchor_sector.dati_lite', icon: '🕯️' },
      { value: 'chozer_bteshuva', labelKey: 'options.anchor_sector.chozer_bteshuva', icon: '🔍' },
      { value: 'masorti_strong', labelKey: 'options.anchor_sector.masorti_strong', icon: '🕯️' },
      { value: 'masorti_medium', labelKey: 'options.anchor_sector.masorti_medium', icon: '🕯️' },
      { value: 'masorti_light', labelKey: 'options.anchor_sector.masorti_light', icon: '🕯️' },
      { value: 'hiloni_jewish', labelKey: 'options.anchor_sector.hiloni_jewish', icon: '✡️' },
      { value: 'hiloni_cultural', labelKey: 'options.anchor_sector.hiloni_cultural', icon: '✡️' },
      { value: 'hiloni', labelKey: 'options.anchor_sector.hiloni', icon: '✡️' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  {
    id: 'p_zionism_preference',
    type: 'singleChoice',
    textKey: 'questions.p_zionism_preference.text',
    category: 'sector',
    forSelf: false,
    forPartner: true,
    conditions: { sectorGroups: ['dati_leumi'] },
    options: [
      { value: 'strong_zionist', labelKey: 'options.s1_dl_zionism.strong_zionist' },
      { value: 'classic_zionist', labelKey: 'options.s1_dl_zionism.classic_zionist' },
      { value: 'pragmatic_zionist', labelKey: 'options.s1_dl_zionism.pragmatic_zionist' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  {
    id: 'p_masorti_practices',
    type: 'multiSelect',
    textKey: 'questions.p_masorti_practices.text',
    category: 'sector',
    forSelf: false,
    forPartner: true,
    maxSelections: 8,
    conditions: { sectorGroups: ['masorti'] },
    options: [
      { value: 'shabbat', labelKey: 'options.s1_masorti_practices.shabbat' },
      { value: 'kashrut', labelKey: 'options.s1_masorti_practices.kashrut' },
      { value: 'holidays', labelKey: 'options.s1_masorti_practices.holidays' },
      { value: 'yom_kippur', labelKey: 'options.s1_masorti_practices.yom_kippur' },
      { value: 'prayer', labelKey: 'options.s1_masorti_practices.prayer' },
      { value: 'jewish_education', labelKey: 'options.s1_masorti_practices.jewish_education' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  {
    id: 'p_hiloni_identity',
    type: 'multiSelect',
    textKey: 'questions.p_hiloni_identity.text',
    category: 'sector',
    forSelf: false,
    forPartner: true,
    maxSelections: 3,
    conditions: { sectorGroups: ['hiloni'] },
    options: [
      { value: 'national_pride', labelKey: 'options.s1_hiloni_jewish_identity.national_pride' },
      { value: 'israeli', labelKey: 'options.s1_hiloni_jewish_identity.israeli' },
      { value: 'culture_literature', labelKey: 'options.s1_hiloni_jewish_identity.culture_literature' },
      { value: 'tikkun_olam', labelKey: 'options.s1_hiloni_jewish_identity.tikkun_olam' },
      { value: 'family_tradition', labelKey: 'options.s1_hiloni_jewish_identity.family_tradition' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
];

// ========== BACKGROUND QUESTIONS (Section 2) ==========
export const BACKGROUND_QUESTIONS: SFQuestion[] = [
  {
    id: 's2_ethnic',
    type: 'singleChoice',
    textKey: 'questions.s2_ethnic.text',
    category: 'background',
    forSelf: true,
    forPartner: false,
    allowCustom: true,
    options: [
      { value: 'ashkenazi', labelKey: 'options.s2_ethnic.ashkenazi' },
      { value: 'sephardi_moroccan', labelKey: 'options.s2_ethnic.sephardi_moroccan' },
      { value: 'sephardi_iraqi', labelKey: 'options.s2_ethnic.sephardi_iraqi' },
      { value: 'sephardi_tunisian', labelKey: 'options.s2_ethnic.sephardi_tunisian' },
      { value: 'sephardi_libyan', labelKey: 'options.s2_ethnic.sephardi_libyan' },
      { value: 'sephardi_yemenite', labelKey: 'options.s2_ethnic.sephardi_yemenite' },
      { value: 'sephardi_persian', labelKey: 'options.s2_ethnic.sephardi_persian' },
      { value: 'sephardi_turkish', labelKey: 'options.s2_ethnic.sephardi_turkish' },
      { value: 'ethiopian', labelKey: 'options.s2_ethnic.ethiopian' },
      { value: 'russian_ukrainian', labelKey: 'options.s2_ethnic.russian_ukrainian' },
      { value: 'american', labelKey: 'options.s2_ethnic.american' },
      { value: 'french', labelKey: 'options.s2_ethnic.french' },
      { value: 'argentinian', labelKey: 'options.s2_ethnic.argentinian' },
      { value: 'mixed', labelKey: 'options.s2_ethnic.mixed' },
      { value: 'other_ethnic', labelKey: 'options.s2_ethnic.other_ethnic', isCustomInput: true },
    ],
  },
  {
    id: 's2_origin',
    type: 'singleChoice',
    textKey: 'questions.s2_origin.text',
    category: 'background',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'sabra', labelKey: 'options.s2_origin.sabra' },
      { value: 'sabra_parents_olim', labelKey: 'options.s2_origin.sabra_parents_olim' },
      { value: 'oleh_veteran', labelKey: 'options.s2_origin.oleh_veteran' },
      { value: 'oleh_mid', labelKey: 'options.s2_origin.oleh_mid' },
      { value: 'oleh_new', labelKey: 'options.s2_origin.oleh_new' },
      { value: 'abroad_planning', labelKey: 'options.s2_origin.abroad_planning' },
    ],
  },
  {
    id: 's2_oleh_origin',
    type: 'singleChoice',
    textKey: 'questions.s2_oleh_origin.text',
    category: 'background',
    forSelf: true,
    forPartner: false,
    allowCustom: true,
    conditions: {
      requiredAnswers: [{ questionId: 's2_origin', values: ['oleh_veteran', 'oleh_mid', 'oleh_new', 'abroad_planning'] }],
    },
    options: [
      { value: 'usa', labelKey: 'options.s2_oleh_origin.usa' },
      { value: 'uk', labelKey: 'options.s2_oleh_origin.uk' },
      { value: 'france', labelKey: 'options.s2_oleh_origin.france' },
      { value: 'russia_ukraine', labelKey: 'options.s2_oleh_origin.russia_ukraine' },
      { value: 'ethiopia', labelKey: 'options.s2_oleh_origin.ethiopia' },
      { value: 'argentina', labelKey: 'options.s2_oleh_origin.argentina' },
      { value: 'australia', labelKey: 'options.s2_oleh_origin.australia' },
      { value: 'south_africa', labelKey: 'options.s2_oleh_origin.south_africa' },
      { value: 'canada', labelKey: 'options.s2_oleh_origin.canada' },
      { value: 'other_country', labelKey: 'options.s2_oleh_origin.other_country', isCustomInput: true },
    ],
  },
  {
    id: 's2_oleh_years',
    type: 'singleChoice',
    textKey: 'questions.s2_oleh_years.text',
    category: 'background',
    forSelf: true,
    forPartner: false,
    conditions: {
      requiredAnswers: [{ questionId: 's2_origin', values: ['oleh_veteran', 'oleh_mid', 'oleh_new'] }],
    },
    options: [
      { value: 'less_3', labelKey: 'options.s2_oleh_years.less_3' },
      { value: '3_7', labelKey: 'options.s2_oleh_years.3_7' },
      { value: '7_15', labelKey: 'options.s2_oleh_years.7_15' },
      { value: 'more_15', labelKey: 'options.s2_oleh_years.more_15' },
    ],
  },
  {
    id: 's2_family_extended',
    type: 'singleChoice',
    textKey: 'questions.s2_family_extended.text',
    category: 'background',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'very_close', labelKey: 'options.s2_family_extended.very_close' },
      { value: 'close', labelKey: 'options.s2_family_extended.close' },
      { value: 'medium', labelKey: 'options.s2_family_extended.medium' },
      { value: 'distant', labelKey: 'options.s2_family_extended.distant' },
      { value: 'disconnected', labelKey: 'options.s2_family_extended.disconnected' },
    ],
  },
  {
    id: 's2_family_atmosphere',
    type: 'singleChoice',
    textKey: 'questions.s2_family_atmosphere.text',
    category: 'background',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'warm_vibrant', labelKey: 'options.s2_family_atmosphere.warm_vibrant' },
      { value: 'quiet_intimate', labelKey: 'options.s2_family_atmosphere.quiet_intimate' },
      { value: 'liberal_open', labelKey: 'options.s2_family_atmosphere.liberal_open' },
      { value: 'conservative_traditional', labelKey: 'options.s2_family_atmosphere.conservative_traditional' },
      { value: 'disciplined_values', labelKey: 'options.s2_family_atmosphere.disciplined_values' },
      { value: 'chaotic_free', labelKey: 'options.s2_family_atmosphere.chaotic_free' },
    ],
  },
  {
    id: 's2_parents_status',
    type: 'singleChoice',
    textKey: 'questions.s2_parents_status.text',
    category: 'background',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'married_happy', labelKey: 'options.s2_parents_status.married_happy' },
      { value: 'married_complex', labelKey: 'options.s2_parents_status.married_complex' },
      { value: 'divorced', labelKey: 'options.s2_parents_status.divorced' },
      { value: 'one_passed', labelKey: 'options.s2_parents_status.one_passed' },
      { value: 'both_passed', labelKey: 'options.s2_parents_status.both_passed' },
      { value: 'dont_know', labelKey: 'options.s2_parents_status.dont_know' },
    ],
  },
  {
    id: 's2_relationship_parents',
    type: 'singleChoice',
    textKey: 'questions.s2_relationship_parents.text',
    category: 'background',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'very_close', labelKey: 'options.s2_relationship_parents.very_close' },
      { value: 'close', labelKey: 'options.s2_relationship_parents.close' },
      { value: 'medium', labelKey: 'options.s2_relationship_parents.medium' },
      { value: 'complex', labelKey: 'options.s2_relationship_parents.complex' },
      { value: 'distant', labelKey: 'options.s2_relationship_parents.distant' },
    ],
  },
];

// ========== BACKGROUND PARTNER + NEW SELF QUESTIONS ==========
export const BACKGROUND_EXTRA_QUESTIONS: SFQuestion[] = [
  // New self: family size
  {
    id: 's2_family_size',
    type: 'singleChoice',
    textKey: 'questions.s2_family_size.text',
    category: 'background',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'only_child', labelKey: 'options.s2_family_size.only_child' },
      { value: 'small_family', labelKey: 'options.s2_family_size.small_family' },
      { value: 'medium_family', labelKey: 'options.s2_family_size.medium_family' },
      { value: 'big_family_origin', labelKey: 'options.s2_family_size.big_family_origin' },
    ],
  },
  // Partner: ethnic preference
  {
    id: 'p_ethnic_preference',
    type: 'multiSelect',
    textKey: 'questions.p_ethnic_preference.text',
    subtitleKey: 'questions.p_ethnic_preference.subtitle',
    category: 'background',
    forSelf: false,
    forPartner: true,
    maxSelections: 5,
    options: [
      { value: 'ashkenazi', labelKey: 'options.s2_ethnic.ashkenazi' },
      { value: 'sephardi_moroccan', labelKey: 'options.s2_ethnic.sephardi_moroccan' },
      { value: 'sephardi_iraqi', labelKey: 'options.s2_ethnic.sephardi_iraqi' },
      { value: 'sephardi_yemenite', labelKey: 'options.s2_ethnic.sephardi_yemenite' },
      { value: 'ethiopian', labelKey: 'options.s2_ethnic.ethiopian' },
      { value: 'russian_ukrainian', labelKey: 'options.s2_ethnic.russian_ukrainian' },
      { value: 'mixed', labelKey: 'options.s2_ethnic.mixed' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
];

// ========== PERSONALITY QUESTIONS (Section 3) ==========
export const PERSONALITY_QUESTIONS: SFQuestion[] = [
  {
    id: 's3_energy_type',
    type: 'slider',
    textKey: 'questions.s3_energy_type.text',
    subtitleKey: 'questions.s3_energy_type.subtitle',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    sliderMin: 0,
    sliderMax: 100,
    sliderLeftKey: 'options.s3_energy_type.very_introverted',
    sliderRightKey: 'options.s3_energy_type.very_extroverted',
  },
  {
    id: 's3_energy_source',
    type: 'multiSelect',
    textKey: 'questions.s3_energy_source.text',
    subtitleKey: 'questions.s3_energy_source.subtitle',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    maxSelections: 3,
    options: [
      { value: 'deep_conversations', labelKey: 'options.s3_energy_source.deep_conversations' },
      { value: 'big_groups', labelKey: 'options.s3_energy_source.big_groups' },
      { value: 'quiet_solitude', labelKey: 'options.s3_energy_source.quiet_solitude' },
      { value: 'physical_movement', labelKey: 'options.s3_energy_source.physical_movement' },
      { value: 'art_creation', labelKey: 'options.s3_energy_source.art_creation' },
      { value: 'learning_reading', labelKey: 'options.s3_energy_source.learning_reading' },
      { value: 'projects_doing', labelKey: 'options.s3_energy_source.projects_doing' },
      { value: 'helping_others', labelKey: 'options.s3_energy_source.helping_others' },
      { value: 'music', labelKey: 'options.s3_energy_source.music' },
      { value: 'nature', labelKey: 'options.s3_energy_source.nature' },
    ],
  },
  {
    id: 's3_character_primary',
    type: 'singleChoice',
    textKey: 'questions.s3_character_primary.text',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'humorous', labelKey: 'options.s3_character_primary.humorous', icon: '😄' },
      { value: 'serious_deep', labelKey: 'options.s3_character_primary.serious_deep', icon: '🤔' },
      { value: 'practical', labelKey: 'options.s3_character_primary.practical', icon: '⚡' },
      { value: 'dreamer', labelKey: 'options.s3_character_primary.dreamer', icon: '🌟' },
      { value: 'leader', labelKey: 'options.s3_character_primary.leader', icon: '🎯' },
      { value: 'supporter', labelKey: 'options.s3_character_primary.supporter', icon: '🤝' },
      { value: 'creative', labelKey: 'options.s3_character_primary.creative', icon: '🎨' },
      { value: 'analytical', labelKey: 'options.s3_character_primary.analytical', icon: '📊' },
      { value: 'empathetic', labelKey: 'options.s3_character_primary.empathetic', icon: '❤️' },
      { value: 'adventurous', labelKey: 'options.s3_character_primary.adventurous', icon: '🏔️' },
    ],
  },
  {
    id: 's3_life_tempo',
    type: 'singleChoice',
    textKey: 'questions.s3_life_tempo.text',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'fast_full', labelKey: 'options.s3_life_tempo.fast_full' },
      { value: 'medium', labelKey: 'options.s3_life_tempo.medium' },
      { value: 'slow_intentional', labelKey: 'options.s3_life_tempo.slow_intentional' },
    ],
  },
  {
    id: 's3_spontaneity',
    type: 'singleChoice',
    textKey: 'questions.s3_spontaneity.text',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'very_planned', labelKey: 'options.s3_spontaneity.very_planned' },
      { value: 'planned_flexible', labelKey: 'options.s3_spontaneity.planned_flexible' },
      { value: 'spontaneous', labelKey: 'options.s3_spontaneity.spontaneous' },
    ],
  },
  {
    id: 's3_humor',
    type: 'multiSelect',
    textKey: 'questions.s3_humor.text',
    subtitleKey: 'questions.s3_humor.subtitle',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    maxSelections: 3,
    options: [
      { value: 'ironic_cynical', labelKey: 'options.s3_humor.ironic_cynical' },
      { value: 'light_playful', labelKey: 'options.s3_humor.light_playful' },
      { value: 'absurd', labelKey: 'options.s3_humor.absurd' },
      { value: 'wordplay', labelKey: 'options.s3_humor.wordplay' },
      { value: 'self_deprecating', labelKey: 'options.s3_humor.self_deprecating' },
      { value: 'dry', labelKey: 'options.s3_humor.dry' },
      { value: 'storytelling', labelKey: 'options.s3_humor.storytelling' },
      { value: 'not_humorous', labelKey: 'options.s3_humor.not_humorous' },
    ],
  },
  {
    id: 's3_conflict',
    type: 'singleChoice',
    textKey: 'questions.s3_conflict.text',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'direct', labelKey: 'options.s3_conflict.direct' },
      { value: 'time_then_talk', labelKey: 'options.s3_conflict.time_then_talk' },
      { value: 'avoidant', labelKey: 'options.s3_conflict.avoidant' },
      { value: 'consensus', labelKey: 'options.s3_conflict.consensus' },
    ],
  },
  {
    id: 's3_social_role',
    type: 'singleChoice',
    textKey: 'questions.s3_social_role.text',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'center', labelKey: 'options.s3_social_role.center' },
      { value: 'active_member', labelKey: 'options.s3_social_role.active_member' },
      { value: 'side_supporter', labelKey: 'options.s3_social_role.side_supporter' },
      { value: 'one_on_one', labelKey: 'options.s3_social_role.one_on_one' },
    ],
  },
  {
    id: 's3_open_character',
    type: 'openText',
    textKey: 'questions.s3_open_character.text',
    subtitleKey: 'questions.s3_open_character.subtitle',
    placeholderKey: 'questions.s3_open_character.placeholder',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    isOptional: true,
    maxCustomLength: 150,
  },
];

// ========== PERSONALITY NEW SELF + PARTNER QUESTIONS ==========
export const PERSONALITY_EXTRA_QUESTIONS: SFQuestion[] = [
  // New self: emotional sensitivity
  {
    id: 's3_sensitivity',
    type: 'singleChoice',
    textKey: 'questions.s3_sensitivity.text',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'very_sensitive', labelKey: 'options.s3_sensitivity.very_sensitive' },
      { value: 'balanced_sensitivity', labelKey: 'options.s3_sensitivity.balanced_sensitivity' },
      { value: 'thick_skinned', labelKey: 'options.s3_sensitivity.thick_skinned' },
    ],
  },
  // New self: approach to change
  {
    id: 's3_change_approach',
    type: 'singleChoice',
    textKey: 'questions.s3_change_approach.text',
    category: 'personality',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'embraces_change', labelKey: 'options.s3_change_approach.embraces_change' },
      { value: 'cautious_change', labelKey: 'options.s3_change_approach.cautious_change' },
      { value: 'stability_seeker', labelKey: 'options.s3_change_approach.stability_seeker' },
    ],
  },
  // Partner: energy type
  {
    id: 'p_energy_type',
    type: 'slider',
    textKey: 'questions.p_energy_type.text',
    subtitleKey: 'questions.p_energy_type.subtitle',
    category: 'personality',
    forSelf: false,
    forPartner: true,
    sliderMin: 0,
    sliderMax: 100,
    sliderLeftKey: 'options.s3_energy_type.very_introverted',
    sliderRightKey: 'options.s3_energy_type.very_extroverted',
  },
  // Partner: energy source
  {
    id: 'p_energy_source',
    type: 'multiSelect',
    textKey: 'questions.p_energy_source.text',
    category: 'personality',
    forSelf: false,
    forPartner: true,
    maxSelections: 3,
    options: [
      { value: 'deep_conversations', labelKey: 'options.s3_energy_source.deep_conversations' },
      { value: 'big_groups', labelKey: 'options.s3_energy_source.big_groups' },
      { value: 'quiet_solitude', labelKey: 'options.s3_energy_source.quiet_solitude' },
      { value: 'physical_movement', labelKey: 'options.s3_energy_source.physical_movement' },
      { value: 'art_creation', labelKey: 'options.s3_energy_source.art_creation' },
      { value: 'learning_reading', labelKey: 'options.s3_energy_source.learning_reading' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: character preferred
  {
    id: 'p_character_preferred',
    type: 'multiSelect',
    textKey: 'questions.p_character_preferred.text',
    subtitleKey: 'questions.p_character_preferred.subtitle',
    category: 'personality',
    forSelf: false,
    forPartner: true,
    maxSelections: 3,
    options: [
      { value: 'humorous', labelKey: 'options.s3_character_primary.humorous', icon: '😄' },
      { value: 'serious_deep', labelKey: 'options.s3_character_primary.serious_deep', icon: '🤔' },
      { value: 'practical', labelKey: 'options.s3_character_primary.practical', icon: '⚡' },
      { value: 'dreamer', labelKey: 'options.s3_character_primary.dreamer', icon: '🌟' },
      { value: 'leader', labelKey: 'options.s3_character_primary.leader', icon: '🎯' },
      { value: 'supporter', labelKey: 'options.s3_character_primary.supporter', icon: '🤝' },
      { value: 'creative', labelKey: 'options.s3_character_primary.creative', icon: '🎨' },
      { value: 'analytical', labelKey: 'options.s3_character_primary.analytical', icon: '📊' },
      { value: 'empathetic', labelKey: 'options.s3_character_primary.empathetic', icon: '❤️' },
      { value: 'adventurous', labelKey: 'options.s3_character_primary.adventurous', icon: '🏔️' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: life tempo
  {
    id: 'p_life_tempo',
    type: 'singleChoice',
    textKey: 'questions.p_life_tempo.text',
    category: 'personality',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'fast_full', labelKey: 'options.s3_life_tempo.fast_full' },
      { value: 'medium', labelKey: 'options.s3_life_tempo.medium' },
      { value: 'slow_intentional', labelKey: 'options.s3_life_tempo.slow_intentional' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: spontaneity
  {
    id: 'p_spontaneity',
    type: 'singleChoice',
    textKey: 'questions.p_spontaneity.text',
    category: 'personality',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'very_planned', labelKey: 'options.s3_spontaneity.very_planned' },
      { value: 'planned_flexible', labelKey: 'options.s3_spontaneity.planned_flexible' },
      { value: 'spontaneous', labelKey: 'options.s3_spontaneity.spontaneous' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: humor
  {
    id: 'p_humor',
    type: 'multiSelect',
    textKey: 'questions.p_humor.text',
    category: 'personality',
    forSelf: false,
    forPartner: true,
    maxSelections: 3,
    options: [
      { value: 'ironic_cynical', labelKey: 'options.s3_humor.ironic_cynical' },
      { value: 'light_playful', labelKey: 'options.s3_humor.light_playful' },
      { value: 'absurd', labelKey: 'options.s3_humor.absurd' },
      { value: 'dry', labelKey: 'options.s3_humor.dry' },
      { value: 'storytelling', labelKey: 'options.s3_humor.storytelling' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: conflict style
  {
    id: 'p_conflict',
    type: 'singleChoice',
    textKey: 'questions.p_conflict.text',
    category: 'personality',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'direct', labelKey: 'options.s3_conflict.direct' },
      { value: 'time_then_talk', labelKey: 'options.s3_conflict.time_then_talk' },
      { value: 'consensus', labelKey: 'options.s3_conflict.consensus' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: social role
  {
    id: 'p_social_role',
    type: 'singleChoice',
    textKey: 'questions.p_social_role.text',
    category: 'personality',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'center', labelKey: 'options.s3_social_role.center' },
      { value: 'active_member', labelKey: 'options.s3_social_role.active_member' },
      { value: 'side_supporter', labelKey: 'options.s3_social_role.side_supporter' },
      { value: 'one_on_one', labelKey: 'options.s3_social_role.one_on_one' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
];

// ========== CAREER QUESTIONS (Section 4) ==========
export const CAREER_QUESTIONS: SFQuestion[] = [
  {
    id: 's4_education_level',
    type: 'singleChoice',
    textKey: 'questions.s4_education_level.text',
    category: 'career',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'high_school', labelKey: 'options.s4_education_level.high_school' },
      { value: 'vocational_cert', labelKey: 'options.s4_education_level.vocational_cert' },
      { value: 'bachelor', labelKey: 'options.s4_education_level.bachelor' },
      { value: 'master', labelKey: 'options.s4_education_level.master' },
      { value: 'phd', labelKey: 'options.s4_education_level.phd' },
      { value: 'yeshiva_only', labelKey: 'options.s4_education_level.yeshiva_only' },
      { value: 'yeshiva_plus', labelKey: 'options.s4_education_level.yeshiva_plus' },
      { value: 'studying_now', labelKey: 'options.s4_education_level.studying_now' },
      { value: 'other_edu', labelKey: 'options.s4_education_level.other_edu' },
    ],
  },
  {
    id: 's4_field',
    type: 'multiSelect',
    textKey: 'questions.s4_field.text',
    subtitleKey: 'questions.s4_field.subtitle',
    category: 'career',
    forSelf: true,
    forPartner: false,
    maxSelections: 3,
    allowCustom: true,
    options: [
      { value: 'tech_hi_tech', labelKey: 'options.s4_field.tech_hi_tech', icon: '💻' },
      { value: 'medicine_health', labelKey: 'options.s4_field.medicine_health', icon: '🏥' },
      { value: 'law', labelKey: 'options.s4_field.law', icon: '⚖️' },
      { value: 'education_teaching', labelKey: 'options.s4_field.education_teaching', icon: '🏫' },
      { value: 'business_finance', labelKey: 'options.s4_field.business_finance', icon: '📊' },
      { value: 'art_design', labelKey: 'options.s4_field.art_design', icon: '🎨' },
      { value: 'construction_real_estate', labelKey: 'options.s4_field.construction_real_estate', icon: '🏗️' },
      { value: 'science_research', labelKey: 'options.s4_field.science_research', icon: '🔬' },
      { value: 'media_communication', labelKey: 'options.s4_field.media_communication', icon: '📻' },
      { value: 'culinary', labelKey: 'options.s4_field.culinary', icon: '🍳' },
      { value: 'security_military', labelKey: 'options.s4_field.security_military', icon: '🛡️' },
      { value: 'religious_career', labelKey: 'options.s4_field.religious_career', icon: '📜' },
      { value: 'therapy_wellness', labelKey: 'options.s4_field.therapy_wellness', icon: '💆' },
      { value: 'social_welfare', labelKey: 'options.s4_field.social_welfare', icon: '🤝' },
      { value: 'entrepreneurship', labelKey: 'options.s4_field.entrepreneurship', icon: '🚀' },
      { value: 'academia', labelKey: 'options.s4_field.academia', icon: '🎓' },
      { value: 'other_field', labelKey: 'options.s4_field.other_field', isCustomInput: true },
    ],
  },
  {
    id: 's4_work_status',
    type: 'singleChoice',
    textKey: 'questions.s4_work_status.text',
    category: 'career',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'employed_full', labelKey: 'options.s4_work_status.employed_full' },
      { value: 'employed_part', labelKey: 'options.s4_work_status.employed_part' },
      { value: 'self_employed', labelKey: 'options.s4_work_status.self_employed' },
      { value: 'entrepreneur', labelKey: 'options.s4_work_status.entrepreneur' },
      { value: 'student_only', labelKey: 'options.s4_work_status.student_only' },
      { value: 'student_working', labelKey: 'options.s4_work_status.student_working' },
      { value: 'kollel', labelKey: 'options.s4_work_status.kollel' },
      { value: 'seeking', labelKey: 'options.s4_work_status.seeking' },
      { value: 'other_work', labelKey: 'options.s4_work_status.other_work' },
    ],
  },
  {
    id: 's4_ambition',
    type: 'singleChoice',
    textKey: 'questions.s4_ambition.text',
    category: 'career',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'career_center', labelKey: 'options.s4_ambition.career_center' },
      { value: 'professional_good', labelKey: 'options.s4_ambition.professional_good' },
      { value: 'balance', labelKey: 'options.s4_ambition.balance' },
      { value: 'livelihood_only', labelKey: 'options.s4_ambition.livelihood_only' },
      { value: 'not_defined', labelKey: 'options.s4_ambition.not_defined' },
    ],
  },
  {
    id: 's4_financial_style',
    type: 'singleChoice',
    textKey: 'questions.s4_financial_style.text',
    category: 'career',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'saver', labelKey: 'options.s4_financial_style.saver' },
      { value: 'investor', labelKey: 'options.s4_financial_style.investor' },
      { value: 'entrepreneur_risk', labelKey: 'options.s4_financial_style.entrepreneur_risk' },
      { value: 'experiential', labelKey: 'options.s4_financial_style.experiential' },
      { value: 'simple', labelKey: 'options.s4_financial_style.simple' },
      { value: 'generous', labelKey: 'options.s4_financial_style.generous' },
    ],
  },
  {
    id: 's4_economic_status',
    type: 'singleChoice',
    textKey: 'questions.s4_economic_status.text',
    category: 'career',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'very_stable', labelKey: 'options.s4_economic_status.very_stable' },
      { value: 'stable', labelKey: 'options.s4_economic_status.stable' },
      { value: 'building', labelKey: 'options.s4_economic_status.building' },
      { value: 'family_support', labelKey: 'options.s4_economic_status.family_support' },
      { value: 'challenging', labelKey: 'options.s4_economic_status.challenging' },
    ],
  },
  {
    id: 's4_housing',
    type: 'singleChoice',
    textKey: 'questions.s4_housing.text',
    category: 'career',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'owns', labelKey: 'options.s4_housing.owns' },
      { value: 'renting', labelKey: 'options.s4_housing.renting' },
      { value: 'with_parents', labelKey: 'options.s4_housing.with_parents' },
      { value: 'dorm_shared', labelKey: 'options.s4_housing.dorm_shared' },
    ],
  },
  {
    id: 's4_partner_career',
    type: 'singleChoice',
    textKey: 'questions.s4_partner_career.text',
    subtitleKey: 'questions.s4_partner_career.subtitle',
    category: 'career',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'ambitious_career', labelKey: 'options.s4_partner_career.ambitious_career' },
      { value: 'stable_income', labelKey: 'options.s4_partner_career.stable_income' },
      { value: 'not_important', labelKey: 'options.s4_partner_career.not_important' },
      { value: 'balance_family', labelKey: 'options.s4_partner_career.balance_family' },
      { value: 'whatever_happy', labelKey: 'options.s4_partner_career.whatever_happy' },
    ],
  },
];

// ========== CAREER NEW SELF + PARTNER QUESTIONS ==========
export const CAREER_EXTRA_QUESTIONS: SFQuestion[] = [
  // New self: life priority
  {
    id: 's4_life_priority',
    type: 'singleChoice',
    textKey: 'questions.s4_life_priority.text',
    category: 'career',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'priority_career', labelKey: 'options.s4_life_priority.priority_career', icon: '💼' },
      { value: 'priority_family', labelKey: 'options.s4_life_priority.priority_family', icon: '👨‍👩‍👧‍👦' },
      { value: 'priority_growth', labelKey: 'options.s4_life_priority.priority_growth', icon: '🌱' },
      { value: 'priority_faith', labelKey: 'options.s4_life_priority.priority_faith', icon: '🕊️' },
      { value: 'priority_adventure', labelKey: 'options.s4_life_priority.priority_adventure', icon: '🌍' },
    ],
  },
  // New self: money attitude
  {
    id: 's4_money_attitude',
    type: 'singleChoice',
    textKey: 'questions.s4_money_attitude.text',
    category: 'career',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'money_important', labelKey: 'options.s4_money_attitude.money_important' },
      { value: 'money_tool', labelKey: 'options.s4_money_attitude.money_tool' },
      { value: 'money_secondary', labelKey: 'options.s4_money_attitude.money_secondary' },
      { value: 'money_spiritual', labelKey: 'options.s4_money_attitude.money_spiritual' },
    ],
  },
  // Partner: education level
  {
    id: 'p_education_level',
    type: 'multiSelect',
    textKey: 'questions.p_education_level.text',
    category: 'career',
    forSelf: false,
    forPartner: true,
    maxSelections: 3,
    options: [
      { value: 'high_school', labelKey: 'options.s4_education_level.high_school' },
      { value: 'vocational_cert', labelKey: 'options.s4_education_level.vocational_cert' },
      { value: 'bachelor', labelKey: 'options.s4_education_level.bachelor' },
      { value: 'master', labelKey: 'options.s4_education_level.master' },
      { value: 'phd', labelKey: 'options.s4_education_level.phd' },
      { value: 'yeshiva_only', labelKey: 'options.s4_education_level.yeshiva_only' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: field
  {
    id: 'p_field',
    type: 'multiSelect',
    textKey: 'questions.p_field.text',
    category: 'career',
    forSelf: false,
    forPartner: true,
    maxSelections: 5,
    options: [
      { value: 'tech_hi_tech', labelKey: 'options.s4_field.tech_hi_tech', icon: '💻' },
      { value: 'medicine_health', labelKey: 'options.s4_field.medicine_health', icon: '🏥' },
      { value: 'law', labelKey: 'options.s4_field.law', icon: '⚖️' },
      { value: 'education_teaching', labelKey: 'options.s4_field.education_teaching', icon: '🏫' },
      { value: 'business_finance', labelKey: 'options.s4_field.business_finance', icon: '📊' },
      { value: 'art_design', labelKey: 'options.s4_field.art_design', icon: '🎨' },
      { value: 'entrepreneurship', labelKey: 'options.s4_field.entrepreneurship', icon: '🚀' },
      { value: 'therapy_wellness', labelKey: 'options.s4_field.therapy_wellness', icon: '💆' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: ambition
  {
    id: 'p_ambition',
    type: 'singleChoice',
    textKey: 'questions.p_ambition.text',
    category: 'career',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'career_center', labelKey: 'options.s4_ambition.career_center' },
      { value: 'professional_good', labelKey: 'options.s4_ambition.professional_good' },
      { value: 'balance', labelKey: 'options.s4_ambition.balance' },
      { value: 'livelihood_only', labelKey: 'options.s4_ambition.livelihood_only' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: financial style
  {
    id: 'p_financial_style',
    type: 'singleChoice',
    textKey: 'questions.p_financial_style.text',
    category: 'career',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'saver', labelKey: 'options.s4_financial_style.saver' },
      { value: 'investor', labelKey: 'options.s4_financial_style.investor' },
      { value: 'experiential', labelKey: 'options.s4_financial_style.experiential' },
      { value: 'simple', labelKey: 'options.s4_financial_style.simple' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
];

// ========== LIFESTYLE QUESTIONS (Section 5) ==========
export const LIFESTYLE_QUESTIONS: SFQuestion[] = [
  {
    id: 's5_location',
    type: 'multiSelect',
    textKey: 'questions.s5_location.text',
    subtitleKey: 'questions.s5_location.subtitle',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    maxSelections: 3,
    options: [
      { value: 'tel_aviv_gush_dan', labelKey: 'options.s5_location.tel_aviv_gush_dan' },
      { value: 'jerusalem', labelKey: 'options.s5_location.jerusalem' },
      { value: 'bnei_brak', labelKey: 'options.s5_location.bnei_brak' },
      { value: 'haifa_north', labelKey: 'options.s5_location.haifa_north' },
      { value: 'beer_sheva_south', labelKey: 'options.s5_location.beer_sheva_south' },
      { value: 'modiin_shfela', labelKey: 'options.s5_location.modiin_shfela' },
      { value: 'settlements_wb', labelKey: 'options.s5_location.settlements_wb' },
      { value: 'community_yishuv', labelKey: 'options.s5_location.community_yishuv' },
      { value: 'moshav_village', labelKey: 'options.s5_location.moshav_village' },
      { value: 'abroad', labelKey: 'options.s5_location.abroad' },
      { value: 'flexible', labelKey: 'options.s5_location.flexible' },
    ],
  },
  {
    id: 's5_rhythm',
    type: 'singleChoice',
    textKey: 'questions.s5_rhythm.text',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'very_early', labelKey: 'options.s5_rhythm.very_early' },
      { value: 'early', labelKey: 'options.s5_rhythm.early' },
      { value: 'late_morning', labelKey: 'options.s5_rhythm.late_morning' },
      { value: 'night_owl', labelKey: 'options.s5_rhythm.night_owl' },
    ],
  },
  {
    id: 's5_kashrut',
    type: 'singleChoice',
    textKey: 'questions.s5_kashrut.text',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'mehadrin', labelKey: 'options.s5_kashrut.mehadrin' },
      { value: 'regular_kosher', labelKey: 'options.s5_kashrut.regular_kosher' },
      { value: 'kosher_home_not_out', labelKey: 'options.s5_kashrut.kosher_home_not_out' },
      { value: 'not_kosher_jewish', labelKey: 'options.s5_kashrut.not_kosher_jewish' },
      { value: 'vegetarian', labelKey: 'options.s5_kashrut.vegetarian' },
      { value: 'vegan', labelKey: 'options.s5_kashrut.vegan' },
      { value: 'not_relevant', labelKey: 'options.s5_kashrut.not_relevant' },
    ],
  },
  {
    id: 's5_hobbies',
    type: 'multiSelect',
    textKey: 'questions.s5_hobbies.text',
    subtitleKey: 'questions.s5_hobbies.subtitle',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    maxSelections: 6,
    allowCustom: true,
    options: [
      { value: 'reading', labelKey: 'options.s5_hobbies.reading', icon: '📚' },
      { value: 'music_listening', labelKey: 'options.s5_hobbies.music_listening', icon: '🎵' },
      { value: 'music_playing', labelKey: 'options.s5_hobbies.music_playing', icon: '🎸' },
      { value: 'running_fitness', labelKey: 'options.s5_hobbies.running_fitness', icon: '🏃' },
      { value: 'yoga_meditation', labelKey: 'options.s5_hobbies.yoga_meditation', icon: '🧘' },
      { value: 'team_sports', labelKey: 'options.s5_hobbies.team_sports', icon: '⚽' },
      { value: 'cooking_baking', labelKey: 'options.s5_hobbies.cooking_baking', icon: '🍳' },
      { value: 'art_drawing', labelKey: 'options.s5_hobbies.art_drawing', icon: '🎨' },
      { value: 'creative_writing', labelKey: 'options.s5_hobbies.creative_writing', icon: '✍️' },
      { value: 'gardening_nature', labelKey: 'options.s5_hobbies.gardening_nature', icon: '🌿' },
      { value: 'gaming', labelKey: 'options.s5_hobbies.gaming', icon: '🎮' },
      { value: 'tech_programming', labelKey: 'options.s5_hobbies.tech_programming', icon: '💻' },
      { value: 'theater_movies', labelKey: 'options.s5_hobbies.theater_movies', icon: '🎭' },
      { value: 'travel', labelKey: 'options.s5_hobbies.travel', icon: '🌍' },
      { value: 'animals', labelKey: 'options.s5_hobbies.animals', icon: '🐾' },
      { value: 'photography', labelKey: 'options.s5_hobbies.photography', icon: '📷' },
      { value: 'torah_study', labelKey: 'options.s5_hobbies.torah_study', icon: '📜' },
      { value: 'volunteering', labelKey: 'options.s5_hobbies.volunteering', icon: '🙏' },
      { value: 'dance', labelKey: 'options.s5_hobbies.dance', icon: '💃' },
      { value: 'wine_food', labelKey: 'options.s5_hobbies.wine_food', icon: '🍷' },
      { value: 'hiking', labelKey: 'options.s5_hobbies.hiking', icon: '🥾' },
      { value: 'crafts_diy', labelKey: 'options.s5_hobbies.crafts_diy', icon: '🔨' },
      { value: 'other_hobby', labelKey: 'options.s5_hobbies.other_hobby', isCustomInput: true },
    ],
  },
  {
    id: 's5_travel_frequency',
    type: 'singleChoice',
    textKey: 'questions.s5_travel_frequency.text',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'loves_frequent', labelKey: 'options.s5_travel_frequency.loves_frequent' },
      { value: 'occasionally', labelKey: 'options.s5_travel_frequency.occasionally' },
      { value: 'not_interested', labelKey: 'options.s5_travel_frequency.not_interested' },
      { value: 'not_travel_reasons', labelKey: 'options.s5_travel_frequency.not_travel_reasons' },
    ],
  },
  {
    id: 's5_travel_style',
    type: 'multiSelect',
    textKey: 'questions.s5_travel_style.text',
    subtitleKey: 'questions.s5_travel_style.subtitle',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    maxSelections: 3,
    conditions: {
      excludeAnswers: [{ questionId: 's5_travel_frequency', values: ['not_travel_reasons', 'not_interested'] }],
    },
    options: [
      { value: 'backpacking_asia', labelKey: 'options.s5_travel_style.backpacking_asia', icon: '🎒' },
      { value: 'backpacking_south_america', labelKey: 'options.s5_travel_style.backpacking_south_america', icon: '🎒' },
      { value: 'europe_culture', labelKey: 'options.s5_travel_style.europe_culture', icon: '🏛️' },
      { value: 'north_america', labelKey: 'options.s5_travel_style.north_america', icon: '🗽' },
      { value: 'israel_nature', labelKey: 'options.s5_travel_style.israel_nature', icon: '⛺' },
      { value: 'luxury_hotels', labelKey: 'options.s5_travel_style.luxury_hotels', icon: '🏨' },
      { value: 'family_trips', labelKey: 'options.s5_travel_style.family_trips', icon: '👨‍👩‍👧' },
      { value: 'jewish_heritage', labelKey: 'options.s5_travel_style.jewish_heritage', icon: '✡️' },
      { value: 'adventure_extreme', labelKey: 'options.s5_travel_style.adventure_extreme', icon: '🏔️' },
    ],
  },
  {
    id: 's5_pets',
    type: 'singleChoice',
    textKey: 'questions.s5_pets.text',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'loves_has', labelKey: 'options.s5_pets.loves_has' },
      { value: 'likes_ok', labelKey: 'options.s5_pets.likes_ok' },
      { value: 'prefer_without', labelKey: 'options.s5_pets.prefer_without' },
      { value: 'allergic', labelKey: 'options.s5_pets.allergic' },
    ],
  },
  {
    id: 's5_politics',
    type: 'singleChoice',
    textKey: 'questions.s5_politics.text',
    subtitleKey: 'questions.s5_politics.subtitle',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    isOptional: true,
    options: [
      { value: 'left', labelKey: 'options.s5_politics.left' },
      { value: 'center_left', labelKey: 'options.s5_politics.center_left' },
      { value: 'center', labelKey: 'options.s5_politics.center' },
      { value: 'center_right', labelKey: 'options.s5_politics.center_right' },
      { value: 'right', labelKey: 'options.s5_politics.right' },
      { value: 'far_right', labelKey: 'options.s5_politics.far_right' },
      { value: 'religious_right', labelKey: 'options.s5_politics.religious_right' },
      { value: 'charedi_parties', labelKey: 'options.s5_politics.charedi_parties' },
      { value: 'not_engaged', labelKey: 'options.s5_politics.not_engaged' },
    ],
  },
  {
    id: 's5_diet',
    type: 'multiSelect',
    textKey: 'questions.s5_diet.text',
    subtitleKey: 'questions.s5_diet.subtitle',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    isOptional: true,
    maxSelections: 5,
    options: [
      { value: 'vegetarian_diet', labelKey: 'options.s5_diet.vegetarian_diet' },
      { value: 'vegan_diet', labelKey: 'options.s5_diet.vegan_diet' },
      { value: 'gluten_free', labelKey: 'options.s5_diet.gluten_free' },
      { value: 'dairy_free', labelKey: 'options.s5_diet.dairy_free' },
      { value: 'nut_allergy', labelKey: 'options.s5_diet.nut_allergy' },
      { value: 'no_restrictions', labelKey: 'options.s5_diet.no_restrictions' },
    ],
  },
];

// ========== LIFESTYLE NEW SELF + PARTNER QUESTIONS ==========
export const LIFESTYLE_EXTRA_QUESTIONS: SFQuestion[] = [
  // New self: fitness/health
  {
    id: 's5_fitness',
    type: 'singleChoice',
    textKey: 'questions.s5_fitness.text',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'very_active', labelKey: 'options.s5_fitness.very_active' },
      { value: 'moderately_active', labelKey: 'options.s5_fitness.moderately_active' },
      { value: 'not_active', labelKey: 'options.s5_fitness.not_active' },
      { value: 'health_focused', labelKey: 'options.s5_fitness.health_focused' },
    ],
  },
  // New self: smoking
  {
    id: 's5_smoking',
    type: 'singleChoice',
    textKey: 'questions.s5_smoking.text',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'non_smoker', labelKey: 'options.s5_smoking.non_smoker' },
      { value: 'social_smoker', labelKey: 'options.s5_smoking.social_smoker' },
      { value: 'regular_smoker', labelKey: 'options.s5_smoking.regular_smoker' },
      { value: 'quit_smoking', labelKey: 'options.s5_smoking.quit_smoking' },
    ],
  },
  // New self: dress style
  {
    id: 's5_dress_style',
    type: 'singleChoice',
    textKey: 'questions.s5_dress_style.text',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'formal_dress', labelKey: 'options.s5_dress_style.formal_dress' },
      { value: 'casual_dress', labelKey: 'options.s5_dress_style.casual_dress' },
      { value: 'sporty_dress', labelKey: 'options.s5_dress_style.sporty_dress' },
      { value: 'creative_dress', labelKey: 'options.s5_dress_style.creative_dress' },
      { value: 'modest_dress', labelKey: 'options.s5_dress_style.modest_dress' },
    ],
  },
  // New self: open to abroad
  {
    id: 's5_open_abroad',
    type: 'singleChoice',
    textKey: 'questions.s5_open_abroad.text',
    category: 'lifestyle',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'open_abroad', labelKey: 'options.s5_open_abroad.open_abroad' },
      { value: 'israel_only', labelKey: 'options.s5_open_abroad.israel_only' },
      { value: 'considering_abroad', labelKey: 'options.s5_open_abroad.considering_abroad' },
    ],
  },
  // Partner: location
  {
    id: 'p_location',
    type: 'multiSelect',
    textKey: 'questions.p_location.text',
    category: 'lifestyle',
    forSelf: false,
    forPartner: true,
    maxSelections: 4,
    options: [
      { value: 'tel_aviv_gush_dan', labelKey: 'options.s5_location.tel_aviv_gush_dan' },
      { value: 'jerusalem', labelKey: 'options.s5_location.jerusalem' },
      { value: 'bnei_brak', labelKey: 'options.s5_location.bnei_brak' },
      { value: 'haifa_north', labelKey: 'options.s5_location.haifa_north' },
      { value: 'beer_sheva_south', labelKey: 'options.s5_location.beer_sheva_south' },
      { value: 'modiin_shfela', labelKey: 'options.s5_location.modiin_shfela' },
      { value: 'settlements_wb', labelKey: 'options.s5_location.settlements_wb' },
      { value: 'flexible', labelKey: 'options.s5_location.flexible' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: rhythm
  {
    id: 'p_rhythm',
    type: 'singleChoice',
    textKey: 'questions.p_rhythm.text',
    category: 'lifestyle',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'very_early', labelKey: 'options.s5_rhythm.very_early' },
      { value: 'early', labelKey: 'options.s5_rhythm.early' },
      { value: 'night_owl', labelKey: 'options.s5_rhythm.night_owl' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: kashrut
  {
    id: 'p_kashrut',
    type: 'singleChoice',
    textKey: 'questions.p_kashrut.text',
    category: 'lifestyle',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'mehadrin', labelKey: 'options.s5_kashrut.mehadrin' },
      { value: 'regular_kosher', labelKey: 'options.s5_kashrut.regular_kosher' },
      { value: 'kosher_home_not_out', labelKey: 'options.s5_kashrut.kosher_home_not_out' },
      { value: 'not_kosher_jewish', labelKey: 'options.s5_kashrut.not_kosher_jewish' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: shared hobbies
  {
    id: 'p_shared_hobbies',
    type: 'multiSelect',
    textKey: 'questions.p_shared_hobbies.text',
    subtitleKey: 'questions.p_shared_hobbies.subtitle',
    category: 'lifestyle',
    forSelf: false,
    forPartner: true,
    maxSelections: 5,
    options: [
      { value: 'reading', labelKey: 'options.s5_hobbies.reading', icon: '📚' },
      { value: 'music_listening', labelKey: 'options.s5_hobbies.music_listening', icon: '🎵' },
      { value: 'running_fitness', labelKey: 'options.s5_hobbies.running_fitness', icon: '🏃' },
      { value: 'yoga_meditation', labelKey: 'options.s5_hobbies.yoga_meditation', icon: '🧘' },
      { value: 'cooking_baking', labelKey: 'options.s5_hobbies.cooking_baking', icon: '🍳' },
      { value: 'travel', labelKey: 'options.s5_hobbies.travel', icon: '🌍' },
      { value: 'hiking', labelKey: 'options.s5_hobbies.hiking', icon: '🥾' },
      { value: 'torah_study', labelKey: 'options.s5_hobbies.torah_study', icon: '📜' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: travel frequency
  {
    id: 'p_travel_frequency',
    type: 'singleChoice',
    textKey: 'questions.p_travel_frequency.text',
    category: 'lifestyle',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'loves_frequent', labelKey: 'options.s5_travel_frequency.loves_frequent' },
      { value: 'occasionally', labelKey: 'options.s5_travel_frequency.occasionally' },
      { value: 'not_interested', labelKey: 'options.s5_travel_frequency.not_interested' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: pets
  {
    id: 'p_pets',
    type: 'singleChoice',
    textKey: 'questions.p_pets.text',
    category: 'lifestyle',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'loves_has', labelKey: 'options.s5_pets.loves_has' },
      { value: 'likes_ok', labelKey: 'options.s5_pets.likes_ok' },
      { value: 'prefer_without', labelKey: 'options.s5_pets.prefer_without' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: politics
  {
    id: 'p_politics',
    type: 'singleChoice',
    textKey: 'questions.p_politics.text',
    category: 'lifestyle',
    forSelf: false,
    forPartner: true,
    isOptional: true,
    options: [
      { value: 'same_as_me', labelKey: 'options.p_politics.same_as_me' },
      { value: 'similar_range', labelKey: 'options.p_politics.similar_range' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: diet
  {
    id: 'p_diet',
    type: 'singleChoice',
    textKey: 'questions.p_diet.text',
    category: 'lifestyle',
    forSelf: false,
    forPartner: true,
    isOptional: true,
    options: [
      { value: 'same_as_me', labelKey: 'options.p_diet_pref.same_as_me' },
      { value: 'flexible', labelKey: 'options.p_diet_pref.flexible' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: smoking
  {
    id: 'p_smoking',
    type: 'singleChoice',
    textKey: 'questions.p_smoking.text',
    category: 'lifestyle',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'non_smoker_only', labelKey: 'options.p_smoking.non_smoker_only' },
      { value: 'social_ok', labelKey: 'options.p_smoking.social_ok' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
];

// ========== FAMILY QUESTIONS (Section 6) ==========
export const FAMILY_QUESTIONS: SFQuestion[] = [
  {
    id: 's6_children_count',
    type: 'singleChoice',
    textKey: 'questions.s6_children_count.text',
    category: 'family',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'one_two', labelKey: 'options.s6_children_count.one_two' },
      { value: 'three_four', labelKey: 'options.s6_children_count.three_four' },
      { value: 'five_six', labelKey: 'options.s6_children_count.five_six' },
      { value: 'as_many_as', labelKey: 'options.s6_children_count.as_many_as' },
      { value: 'not_sure', labelKey: 'options.s6_children_count.not_sure' },
      { value: 'dont_want', labelKey: 'options.s6_children_count.dont_want' },
      { value: 'have_enough', labelKey: 'options.s6_children_count.have_enough' },
    ],
  },
  {
    id: 's6_home_roles',
    type: 'singleChoice',
    textKey: 'questions.s6_home_roles.text',
    category: 'family',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'full_sharing', labelKey: 'options.s6_home_roles.full_sharing' },
      { value: 'traditional', labelKey: 'options.s6_home_roles.traditional' },
      { value: 'flexible', labelKey: 'options.s6_home_roles.flexible' },
      { value: 'both_work_help', labelKey: 'options.s6_home_roles.both_work_help' },
      { value: 'she_works_too', labelKey: 'options.s6_home_roles.she_works_too' },
    ],
  },
  {
    id: 's6_parenting_style',
    type: 'singleChoice',
    textKey: 'questions.s6_parenting_style.text',
    category: 'family',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'very_involved', labelKey: 'options.s6_parenting_style.very_involved' },
      { value: 'supportive', labelKey: 'options.s6_parenting_style.supportive' },
      { value: 'educating', labelKey: 'options.s6_parenting_style.educating' },
      { value: 'free_developing', labelKey: 'options.s6_parenting_style.free_developing' },
    ],
  },
  {
    id: 's6_education_system',
    type: 'singleChoice',
    textKey: 'questions.s6_education_system.text',
    category: 'family',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'state', labelKey: 'options.s6_education_system.state' },
      { value: 'state_religious', labelKey: 'options.s6_education_system.state_religious' },
      { value: 'charedi', labelKey: 'options.s6_education_system.charedi' },
      { value: 'alternative', labelKey: 'options.s6_education_system.alternative' },
      { value: 'international', labelKey: 'options.s6_education_system.international' },
      { value: 'not_yet', labelKey: 'options.s6_education_system.not_yet' },
    ],
  },
  {
    id: 's6_home_atmosphere',
    type: 'multiSelect',
    textKey: 'questions.s6_home_atmosphere.text',
    subtitleKey: 'questions.s6_home_atmosphere.subtitle',
    category: 'family',
    forSelf: true,
    forPartner: false,
    maxSelections: 3,
    options: [
      { value: 'open_guests', labelKey: 'options.s6_home_atmosphere.open_guests' },
      { value: 'private_family', labelKey: 'options.s6_home_atmosphere.private_family' },
      { value: 'religious_structure', labelKey: 'options.s6_home_atmosphere.religious_structure' },
      { value: 'liberal', labelKey: 'options.s6_home_atmosphere.liberal' },
      { value: 'quiet_order', labelKey: 'options.s6_home_atmosphere.quiet_order' },
      { value: 'lively_noisy', labelKey: 'options.s6_home_atmosphere.lively_noisy' },
    ],
  },
  {
    id: 's6_partner_children',
    type: 'singleChoice',
    textKey: 'questions.s6_partner_children.text',
    category: 'family',
    forSelf: false,
    forPartner: true,
    conditions: { lifeStages: ['first_marriage', 'divorced_no_children', 'returning'] },
    options: [
      { value: 'open_yes', labelKey: 'options.s6_partner_children.open_yes' },
      { value: 'open_depends', labelKey: 'options.s6_partner_children.open_depends' },
      { value: 'prefer_without', labelKey: 'options.s6_partner_children.prefer_without' },
      { value: 'not_ok', labelKey: 'options.s6_partner_children.not_ok' },
    ],
  },
  {
    id: 's6_blended_family',
    type: 'singleChoice',
    textKey: 'questions.s6_blended_family.text',
    category: 'family',
    forSelf: false,
    forPartner: true,
    conditions: { lifeStages: ['divorced_with_children', 'widowed'] },
    options: [
      { value: 'full_parent', labelKey: 'options.s6_blended_family.full_parent' },
      { value: 'supportive_role', labelKey: 'options.s6_blended_family.supportive_role' },
      { value: 'respectful_distance', labelKey: 'options.s6_blended_family.respectful_distance' },
      { value: 'figure_out_together', labelKey: 'options.s6_blended_family.figure_out_together' },
    ],
  },
];

// ========== FAMILY PARTNER QUESTIONS ==========
export const FAMILY_EXTRA_QUESTIONS: SFQuestion[] = [
  // Partner: children count
  {
    id: 'p_children_count',
    type: 'singleChoice',
    textKey: 'questions.p_children_count.text',
    category: 'family',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'one_two', labelKey: 'options.s6_children_count.one_two' },
      { value: 'three_four', labelKey: 'options.s6_children_count.three_four' },
      { value: 'five_six', labelKey: 'options.s6_children_count.five_six' },
      { value: 'as_many_as', labelKey: 'options.s6_children_count.as_many_as' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: home roles
  {
    id: 'p_home_roles',
    type: 'singleChoice',
    textKey: 'questions.p_home_roles.text',
    category: 'family',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'full_sharing', labelKey: 'options.s6_home_roles.full_sharing' },
      { value: 'traditional', labelKey: 'options.s6_home_roles.traditional' },
      { value: 'flexible', labelKey: 'options.s6_home_roles.flexible' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: parenting style
  {
    id: 'p_parenting_style',
    type: 'singleChoice',
    textKey: 'questions.p_parenting_style.text',
    category: 'family',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'very_involved', labelKey: 'options.s6_parenting_style.very_involved' },
      { value: 'supportive', labelKey: 'options.s6_parenting_style.supportive' },
      { value: 'free_developing', labelKey: 'options.s6_parenting_style.free_developing' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: education system
  {
    id: 'p_education_system',
    type: 'singleChoice',
    textKey: 'questions.p_education_system.text',
    category: 'family',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'state', labelKey: 'options.s6_education_system.state' },
      { value: 'state_religious', labelKey: 'options.s6_education_system.state_religious' },
      { value: 'charedi', labelKey: 'options.s6_education_system.charedi' },
      { value: 'alternative', labelKey: 'options.s6_education_system.alternative' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: home atmosphere
  {
    id: 'p_home_atmosphere',
    type: 'multiSelect',
    textKey: 'questions.p_home_atmosphere.text',
    subtitleKey: 'questions.p_home_atmosphere.subtitle',
    category: 'family',
    forSelf: false,
    forPartner: true,
    maxSelections: 3,
    options: [
      { value: 'open_guests', labelKey: 'options.s6_home_atmosphere.open_guests' },
      { value: 'private_family', labelKey: 'options.s6_home_atmosphere.private_family' },
      { value: 'religious_structure', labelKey: 'options.s6_home_atmosphere.religious_structure' },
      { value: 'liberal', labelKey: 'options.s6_home_atmosphere.liberal' },
      { value: 'quiet_order', labelKey: 'options.s6_home_atmosphere.quiet_order' },
      { value: 'lively_noisy', labelKey: 'options.s6_home_atmosphere.lively_noisy' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
];

// ========== RELATIONSHIP QUESTIONS (Section 7) ==========
export const RELATIONSHIP_QUESTIONS: SFQuestion[] = [
  {
    id: 's7_relationship_meaning',
    type: 'multiSelect',
    textKey: 'questions.s7_relationship_meaning.text',
    subtitleKey: 'questions.s7_relationship_meaning.subtitle',
    category: 'relationship',
    forSelf: true,
    forPartner: false,
    maxSelections: 3,
    options: [
      { value: 'partnership_build', labelKey: 'options.s7_relationship_meaning.partnership_build' },
      { value: 'love_emotion', labelKey: 'options.s7_relationship_meaning.love_emotion' },
      { value: 'best_friendship', labelKey: 'options.s7_relationship_meaning.best_friendship' },
      { value: 'home_stability', labelKey: 'options.s7_relationship_meaning.home_stability' },
      { value: 'growth_together', labelKey: 'options.s7_relationship_meaning.growth_together' },
      { value: 'mutual_respect', labelKey: 'options.s7_relationship_meaning.mutual_respect' },
      { value: 'support_each_other', labelKey: 'options.s7_relationship_meaning.support_each_other' },
    ],
  },
  {
    id: 's7_love_language',
    type: 'singleChoice',
    textKey: 'questions.s7_love_language.text',
    category: 'relationship',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'quality_time', labelKey: 'options.s7_love_language.quality_time', icon: '⏰' },
      { value: 'words_affirmation', labelKey: 'options.s7_love_language.words_affirmation', icon: '💬' },
      { value: 'acts_of_service', labelKey: 'options.s7_love_language.acts_of_service', icon: '🛠️' },
      { value: 'physical_touch', labelKey: 'options.s7_love_language.physical_touch', icon: '🤗' },
      { value: 'gifts', labelKey: 'options.s7_love_language.gifts', icon: '🎁' },
    ],
  },
  {
    id: 's7_closeness',
    type: 'singleChoice',
    textKey: 'questions.s7_closeness.text',
    category: 'relationship',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'very_close', labelKey: 'options.s7_closeness.very_close' },
      { value: 'balanced', labelKey: 'options.s7_closeness.balanced' },
      { value: 'independent', labelKey: 'options.s7_closeness.independent' },
    ],
  },
  {
    id: 's7_meeting_pace',
    type: 'singleChoice',
    textKey: 'questions.s7_meeting_pace.text',
    category: 'relationship',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'fast', labelKey: 'options.s7_meeting_pace.fast' },
      { value: 'medium', labelKey: 'options.s7_meeting_pace.medium' },
      { value: 'slow', labelKey: 'options.s7_meeting_pace.slow' },
    ],
  },
  {
    id: 's7_relationship_model',
    type: 'singleChoice',
    textKey: 'questions.s7_relationship_model.text',
    category: 'relationship',
    forSelf: true,
    forPartner: false,
    options: [
      { value: 'equal_partnership', labelKey: 'options.s7_relationship_model.equal_partnership' },
      { value: 'traditional_roles', labelKey: 'options.s7_relationship_model.traditional_roles' },
      { value: 'she_leads', labelKey: 'options.s7_relationship_model.she_leads' },
      { value: 'romantic_expressive', labelKey: 'options.s7_relationship_model.romantic_expressive' },
      { value: 'pragmatic_stable', labelKey: 'options.s7_relationship_model.pragmatic_stable' },
    ],
  },
  {
    id: 's7_open_partner',
    type: 'openText',
    textKey: 'questions.s7_open_partner.text',
    subtitleKey: 'questions.s7_open_partner.subtitle',
    placeholderKey: 'questions.s7_open_partner.placeholder',
    category: 'relationship',
    forSelf: false,
    forPartner: true,
    isOptional: true,
    maxCustomLength: 200,
  },
];

// ========== RELATIONSHIP PARTNER QUESTIONS ==========
export const RELATIONSHIP_EXTRA_QUESTIONS: SFQuestion[] = [
  // Partner: relationship meaning
  {
    id: 'p_relationship_meaning',
    type: 'multiSelect',
    textKey: 'questions.p_relationship_meaning.text',
    subtitleKey: 'questions.p_relationship_meaning.subtitle',
    category: 'relationship',
    forSelf: false,
    forPartner: true,
    maxSelections: 3,
    options: [
      { value: 'partnership_build', labelKey: 'options.s7_relationship_meaning.partnership_build' },
      { value: 'love_emotion', labelKey: 'options.s7_relationship_meaning.love_emotion' },
      { value: 'best_friendship', labelKey: 'options.s7_relationship_meaning.best_friendship' },
      { value: 'home_stability', labelKey: 'options.s7_relationship_meaning.home_stability' },
      { value: 'growth_together', labelKey: 'options.s7_relationship_meaning.growth_together' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: love language
  {
    id: 'p_love_language',
    type: 'singleChoice',
    textKey: 'questions.p_love_language.text',
    category: 'relationship',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'quality_time', labelKey: 'options.s7_love_language.quality_time', icon: '⏰' },
      { value: 'words_affirmation', labelKey: 'options.s7_love_language.words_affirmation', icon: '💬' },
      { value: 'acts_of_service', labelKey: 'options.s7_love_language.acts_of_service', icon: '🛠️' },
      { value: 'physical_touch', labelKey: 'options.s7_love_language.physical_touch', icon: '🤗' },
      { value: 'gifts', labelKey: 'options.s7_love_language.gifts', icon: '🎁' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: closeness
  {
    id: 'p_closeness',
    type: 'singleChoice',
    textKey: 'questions.p_closeness.text',
    category: 'relationship',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'very_close', labelKey: 'options.s7_closeness.very_close' },
      { value: 'balanced', labelKey: 'options.s7_closeness.balanced' },
      { value: 'independent', labelKey: 'options.s7_closeness.independent' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
  // Partner: relationship model
  {
    id: 'p_relationship_model',
    type: 'singleChoice',
    textKey: 'questions.p_relationship_model.text',
    category: 'relationship',
    forSelf: false,
    forPartner: true,
    options: [
      { value: 'equal_partnership', labelKey: 'options.s7_relationship_model.equal_partnership' },
      { value: 'traditional_roles', labelKey: 'options.s7_relationship_model.traditional_roles' },
      { value: 'romantic_expressive', labelKey: 'options.s7_relationship_model.romantic_expressive' },
      { value: 'pragmatic_stable', labelKey: 'options.s7_relationship_model.pragmatic_stable' },
      { value: 'doesnt_matter', labelKey: 'options.common.doesnt_matter', icon: '🤷' },
    ],
  },
];

// ========== SECTIONS CONFIG ==========
export const SF_SECTIONS: SFSection[] = [
  {
    id: 'anchor',
    titleKey: 'sections.anchor.title',
    subtitleKey: 'sections.anchor.subtitle',
    icon: '🌟',
    color: 'teal',
    questions: ANCHOR_QUESTIONS,
  },
  {
    id: 'identity',
    titleKey: 'sections.identity.title',
    subtitleKey: 'sections.identity.subtitle',
    icon: '🪞',
    color: 'blue',
    questions: [...IDENTITY_QUESTIONS, ...IDENTITY_PARTNER_QUESTIONS],
  },
  {
    id: 'background',
    titleKey: 'sections.background.title',
    subtitleKey: 'sections.background.subtitle',
    icon: '🌳',
    color: 'green',
    questions: [...BACKGROUND_QUESTIONS, ...BACKGROUND_EXTRA_QUESTIONS],
  },
  {
    id: 'personality',
    titleKey: 'sections.personality.title',
    subtitleKey: 'sections.personality.subtitle',
    icon: '✨',
    color: 'purple',
    questions: [...PERSONALITY_QUESTIONS, ...PERSONALITY_EXTRA_QUESTIONS],
  },
  {
    id: 'career',
    titleKey: 'sections.career.title',
    subtitleKey: 'sections.career.subtitle',
    icon: '💼',
    color: 'orange',
    questions: [...CAREER_QUESTIONS, ...CAREER_EXTRA_QUESTIONS],
  },
  {
    id: 'lifestyle',
    titleKey: 'sections.lifestyle.title',
    subtitleKey: 'sections.lifestyle.subtitle',
    icon: '🎯',
    color: 'pink',
    questions: [...LIFESTYLE_QUESTIONS, ...LIFESTYLE_EXTRA_QUESTIONS],
  },
  {
    id: 'family',
    titleKey: 'sections.family.title',
    subtitleKey: 'sections.family.subtitle',
    icon: '🏡',
    color: 'amber',
    questions: [...FAMILY_QUESTIONS, ...FAMILY_EXTRA_QUESTIONS],
  },
  {
    id: 'relationship',
    titleKey: 'sections.relationship.title',
    subtitleKey: 'sections.relationship.subtitle',
    icon: '💞',
    color: 'rose',
    questions: [...RELATIONSHIP_QUESTIONS, ...RELATIONSHIP_EXTRA_QUESTIONS],
  },
];
